### ISSUE TITLE
Training Instructions

### ISSUE THREAD

**Issue by alimaan2935** [Rikorose/DeepFilterNet#10]
This is really an amazing piece of work @Rikorose 
Could you please add some instructions on how to train this with custom dataset?

**Comment by Rikorose** [comment]
Hi there,

thanks for your interest in DeepFilterNet. I added some instructions to the readme and also fixed some refactoring errors. You may need to update this repo or the libdfdata and DeepFilterNet python wheels.

Please let me know if you need some more help to get started.

**Comment by alimaan2935** [comment]
Thank you :)
