### ISSUE TITLE
question about function "band_mean_norm_erb"

### ISSUE THREAD

**Issue by yemifeng** [Rikorose/DeepFilterNet#100]
Hi, Rikorose
        Thanks for sharing this code! There are some problems for me , could you give me some suggestions? 

        (1) How does the function "band_mean_norm_erb" work , or could you give me some papers to explain this implementation?

        (2) "band_mean_norm_erb" is called by "transforms::erb_norm", "MEAN_NORM_INIT" is used in "transforms::erb_norm" and the number of "MEAN_NORM_INIT" is "[-60.0, -90.0]", so  whether  the numbers [-60.0, -90.0] is determined by experience or obtained through mathematical derivation? 

        Thank you !

**Comment by Rikorose** [comment]
Hi,

(1) This is an exponential moving avg normalization. You should find the Formular or a reference in the DeepFilterNet paper.
(2) These are empirical values. But after a few frames this should not really matter anymore.

**Comment by Rikorose** [comment]
The 40. is just a constant scaling factor. The output is approx. in range [-80; 0] dB. Thus, dividing by 40. and doing the exponential mean normalization gives us a nicer [-1; 1] input distribution. In fact, if the DNN includes some normalizing layers, dividing by -40 does not really matter. The DNN also handles a [-40; 40] input distribution nicely.

**Comment by zuowanbushiwo** [comment]
@Rikorose 
Why not use variance to Normalization  as  Reference paper  formula, is there any bad effect if doing so? 
And   Read carefully Section 2.3 of your article,  flowchart maybe: log-power spectrogram -> normalization->erb band, but in your code maybe: log-power spectrogram ->erb band ->normalization? why?
Thanks!

**Comment by zuowanbushiwo** [comment]
@Rikorose 
Thank you so much for your detailed reply
