### ISSUE TITLE
how to avoid rust

### ISSUE THREAD

**Issue by gigadeplex** [Rikorose/DeepFilterNet#102]
how can I just avoid using the Rust library altogether? Let's say I want to do everything in python, how can I get "spec, erb_feat, spec_feat" without using rust and just python?

**Comment by gigadeplex** [comment]
why is there no option of doing the data loading in python with pytorch?

**Comment by Rikorose** [comment]
Hi currently there is no way to avoid rust and its also no plan to support it. I might consider a patch to support python only if I think it is maintainable.

**Comment by smylab** [comment]
Hi，thank you for your open works
Is the current updated code pyDF and pyDF-data can avoid the execution of RUST code?  meaning that pyDF-data can replace the function of RUST and run directly on python?

**Comment by Rikorose** [comment]
Not sure what you want to say, but nothing has changed, pyDF* are both based on the Rust module. This will most likely not change anytime.
