### ISSUE TITLE
poetry install  is extremely slow when resolving the dependencies

### ISSUE THREAD

**Issue by zuowanbushiwo** [Rikorose/DeepFilterNet#108]
Hi  @Rikorose 
    Hello, thanks for your open source DeepFilterNet work. After PyPI install  and  trying it out, I found the effect and the amount of computation to be excellent.  
     So  I want  studying the network carefully,  and  manual Installation  in win10.
     first , i setup a  conda  env , and download rust  and cargo :  `rustc 1.61.0 (fe5b13d68 2022-05-18)`
     second,   in a  python3.9  conda  env ,   I follow your README : 
```
      pip install torch torchaudio -f https://download.pytorch.org/whl/cpu/torch_stable.html
      pip install maturin poetry
      maturin develop --release -m pyDF/Cargo.toml
      maturin develop --release -m pyDF-data/Cargo.toml
```
These commands have a correct result, key packages: DeepFilterDataLoader and DeepFilterLib   install sucessful.

```
asttokens            2.0.5
CacheControl         0.12.11
cachy                0.3.0
certifi              2022.5.18.1
charset-normalizer   2.0.12
cleo                 0.8.1
clikit               0.6.2
colorama             0.4.5
crashtest            0.3.1
DeepFilterDataLoader 0.2.5rc0
DeepFilterLib        0.2.5rc0
distlib              0.3.4
executing            0.8.3
filelock             3.7.1
html5lib             1.1
icecream             2.1.2
idna                 3.3
importlib-metadata   4.11.4
keyring              23.6.0
lockfile             0.12.2
loguru               0.6.0
maturin              0.12.20
msgpack              1.0.4
numpy                1.22.4
packaging            20.9
pastel               0.2.1
pexpect              4.8.0
pip                  21.2.4
pkginfo              1.8.3
platformdirs         2.5.2
poetry               1.1.13
poetry-core          1.0.8
ptflops              0.6.9
ptyprocess           0.7.0
Pygments             2.12.0
pylev                1.4.0
pyparsing            3.0.9
pywin32-ctypes       0.2.0
requests             2.28.0
requests-toolbelt    0.9.1
setuptools           61.2.0
shellingham          1.4.0
six                  1.16.0
tomli                2.0.1
tomlkit              0.11.0
torch                1.11.0+cpu
torchaudio           0.11.0+cpu
typing_extensions    4.2.0
urllib3              1.26.9
virtualenv           20.14.1
webencodings         0.5.1
wheel                0.37.1
win32-setctime       1.1.0
wincertstore         0.2
zipp                 3.8.0
```

third,   `poetry install -E train -E eval`   or  `poetry install -E train -E eval --no-root`  ， those cmd  are  been blocking and has not returned any results，even after an hour or more.
```
(DeepFilterNet) E:\code\DeepFilterNet\DeepFilterNet>poetry install -E train -E eval --no-root
Updating dependencies
Resolving dependencies...
```
How to fixed it? and  how can debug that where is  blocking ?
Thanks!

**Comment by smylab** [comment]
Hi！
  when I enter the command "maturin develop --release -m pyDF/Cargo.toml" in linux( python3.9.maturin0.11) . The program is stationary and nothing is happening, why?
  
  
  
![11](https://user-images.githubusercontent.com/83106172/187432230-33cf4216-193a-464e-bbcd-6b495d24557c.png)

**Comment by Rikorose** [comment]
maturin is independent of poetry. This issue is not related.

**Comment by smylab** [comment]
> maturin is independent of poetry. This issue is not related.

Thank you for your continued help. I followed the README and successfully executed the first two sentences, but when I entered the third sentence, the program did not respond, why is this? What could be the problem?
      1、pip install torch torchaudio -f https://download.pytorch.org/whl/cpu/torch_stable.html
      2、pip install maturin poetry
      3、maturin develop --release -m pyDF/Cargo.toml
      4、maturin develop --release -m pyDF-data/Cargo.toml

**Comment by Rikorose** [comment]
Could you post the output of `cargo build -p DeepFilterLib` and `cargo build -p DeepFilterDataLoader` ?

**Comment by smylab** [comment]
> Could you post the output of `cargo build -p DeepFilterLib` and `cargo build -p DeepFilterDataLoader` ?
Sorry for the late reply, I've been trying to solve the problem, but unfortunately.
The problem is as follows：

![2](https://user-images.githubusercontent.com/83106172/187914099-e00f4472-3cad-499b-a654-60d7e44877e0.png)


when entered the 'cargo build'  or  `cargo build -p DeepFilterLib` and `cargo build -p DeepFilterDataLoader`,  it's stuck in 'git repository `https://github.com/aldanor/hdf5-rust/`'.

I'm in China, it's hard to git down and always connects timeout. I have downloaded the offline hdf5-rust, but do not know how to deal with

**Comment by Rikorose** [comment]
You can modify the dependency in Cargo.toml to point to a local path instead of the github repo.

```toml
hdf5 = { version = "0.8.1", optional = true, path = "path/to/hdf5-rust/"}
```
