### ISSUE TITLE
Fine Tuning Option

### ISSUE THREAD

**Issue by ndisci** [Rikorose/DeepFilterNet#109]
Hi,
Is there any option to fine-tune the pre-trained models ?
Thanks for your time.

**Comment by youssefabdelm** [comment]
> Hi,
> 
> This is not implemented by the framework. The usual process is straight forward: Load the pretrained weights for all but the last DNN layers. Then, do your normal training on your fine-tune data.

Hey @Rikorose I'd love to finetune on the existing pretrained weights as well. Could you provide a more detailed description or examples on how to go about doing the "load pretrained weights all but for last DNN layers" step? No worries if too lengthy/much of a hassle though.
