### ISSUE TITLE
Run on normal RAM?

### ISSUE THREAD

**Issue by youssefabdelm** [Rikorose/DeepFilterNet#113]
Hi, I've tried to get Colab Pro in order to run this on their higher RAM (which I thought was going to be extra GPU memory) but turns out it's just normal RAM. Is it possible for me to run Deepfilternet on a normal CPU + RAM combination as opposed to use GPU memory? Basically I'm doing this because I'd like to run it on longer files (hour long)

**Comment by Rikorose** [comment]
Hi thanks for your interest in DeepFilterNet. Currently, this is not possibly since we are missing the real time loop of the DNN (#76). Thus, your best option would be to split your files manually into small segments like 1 min and process these individual files.

**Comment by youssefabdelm** [comment]
Ah I see, thank you so much for the explanation!
