### ISSUE TITLE
Package guide error

### ISSUE THREAD

**Issue by guokuan-git** [Rikorose/DeepFilterNet#124]
Hello, I'm a learner. I can't import this package normally. I don't know what's wrong. Please tell me,thanks
 
![1659943483(1)](https://user-images.githubusercontent.com/110777663/183362758-2433daf5-1ac1-4654-a368-11ad76b49b5f.jpg)

**Comment by Rikorose** [comment]
This is the rust module which you probably did not compile.

**Comment by guokuan-git** [comment]
> This is the rust module which you probably did not compile.

This is very useful to me.thanks
