### ISSUE TITLE
Error with maturin (Windows)

### ISSUE THREAD

**Issue by surfingnirvana** [Rikorose/DeepFilterNet#129]
(deepfilternet) C:\NEURAL\DeepFilterNet-main>maturin develop --release -m pyDF/Cargo.toml
📦 Including license file "pyDF\LICENSE"
📦 Including license file "pyDF\LICENSE-APACHE"
📦 Including license file "pyDF\LICENSE-MIT"
🔗 Found pyo3 bindings
🐍 Found CPython 3.8 at C:\ProgramData\Anaconda3\envs\deepfilternet\python.exe
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: numpy>=1.22 in c:\programdata\anaconda3\envs\deepfilternet\lib\site-packages (1.23.2)
   Compiling autocfg v1.1.0
   Compiling target-lexicon v0.12.4
   Compiling proc-macro2 v1.0.43
   Compiling quote v1.0.21
   Compiling unicode-ident v1.0.3
   Compiling syn v1.0.99
   Compiling once_cell v1.13.1
   Compiling serde v1.0.143
   Compiling windows_x86_64_msvc v0.36.1
   Compiling parking_lot_core v0.9.3
   Compiling libc v0.2.132
   Compiling strength_reduce v0.2.3
   Compiling rawpointer v0.2.1
   Compiling scopeguard v1.1.0
   Compiling smallvec v1.9.0
   Compiling cfg-if v1.0.0
   Compiling unindent v0.1.10
   Compiling indoc v1.0.7
   Compiling matrixmultiply v0.3.2
   Compiling num-traits v0.2.15
   Compiling num-integer v0.1.45
   Compiling lock_api v0.4.7
   Compiling windows-sys v0.36.1
   Compiling pyo3-build-config v0.16.5
   Compiling primal-check v0.3.2
   Compiling transpose v0.2.1
   Compiling num-complex v0.4.2
   Compiling pyo3-macros-backend v0.16.5
   Compiling thiserror-impl v1.0.32
   Compiling parking_lot v0.12.1
   Compiling ndarray v0.15.6
   Compiling rustfft v6.0.1
   Compiling pyo3-ffi v0.16.5
   Compiling pyo3 v0.16.5
   Compiling thiserror v1.0.32
   Compiling pyo3-macros v0.16.5
   Compiling realfft v3.0.1
   Compiling deep_filter v0.2.6-pre (C:\NEURAL\DeepFilterNet-main\libDF)
   Compiling numpy v0.16.2
   Compiling DeepFilterLib v0.2.6-pre (C:\NEURAL\DeepFilterNet-main\pyDF)
    Finished release [optimized] target(s) in 1m 20s
📖 Found type stub file at libdf.pyi
📦 Built wheel for CPython 3.8 to C:\Users\user\AppData\Local\Temp\.tmp9iLTdC\DeepFilterLib-0.2.6rc0-cp38-none-win_amd64.whl
🛠  Installed DeepFilterLib-0.2.6-pre

(deepfilternet) C:\NEURAL\DeepFilterNet-main>cd DeepFilterNet

(deepfilternet) C:\NEURAL\DeepFilterNet-main\DeepFilterNet>poetry install -E train -E eval
Installing dependencies from lock file

Package operations: 1 install, 1 update, 0 removals

  • Installing deepfilterdataloader (0.2.5 C:/NEURAL/DeepFilterNet-main/pyDF-data)
  • Updating deepfilterlib (0.2.6rc0 -> 0.2.5 C:/NEURAL/DeepFilterNet-main/pyDF)

  EnvCommandError

  Command C:\ProgramData\Anaconda3\envs\deepfilternet\Scripts\pip.exe install --no-deps -U C:\NEURAL\DeepFilterNet-main\pyDF errored with the following return code 1, and output:
  Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
  Processing c:\neural\deepfilternet-main\pydf
    DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
     pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: 'C:\ProgramData\Anaconda3\envs\deepfilternet\python.exe' 'C:\ProgramData\Anaconda3\envs\deepfilternet\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\user\AppData\Local\Temp\tmpzpqilrdx'
           cwd: C:\Users\user\AppData\Local\Temp\pip-req-build-auzjzjwq
      Complete output (18 lines):
      💥 maturin failed
        Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
        Caused by: `cargo metadata` exited with an error: error: failed to get `deep_filter` as a dependency of package `DeepFilterLib v0.2.6-pre (C:\Users\user\AppData\Local\Temp\pip-req-build-auzjzjwq)`

      Caused by:
        failed to load source for dependency `deep_filter`

      Caused by:
        Unable to update C:\Users\user\AppData\Local\Temp\libDF

      Caused by:
        failed to read `C:\Users\user\AppData\Local\Temp\libDF\Cargo.toml`

      Caused by:
        The system cannot find the path specified. (os error 3)
      Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', 'C:\\Users\\user\\AppData\\Local\\Temp\\pip-modern-metadata-ltcyugjr', '--interpreter', 'C:\\ProgramData\\Anaconda3\\envs\\deepfilternet\\python.exe']' returned non-zero exit status 1.
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory C:\Users\user\AppData\Local\Temp\pip-modern-metadata-ltcyugjr --interpreter C:\ProgramData\Anaconda3\envs\deepfilternet\python.exe`
      ----------------------------------------
  WARNING: Discarding file:///C:/NEURAL/DeepFilterNet-main/pyDF. Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\envs\deepfilternet\python.exe' 'C:\ProgramData\Anaconda3\envs\deepfilternet\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\user\AppData\Local\Temp\tmpzpqilrdx' Check the logs for full command output.
  ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\envs\deepfilternet\python.exe' 'C:\ProgramData\Anaconda3\envs\deepfilternet\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\user\AppData\Local\Temp\tmpzpqilrdx' Check the logs for full command output.

  at C:\ProgramData\Anaconda3\envs\deepfilternet\lib\site-packages\poetry\utils\env.py:1195 in _run
      1191│                 output = subprocess.check_output(
      1192│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1193│                 )
      1194│         except CalledProcessError as e:
    → 1195│             raise EnvCommandError(e, input=input_)
      1196│
      1197│         return decode(output)
      1198│
      1199│     def execute(self, bin, *args, **kwargs):

  EnvCommandError

  Command C:\ProgramData\Anaconda3\envs\deepfilternet\Scripts\pip.exe install --no-deps -U C:\NEURAL\DeepFilterNet-main\pyDF-data errored with the following return code 1, and output:
  Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
  Processing c:\neural\deepfilternet-main\pydf-data
    DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
     pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: 'C:\ProgramData\Anaconda3\envs\deepfilternet\python.exe' 'C:\ProgramData\Anaconda3\envs\deepfilternet\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\user\AppData\Local\Temp\tmp_h7cw0fa'
           cwd: C:\Users\user\AppData\Local\Temp\pip-req-build-_fxp20xr
      Complete output (19 lines):
      💥 maturin failed
        Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
        Caused by: `cargo metadata` exited with an error:     Updating crates.io index
      error: failed to get `deep_filter` as a dependency of package `DeepFilterDataLoader v0.2.6-pre (C:\Users\user\AppData\Local\Temp\pip-req-build-_fxp20xr)`

      Caused by:
        failed to load source for dependency `deep_filter`

      Caused by:
        Unable to update C:\Users\user\AppData\Local\Temp\libDF

      Caused by:
        failed to read `C:\Users\user\AppData\Local\Temp\libDF\Cargo.toml`

      Caused by:
        The system cannot find the path specified. (os error 3)
      Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', 'C:\\Users\\user\\AppData\\Local\\Temp\\pip-modern-metadata-us0mpeoo', '--interpreter', 'C:\\ProgramData\\Anaconda3\\envs\\deepfilternet\\python.exe']' returned non-zero exit status 1.
      Checking for Rust toolchain....
      Running `maturin pep517 write-dist-info --metadata-directory C:\Users\user\AppData\Local\Temp\pip-modern-metadata-us0mpeoo --interpreter C:\ProgramData\Anaconda3\envs\deepfilternet\python.exe`
      ----------------------------------------
  WARNING: Discarding file:///C:/NEURAL/DeepFilterNet-main/pyDF-data. Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\envs\deepfilternet\python.exe' 'C:\ProgramData\Anaconda3\envs\deepfilternet\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\user\AppData\Local\Temp\tmp_h7cw0fa' Check the logs for full command output.
  ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\envs\deepfilternet\python.exe' 'C:\ProgramData\Anaconda3\envs\deepfilternet\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\user\AppData\Local\Temp\tmp_h7cw0fa' Check the logs for full command output.

  at C:\ProgramData\Anaconda3\envs\deepfilternet\lib\site-packages\poetry\utils\env.py:1195 in _run
      1191│                 output = subprocess.check_output(
      1192│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1193│                 )
      1194│         except CalledProcessError as e:
    → 1195│             raise EnvCommandError(e, input=input_)
      1196│
      1197│         return decode(output)
      1198│
      1199│     def execute(self, bin, *args, **kwargs):

**Comment by Rikorose** [comment]
Just to confirm - you have rust/cargo installed?
Could you provide the output of `cargo build`?

**Comment by surfingnirvana** [comment]
This is the output. I had to install hdf5 binaries. But now it compiles. However the issue is still there.

C:\NEURAL\DeepFilterNet>cargo build
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.43
   Compiling quote v1.0.21
   Compiling unicode-ident v1.0.3
   Compiling syn v1.0.99
   Compiling cfg-if v1.0.0
   Compiling serde_derive v1.0.143
   Compiling libm v0.2.5
   Compiling once_cell v1.13.1
   Compiling serde v1.0.143
   Compiling winapi v0.3.9
   Compiling target-lexicon v0.12.4
   Compiling memchr v2.5.0
   Compiling scopeguard v1.1.0
   Compiling winreg v0.10.1
   Compiling version_check v0.9.4
   Compiling libc v0.2.132
   Compiling regex-syntax v0.6.27
   Compiling crossbeam-utils v0.8.11
   Compiling smallvec v1.9.0
   Compiling windows_x86_64_msvc v0.36.1
   Compiling rawpointer v0.2.1
   Compiling strength_reduce v0.2.3
   Compiling parking_lot_core v0.8.5
   Compiling rayon-core v1.9.3
   Compiling ppv-lite86 v0.2.16
   Compiling parking_lot_core v0.9.3
   Compiling hdf5-types v0.8.1 (https://github.com/aldanor/hdf5-rust/#d71b03e1)
   Compiling num_cpus v1.13.1
   Compiling ascii v1.0.0
   Compiling byteorder v1.4.3
   Compiling tinyvec_macros v0.1.0
   Compiling serde_json v1.0.83
   Compiling hdf5 v0.8.1 (https://github.com/aldanor/hdf5-rust/#d71b03e1)
   Compiling log v0.4.17
   Compiling indoc v1.0.7
   Compiling either v1.8.0
   Compiling unindent v0.1.10
   Compiling itoa v1.0.3
   Compiling lazy_static v1.4.0
   Compiling bitflags v1.3.2
   Compiling paste v1.0.8
   Compiling ryu v1.0.11
   Compiling hound v3.4.0
   Compiling claxon v0.4.3
   Compiling roots v0.0.7
   Compiling getrandom v0.2.7
   Compiling instant v0.1.12
   Compiling matrixmultiply v0.3.2
   Compiling num-traits v0.2.15
   Compiling num-integer v0.1.45
   Compiling lock_api v0.4.7
   Compiling memoffset v0.6.5
   Compiling crossbeam-epoch v0.9.10
   Compiling rayon v1.5.3
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling tinyvec v1.6.0
   Compiling ogg v0.8.0
   Compiling rand_core v0.6.3
   Compiling lewton v0.10.2
   Compiling rand_chacha v0.3.1
   Compiling rand_xoshiro v0.6.0
   Compiling crossbeam-channel v0.5.6
   Compiling aho-corasick v0.7.18
   Compiling windows-sys v0.36.1
   Compiling rand v0.8.5
   Compiling crossbeam-deque v0.8.2
   Compiling pyo3-build-config v0.16.5
   Compiling regex v1.6.0
   Compiling rand_distr v0.4.3
   Compiling primal-check v0.3.2
   Compiling transpose v0.2.1
   Compiling libloading v0.7.3
   Compiling parking_lot v0.12.1
   Compiling parking_lot v0.11.2
   Compiling pyo3-ffi v0.16.5
   Compiling pyo3 v0.16.5
   Compiling pyo3-macros-backend v0.16.5
   Compiling thiserror-impl v1.0.32
   Compiling hdf5-derive v0.8.1 (https://github.com/aldanor/hdf5-rust/#d71b03e1)
   Compiling pyo3-macros v0.16.5
   Compiling thiserror v1.0.32
   Compiling hdf5-sys v0.8.1 (https://github.com/aldanor/hdf5-rust/#d71b03e1)
   Compiling num-complex v0.4.2
   Compiling ndarray v0.15.6
   Compiling rustfft v6.0.1
   Compiling ndarray-rand v0.14.0
   Compiling numpy v0.16.2
   Compiling realfft v3.0.1
   Compiling rubato v0.12.0
   Compiling deep_filter v0.2.6-pre (C:\NEURAL\DeepFilterNet\libDF)
   Compiling DeepFilterDataLoader v0.2.6-pre (C:\NEURAL\DeepFilterNet\pyDF-data)
   Compiling DeepFilterLib v0.2.6-pre (C:\NEURAL\DeepFilterNet\pyDF)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 13s

**Comment by Rikorose** [comment]
Hm this builds correctly. Also maturin build the deepfilterlib wheel correctly. Not sure what the issue is with poetry on windows. The problem is, that it does not detect, the deepfilterlib wheel as far as I understand. You could try to install the remaining dependencies via the requirements file.
To get the DeepFilterNet package working you may need to set the pythonpath vairable, but not sure how this works in windows:
```bash
export PYTHONPATH=/path/to/DeeFilterNetRepository/DeepFilterNet
```

**Comment by surfingnirvana** [comment]
I added the DeepFilterNet folder manually to the windows system environment variables. But there is another error now.

C:\NEURAL\DeepFilterNet\DeepFilterNet>poetry install -E train -E eval
Creating virtualenv deepfilternet-kV6PKjDO-py3.9 in C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs
Installing dependencies from lock file

Package operations: 33 installs, 0 updates, 0 removals

  • Installing distlib (0.3.5)
  • Installing filelock (3.7.1)
  • Installing numpy (1.23.1)
  • Installing platformdirs (2.5.2)
  • Installing six (1.16.0)
  • Installing asttokens (2.0.5)
  • Installing certifi (2022.6.15)
  • Installing charset-normalizer (2.1.0)
  • Installing executing (0.9.1)
  • Installing identify (2.5.2)
  • Installing colorama (0.4.5)
  • Installing pastel (0.2.1)
  • Installing cfgv (3.3.1)
  • Installing nodeenv (1.7.0)
  • Installing pygments (2.12.0)
  • Installing pyyaml (6.0)
  • Installing virtualenv (20.16.2)
  • Installing tomli (1.2.3)
  • Installing scipy (1.6.1)
  • Installing urllib3 (1.26.11)
  • Installing toml (0.10.2)
  • Installing idna (3.3)
  • Installing win32-setctime (1.1.0)
  • Installing appdirs (1.4.4)
  • Installing deepfilterdataloader (0.2.5 C:/NEURAL/DeepFilterNet/pyDF-data)
  • Installing loguru (0.6.0)
  • Installing icecream (2.1.3)
  • Installing pystoi (0.3.3)
  • Installing pesq (0.0.3)
  • Installing requests (2.28.1)
  • Installing pre-commit (2.20.0)
  • Installing deepfilterlib (0.2.5 C:/NEURAL/DeepFilterNet/pyDF)
  • Installing poethepoet (0.11.0)

Installing the current project: DeepFilterNet (0.2.6-pre)

------------------------------------------------


C:\NEURAL\DeepFilterNet>python DeepFilterNet/df/enhance.py -m DeepFilterNet2 X:/clean.wav
Traceback (most recent call last):
  File "DeepFilterNet/df/enhance.py", line 13, in <module>
    from df.checkpoint import load_model as load_model_cp
  File "C:\ProgramData\Anaconda3\envs\deepfilternet\lib\site-packages\df\checkpoint.py", line 13, in <module>
    from df.utils import check_finite_module
  File "C:\ProgramData\Anaconda3\envs\deepfilternet\lib\site-packages\df\utils.py", line 22, in <module>
    from torchaudio.functional import resample as ta_resample
  File "C:\ProgramData\Anaconda3\envs\deepfilternet\lib\site-packages\torchaudio\__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "C:\ProgramData\Anaconda3\envs\deepfilternet\lib\site-packages\torchaudio\_extension.py", line 103, in <module>
    _init_extension()
  File "C:\ProgramData\Anaconda3\envs\deepfilternet\lib\site-packages\torchaudio\_extension.py", line 88, in _init_extension
    _load_lib("libtorchaudio")
  File "C:\ProgramData\Anaconda3\envs\deepfilternet\lib\site-packages\torchaudio\_extension.py", line 51, in _load_lib
    torch.ops.load_library(path)
  File "C:\ProgramData\Anaconda3\envs\deepfilternet\lib\site-packages\torch\_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "C:\ProgramData\Anaconda3\envs\deepfilternet\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] The specified procedure could not be found

**Comment by Rikorose** [comment]
As I suggested above, please try to install the remaining requirements via pip and not with poetry.

**Comment by surfingnirvana** [comment]
Good now it is all working. My Anaconda installation had to be updated and cleaned up. I also created the conda environment with python=3.9.0    Then installed requirements with "conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge". Followed the install guide from there. There was a ("No audio backend is available.") warning - fixed it with "conda install -c conda-forge pysoundfile"
