### ISSUE TITLE
Question about loss weight

### ISSUE THREAD

**Issue by TAWHT** [Rikorose/DeepFilterNet#130]
Hi, thanks for this work. I have some questions about loss weight.
I downloaded the models/DeepFilterNet2.zip you provided.
config.ini shows that you only used 3 losses. (localsnrloss spectralloss multiresspecloss)
Is this the correct loss weight setting? If not, can you advise the correct configuration?
Thank you.

[localsnrloss]
factor = 1e-3

[maskloss]
factor = 0
mask = iam
gamma = 0.6
gamma_pred = 0.6
f_under = 1

[spectralloss]
factor_magnitude = 1000
factor_complex = 1000
gamma = 0.3

[dfalphaloss]
factor = 0.0

[multiresspecloss]
factor = 500
factor_complex = 500
gamma = 0.3
fft_sizes = 256,512,1024

[sdrloss]
factor = 0.0
segmental_ws = 0

**Comment by Rikorose** [comment]
These are the correct settings.
