### ISSUE TITLE
maturin failed

### ISSUE THREAD

**Issue by smylab** [Rikorose/DeepFilterNet#135]
![1](https://user-images.githubusercontent.com/83106172/187162475-a43fd15a-82bd-4120-b06a-d625e03e580d.png)
![2](https://user-images.githubusercontent.com/83106172/187164708-5a028ed6-1fd9-467b-a6a2-95c72bc7a779.png)

when I run "maturin develop --release -m pyDF-data/Cargo.toml" on windows 10

It showed :
  Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
  Caused by: failed to start `cargo metadata`: 拒绝访问。 (os error 5)
  Caused by: 拒绝访问。 (os error 5)
  
  so， what can I do to solve the problem.Thanks

**Comment by Rikorose** [comment]
Did you follow the Readme and installed cargo via rustup?

**Comment by smylab** [comment]
> Did you follow the Readme and installed cargo via rustup?

Yes， I have installed cargo vis rustup, the "cargo --version" and "rustc --version" is display is normal

I tried to follow the instructions，entered the command：cargo build.   But the following error occurred that I could not solve

![4](https://user-images.githubusercontent.com/83106172/187227665-0f6c0022-e13a-4d80-b49b-a780dd00d0ee.png)

**Comment by Rikorose** [comment]
You are missing hdf5 headers. You need to install hdf5 with development files if you want the training environment. Note that training on windows is not supported by the DeepFilterNet.
