### ISSUE TITLE
Question about feat_spec shape

### ISSUE THREAD

**Issue by starLitEE** [Rikorose/DeepFilterNet#136]
Hi, thanks for your work. 
I have a question about your cutting off process for DFnet. 
In the paper, you described the model cut off the spectrogram under f_DF=5kHz but I have some confusion about this part.

1. Where can I find cutting off process in the code? Maybe it is in the rust file but I can not find where it is.
2. The shape of noisy and feat_spec is as below. (I recommended "#31 issue".)
 noisy: [batch,1,300,481], feat_spec: [batch,1,300,96]
 You set the fft size as 960, thus I could get 481 by 960//2+1=481.
 But how about 96? First, I thought 48000//10 is almost equal to 5, thus the number of feat_spec frequency bin has to be 481//10 = 48. How can I get 96? 

Thank you for your answer!

**Comment by Rikorose** [comment]
You are confusing sampling rate (48kHz) with nyqist frequency (24kHz). The frequency resolution (i.e. difference between to frequency bins) is 48000/960=50Hz. To get f_DF=5kHz, we need 100 frequency bins. I chose 96 because this is plays better with convolutions an a stride of 2.

**Comment by starLitEE** [comment]
Clear answer! Thank you
