### ISSUE TITLE
Post-filter questions and reducing denoising intensity?

### ISSUE THREAD

**Issue by youssefabdelm** [Rikorose/DeepFilterNet#139]
Hey! Again, thank you so much for making this and for helping us all out so much. This is still probably the best denoising model I've ever come across.

So my questions are:

1. I've checked the post-filter [paper](https://arxiv.org/abs/2008.04259) and still not sure I understand what it's doing. Do I understand correctly that the post-filter intensifies the denoising process for noisier areas or does it make it more tame? 
3. Does adding a post-filter (if it is more 'aggressive with noise reduction') risk reducing intelligibility / increasing artifacts for certain really noisy sections? 
4. What I'm most curious about though is: Is there a way to reduce the intensity of the denoising in the model, to have a little bit of the original signal back in overall? 

(I'm doing this purely to recover certain lost aspects of speech and not to retain any non-speech sounds, certain plosives and sibilants are too rounded off in my case)

Edit: I checked the Deepfilternet2 paper again. It seems with post-filter it performs better on intelligibility (since DNSMOS is designed to be a more accurate intelligibility metric)? Or is that too much of a stretch since without post-filter on PESQ, STOI, and so on is lower with post-filter?)

**Comment by Rikorose** [comment]
Hi,

1. It slightly suppresses very noisy regions and compensates by adding more energy to less noisy regions.
2. It might suppress frequency bins containing speech slightly more, but I would say, this effect is rather little and don't impacts speech intelligibility. This effect is mostly targeted to enhance the overall listening experience (i.e. MOS values), rather speech intelligibility.
3. Yes, you can add some of the original signal back via `--atten-lim`.

**Comment by youssefabdelm** [comment]
Thank you! Regarding `--atten-lim` what sort of input does it take in? 0 to 1?

**Comment by Rikorose** [comment]
```bash
$ deepFilter -h
usage: deepFilter [-h] [--model-base-dir MODEL_BASE_DIR] [--pf] [--output-dir OUTPUT_DIR] [--log-level LOG_LEVEL] [--debug] [--epoch EPOCH] [--compensate-delay] [--atten-lim ATTEN_LIM]
                  noisy_audio_files [noisy_audio_files ...]

positional arguments:
  noisy_audio_files     List of noise files to mix with the clean speech file.

options:
  -h, --help            show this help message and exit
  --model-base-dir MODEL_BASE_DIR, -m MODEL_BASE_DIR
                        Model directory containing checkpoints and config. To load a pretrained model, you may just provide the model name, e.g. `DeepFilterNet`. By default, the
                        pretrained DeepFilterNet2 model is loaded.
  --pf                  Post-filter that slightly over-attenuates very noisy sections.
  --output-dir OUTPUT_DIR, -o OUTPUT_DIR
                        Directory in which the enhanced audio files will be stored.
  --log-level LOG_LEVEL
                        Logger verbosity. Can be one of (debug, info, error, none)
  --debug, -d
  --epoch EPOCH, -e EPOCH
                        Epoch for checkpoint loading. Can be one of ['best', 'latest', <int>].
  --compensate-delay, -D
                        Add some paddig to compensate the delay introduced by the real-time STFT/ISTFT implementation.
  --atten-lim ATTEN_LIM, -a ATTEN_LIM
                        Attenuation limit in dB by mixing the enhanced signal with the noisy signal.
```

You can try 6 dB and increase the attenuation if you need more noise reduction.

**Comment by youssefabdelm** [comment]
Thank you! Will give it a shot
