### ISSUE TITLE
Hidden state inheritance for real-time loop

### ISSUE THREAD

**Issue by JBloodless** [Rikorose/DeepFilterNet#143]
Hi! I'm tryin to implement real-time loop in python, but I'm a bit confused with variety of options. I'm using all of the settings "out of box", except that I modified enhance.py and deepfilternet2.py to perform frame-by-frame enhancing by passing GRU states from previous frame:

```
def enhance(
    model: nn.Module, df_state: DF, audio: Tensor, pad=False, atten_lim_db: Optional[float] = None
):
    model.eval()

    audio_spl = torch.split(audio, 960, dim=1)
    print(len(audio_spl))
    out_buf = None
    h0_erb = torch.zeros(2, 1, 256)
    h0_df = torch.zeros(2, 1, 256)          #init states for ERB and DF decoders

    for audio in audio_spl:

        bs = audio.shape[0]
        if hasattr(model, "reset_h0"):
            model.reset_h0(batch_size=bs, device=get_device())
        orig_len = audio.shape[-1]
        n_fft, hop = 0, 0
        if pad:
            n_fft, hop = df_state.fft_size(), df_state.hop_size()
            # Pad audio to compensate for the delay due to the real-time STFT implementation
            audio = F.pad(audio, (0, n_fft))
        nb_df = getattr(model, "nb_df", getattr(model, "df_bins", ModelParams().nb_df))
        spec, erb_feat, spec_feat = df_features(audio, df_state, nb_df, device=get_device())
        enhanced, h0_erb, h0_df, _, _, _ = model(spec, erb_feat, spec_feat, h0_erb, h0_df)       #updating GRU states
        enhanced = as_complex(enhanced.cpu().squeeze(1))
        if atten_lim_db is not None and abs(atten_lim_db) > 0:
            lim = 10 ** (-abs(atten_lim_db) / 20)
            enhanced = as_complex(spec.squeeze(1)) * lim + enhanced * (1 - lim)
        audio = torch.as_tensor(df_state.synthesis(enhanced.numpy()))
        if pad:
            # The frame size is equal to p.hop_size. Given a new frame, the STFT loop requires e.g.
            # ceil((n_fft-hop)/hop). I.e. for 50% overlap, then hop=n_fft//2
            # requires 1 additional frame lookahead; 75% requires 3 additional frames lookahead.
            # Thus, the STFT/ISTFT loop introduces an algorithmic delay of n_fft - hop.
            assert n_fft % hop == 0  # This is only tested for 50% and 75% overlap
            d = n_fft - hop
            audio = audio[:, d : orig_len + d]
        if out_buf is None:
            out_buf = audio
        else:
            out_buf = torch.cat((out_buf, audio), dim=1)
        print('out_buf ', out_buf.shape)
    return out_buf
```

As far as I found, the only recurrent states that need to be passed are the states of ErbDecoder's and DfDecoder's GRU. What else in the model should be modified to get it right? The results of such inference are very far from ideal.

P.S. I found that in DfOp class in modules.py there are different kinds of forward passes for deep filtering, should I use one of them?

**Comment by JBloodless** [comment]
To be clear, I am getting SOME result the resembles offline mode, so I'm assuming that my problem is somewhere near the surface

![Снимок экрана 2022-10-03 в 19 01 50](https://user-images.githubusercontent.com/8794436/193623863-37780265-0bcf-4708-95d2-9c53e86a6a30.png)

**Comment by Rikorose** [comment]
You also need to modify the convolutional layers over time which requires also buffer handling.

**Comment by JBloodless** [comment]
I guess, it's about TCN layers with 1x3 kernels?

**Comment by Rikorose** [comment]
Yes

**Comment by JBloodless** [comment]
Thanks, I'll try!

**Comment by JBloodless** [comment]
Sorry for bothering you again
Am I right, that I can handle three frames at a time without modifying TCN (since it's not an issue for my purposes)? For example, I can take 3 frames, run them through one iteration and append only last frame to output, then shift one frame further etc. - would it be the right way in terms of quality of final result?

**Comment by Rikorose** [comment]
No, because you will get tons of conv border effects. Also you have a 5x1 convolution over time in df_dec.

**Comment by JBloodless** [comment]
Okay, got it, thanks
