### ISSUE TITLE
Aligning noisy recording with denoised recording

### ISSUE THREAD

**Issue by youssefabdelm** [Rikorose/DeepFilterNet#145]
Hey! I have another model I'm using called STOI-VQCPC (https://github.com/vvvm23/stoi-vqcpc/) which returns continuous intelligibility metrics. 

I've used these to return a list of volume levels so that I can automatically bring back the noisy signal when the audio is too unintelligible. 

The problem I'm facing right now is that I'm getting this phasing issue when overlaying the denoised audio and the noisy audio (possibly due to some delay). 

Ideally of course I want perfect alignment of both noisy and denoised so that no phasing occurs. 

I tried with and without `--compensate-delay` and I used the package `audalign` (https://github.com/benfmiller/audalign) to measure how well the noisy audio aligns with the denoised one. 

Since that package seems to be estimating with all its functions I'm getting different numbers every time, but it seems that even with `--compensate-delay` I'm not getting perfect alignment. 

When I check compensate-delay's number of samples I see that they're nearly identical to the number of samples in the original file: 
orignal file: `1317653 samples`
compensate-delay: `1317654 samples`

And when I check the time difference using `audalign` I get:

`18.588386297225952` when measuring the original and the compensate-delay version (I assume milliseconds)
`15.779815196990967` when measuring the original and the normally denoised one (without compensate-delay). 

This is using their "VisualRecognizer" function which takes longest and seems to be one of their more accurate ones (according to their readme, I'm not that familiar)

I thought about using audalign to align the two files, but again I get some noise in the measurement, everytime I run the funciton it's slightly different. 

I'm trying to locate the reason behind this. How would you recommend I do this such that there's no phasing? 

Is there some set number of milliseconds I can reliably push the denoised or noisy audio to to get perfect alignment or will this always be variable?

**Comment by youssefabdelm** [comment]
With `audalign`'s CorrelationSpectrogramRecognizer, when I do 100 measurements and average them, I get:

`0.25272274017333984` for original and normally denoised (I assume this is in seconds)
`0.25113353967666624` for original and compensate-delay 

With their CorrelationRecognizer there seems to be a discrepancy (100 measurements averaged):

`0.2633010816574097` for original and normally denoised
`0.06403945922851563` for original and compensate-delay

**Comment by Rikorose** [comment]
Hi, I cannot reproduce your findings.
``bash
$ python DeepFilterNet/df/enhance.py assets/noisy_snr0.wav -o out -D
$ soxi assets/noisy_snr0.wav out/noisy_snr0_DeepFilterNet2.wav

Input File     : 'assets/noisy_snr0.wav'
Channels       : 1
Sample Rate    : 48000
Precision      : 16-bit
Duration       : 00:00:10.60 = 508591 samples ~ 794.673 CDDA sectors
File Size      : 1.02M
Bit Rate       : 768k
Sample Encoding: 16-bit Signed Integer PCM


Input File     : 'out/noisy_snr0_DeepFilterNet2.wav'
Channels       : 1
Sample Rate    : 48000
Precision      : 16-bit
Duration       : 00:00:10.60 = 508591 samples ~ 794.673 CDDA sectors
File Size      : 1.02M
Bit Rate       : 768k
Sample Encoding: 16-bit Signed Integer PCM

Total Duration of 2 files: 00:00:21.19

Also you can add back the original noisy signal via `--atten-lim`. And I also tested adding the denoised signal with `-D` and the original noisy signal in time domain and do not get any phase issues.
```

**Comment by youssefabdelm** [comment]
Could it be due to the conversion process? I'm not feeding it 48kHz files. I'll try that and see. I'm aware that I can add back the original noisy signal via `atten-lim` but I wanted to test controlling volume throughout time with the intelligibility scores of a different model instead of having a fixed volume at which it plays.

**Comment by youssefabdelm** [comment]
Okay so it seems when I convert the file to 48kHz before denoising, and use `--compensate-delay` I get the exact same number of samples:

```
The file /content/test_original_48k.wav is: 
29.88 seconds long
29878.77 milliseconds long
has 1434181 samples
------
The file /content/test_original_48k_DeepFilterNet2.wav is:
29.87 seconds long
29870.00 milliseconds long
has 1433760 samples
------
The file /content/test_original_48k_DeepFilterNet2_compensatedelay.wav is: 
29.88 seconds long
29878.77 milliseconds long
has 1434181 samples
```

This is the function I'm using to measure length:

```
from scipy.io import wavfile

def wav_length(wav_file):
    rate, data = wavfile.read(wav_file)
    length = data.shape[0] / rate
    print('The file {} is {:.2f} seconds long'.format(wav_file, length))
    print('The file {} is {:.2f} milliseconds long'.format(wav_file, length * 1000))
    print('The file {} has {} samples'.format(wav_file, data.shape[0]))

```

I'm going to move onto testing alignment as well as fading between them to double-check.

**Comment by youssefabdelm** [comment]
I converted using ffmpeg:

```
import ffmpeg
import os

def convert_wav(file_path, output_path):
    """
    Converts a wav file to 48kHz 16bit using ffmpeg-python
    """
    stream = ffmpeg.input(file_path)
    stream = ffmpeg.output(stream, output_path, acodec='pcm_s16le', ac=1, ar='48k')
    #Now let's export to a file
    ffmpeg.run(stream)
```

I think I recognize my error now. 

I may have been comparing the original signal (44.1kHz) to the denoised signal (48kHz) which was causing this slight delay between the two.
