### ISSUE TITLE
Problems of training from scratch

### ISSUE THREAD

**Issue by jyhan03** [Rikorose/DeepFilterNet#146]
Hi, thanks for the good work. According to the GitHub page, we have installed this software many times, but still can't train it on our machine. During installation, we found some issues and tried to modify them to make the whole process continue. 

For data preparation, the `python df/prepare_data.py` was changed to `python df/scripts/prepare_data.py`, as we found the `prepare_data.py` actually located in the `df/scripts`.

For `pip install poetry`, when started with `poetry install -E train -E eval --no-root`,  we encountered a `No module named 'packaging'` error. Then we adpoted `pip uninstall poetry` and `conda install poetry` to solve the problem.

Untill now, it seems that the whole installation has finished and we haven't found other installation errors.

But when using `python df/train.py`, we encountered another problem as follows:
![2](https://user-images.githubusercontent.com/48471602/194279981-34e56a90-37b6-4068-aeda-7e4337ba3f02.png)

Then we change the `df/stoi.py` to import `resample` from `df/io.py` rather than `df/utils.py`. In this way, the training command seems to able to work.

However, we found another memory problem as follows:
![3](https://user-images.githubusercontent.com/48471602/194280901-740d5389-0190-4d8b-a9f8-452a8b9c7216.png)

In addition, we also tried to install this software on other machines, but still would be troubled with the above problems. Have you ever encounted these and what should we do to solve them?

**Comment by Rikorose** [comment]
Hi, these two issues are fixed on some newer branches but not yet merged into master and also don't have a release ready.
The second error is due to some changes in pytorch 1.12. An easy fix would be to train with pytorch 1.11 for now, or wait for new DeepFilterNet release.

**Comment by Rikorose** [comment]
Yea I refactored this but forgot to also change the import. Your fix is fine and will be included in a new release.

**Comment by jyhan03** [comment]
Thanks again. The training process seems normal after I changed Pytorch to 1.11. Looking forward to the new release.
