### ISSUE TITLE
different from the paper

### ISSUE THREAD

**Issue by CaoYuhang** [Rikorose/DeepFilterNet#147]
https://github.com/Rikorose/DeepFilterNet/blob/2dfc3d0305de1f87ed8b91d120210ffc20656979/DeepFilterNet/df/deepfilternet2.py#L235

Hi, Thank you for your awesome work, I find that in this line  you use conv_layer not tconv_layer, a little different from the paper?

**Comment by Rikorose** [comment]
Hi, for this layer, it does not matter if its a normal or a transposed convolution since the stride is 1 anyway.
