### ISSUE TITLE
processing multiple files at the same time

### ISSUE THREAD

**Issue by Chopin68** [Rikorose/DeepFilterNet#148]
The noise reduction effect is extremely good,If only I could handle multiple WAVs or paths with one click,Would anyone like to share his batch processing code? Thank you very much. It will help me learn.

**Comment by Chopin68** [comment]
I think I found a simple way to put multiple audio file names in the audio folder where noise reduction is required and run them on the command line. I did it

**Comment by QQQQQQQQY** [comment]
> 我想我找到了一种简单的方法，可以将多个音频文件名放在需要降噪的音频文件夹中，并在命令行上运行它们。我成功了
你好，可以分享下这个办法吗，我最近也在寻找这个问题答案，期待你的回复
