### ISSUE TITLE
Problems with the new version 0.3.0

### ISSUE THREAD

**Issue by yurinoviello** [Rikorose/DeepFilterNet#156]
I have found some problems using the new version of the package on pip.

Using as input a 'wav' file of 46MB I encountered the following error

_RuntimeError: CUDA out of memory. Tried to allocate 38.09 GiB_

I restored the previous version (0.2.5) and it runs as before.

Hardware: RTX 2080S

**Comment by Rikorose** [comment]
OK interesting. Could you give some more details on the audio file? Length, channels, sampling rate?

Also could you measure the memory consumption on 0.2.5 e.g. with nvidia smi?

**Comment by yurinoviello** [comment]
Audio details:
```
Channels: 2
Sample width: 2
Frame rate (sample rate): 44100
Frame width: 4
Length (ms): 260017
Frame count: 11466752.0
Intensity: -34.475185718792
```

Memory consumption on 0.2.5:
```
nvidia-smi -l 1 | grep python
|    0   N/A  N/A     47967      C   ...a3/envs/DFN/bin/python3.9      409MiB |
|    0   N/A  N/A     47967      C   ...a3/envs/DFN/bin/python3.9      779MiB |
|    0   N/A  N/A     47967      C   ...a3/envs/DFN/bin/python3.9     4721MiB |
|    0   N/A  N/A     47967      C   ...a3/envs/DFN/bin/python3.9     6347MiB |
```

**Comment by Rikorose** [comment]
So the issue is related to [GroupedLinearEinsum processing](https://github.com/Rikorose/DeepFilterNet/blob/8509133/DeepFilterNet/df/modules.py#L771).

This change was necessary to get the Rust processing working, but will eventually change it back to einsum for an efficient pytorch/GPU processing again.

**Comment by Rikorose** [comment]
Thanks for reporting!
