### ISSUE TITLE
Experiments: w/o stage 2

### ISSUE THREAD

**Issue by smylab** [Rikorose/DeepFilterNet#157]
Thank you for your outstanding contribution, I have some questions about the experimental part of the article, what is the w/o indicator, and why was only stage2 was compared in the comparison experiment？

![QQ图片20221022104757](https://user-images.githubusercontent.com/83106172/197315802-cd9b3e62-3437-42d7-b20e-cdc729f78659.png)

**Comment by Rikorose** [comment]
Hi, w/o stands for without. So this row means that the audio files were only enhanced using the first stage (ERB gains), and not with the 2nd stage (deep filtering).
