### ISSUE TITLE
Model in real-time implementation

### ISSUE THREAD

**Issue by JBloodless** [Rikorose/DeepFilterNet#164]
Thanks for real-time implementation of DeepFilterNet! I have a question regarding that. Is the default model used for RT enhancement same as offline one? I watched WIP branch for some time, and there was another one with 0 lookaheads. Did you use that one for RT loop? If not, can you probably share config.ini for new model to train it from scratch? 

Follow-up: is it still possible to run real-time loop from Rust (without shipped binaries) using libDF/src/bin/enhance_wav.rs ?

**Comment by Rikorose** [comment]
Hi, the default model used in `deep-filter` is the standard DeepFilterNet2 model. However, you may specify a different model via `deep-filter -m <path to model.tar.gz>`. The weights for the low latency model (ll) can be found in `models/DeepFilterNet2_onnx_ll.tar.gz`. This also includes the `config.ini` file.

For the ladspa plugin, I use the ll model by default.

**Comment by Rikorose** [comment]
Yes. Note that the binary was renamed to deep-filter. So use `cargo run - - bin deep-filter -- audio.wav`

**Comment by JBloodless** [comment]
Thanks a lot!

**Comment by codonna9** [comment]
@Rikorose  Thanks again for making this open-source. I'm trying to learn from it.
I have a question on how to train the real-time version of DeepFilterNet2. 
From what I've read so far, I can use the "config.ini" file in the file "DeepFilterNet2_onnx_ll.tar.gz", put this config file into a "base_dir" directory, prepare the dataset & train real-time models using this command (as in the README):
python df/train.py path/to/dataset.cfg path/to/data_dir/ path/to/base_dir/

Please, let me know if I got this right. Thanks a lot.

**Comment by Rikorose** [comment]
Looks good
