### ISSUE TITLE
Questions about deepfilter1 code

### ISSUE THREAD

**Issue by Eie1** [Rikorose/DeepFilterNet#178]
Thanks for your  code , it is really helpful for my work

Could I ask some questions about the code?

I input such follows into the net,is it right?
test_spec=torch.randn(7,1, 501, 481, 2)
        test_erb = torch.randn(7, 1, 501, 32)
        test_feac= torch.randn(7, 2, 501, 481) 
spec, m, lsnr, df_alpha = self.net(spec=test_spec,feat_erb=test_erb,feat_spec=test_feac)

and I  only change code in dfnet by commenting  out  the first line, and I did not change any other code in deepfilter:
class DfNet(nn.Module):
def forward
 # feat_spec = feat_spec.transpose(1, 4).squeeze(4)  # re/im into channel axis
 e0, e1, e2, e3, emb, c0, lsnr = self.enc(feat_erb, feat_spec)
m = self.erb_dec(emb, e3, e2, e1, e0)
spec = self.mask(spec, m, atten_lim)
        if self.run_df:
            df_coefs, df_alpha = self.df_dec(emb, c0)
            spec = self.df_op(spec, df_coefs, df_alpha)
            #spec是输入到dfilter的，df_op是real_unfold
        else:
            df_alpha = torch.zeros(spec.shape[0], spec.shape[2], 1, device=spec.device)

but it has errors :
  File "/home/dsp/LHN-GAG/DeepFilterNet-main/DeepFilterNet_code/df/deepfilternet.py", line 382, in forward
    df_coefs, df_alpha = self.df_dec(emb, c0)
  File "/home/dsp/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dsp/LHN-GAG/DeepFilterNet-main/DeepFilterNet_code/df/deepfilternet.py", line 272, in forward
    c = c.add(c0).view(b, t, self.df_order, 2, self.df_bins).transpose(3, 4)  # [B, T, O, F, 2]
RuntimeError: The size of tensor a (96) must match the size of tensor b (481) at non-singleton dimension 3

and I check the error in DfDecoder as follows,I print the size of c and c0,I find that they cannot  be computed  by add,
 # print(c.size(),c0.size())
 # torch.Size([7, 501, 10, 96]) torch.Size([7, 501, 10, 481])
is there some setting errors or input errors?

Thanks for your answering very much

class DfDecoder(nn.Module):
    def __init__(self):
        super().__init__()
        p = ModelParams()
        layer_width = p.conv_ch
        self.emb_dim = p.emb_hidden_dim

        self.df_n_hidden = p.df_hidden_dim
        self.df_n_layers = p.df_num_layers
        self.df_order = p.df_order
        self.df_bins = p.nb_df
        self.df_lookahead = p.df_lookahead
        self.gru_groups = p.gru_groups

        self.df_convp = convkxf(
            layer_width, self.df_order * 2, k=1, f=1, complex_in=True, batch_norm=True
        )
        self.df_gru = GroupedGRU(
            p.emb_hidden_dim,
            self.df_n_hidden,
            num_layers=self.df_n_layers,
            batch_first=False,
            groups=p.gru_groups,
            shuffle=p.group_shuffle,
            add_outputs=True,
        )
        self.df_fc_out = nn.Sequential(
            nn.Linear(self.df_n_hidden, self.df_bins * self.df_order * 2), nn.Tanh()
        )
        self.df_fc_a = nn.Sequential(nn.Linear(self.df_n_hidden, 1), nn.Sigmoid())

    def forward(self, emb: Tensor, c0: Tensor) -> Tuple[Tensor, Tensor]:
        b, t, _ = emb.shape
        c, _ = self.df_gru(emb.transpose(0, 1))  # [T, B, H], H: df_n_hidden
        c0 = self.df_convp(c0).transpose(1, 2)  # [B, T, O*2, F]
        c = c.transpose(0, 1)  # [B, T, H]
        alpha = self.df_fc_a(c)  # [B, T, 1]
        c = self.df_fc_out(c)  # [B, T, F*O*2], O: df_order
        c = c.view(b, t, self.df_order * 2, self.df_bins)  # [B, T, O*2, F]
        # print(c.size(),c0.size())
        # torch.Size([7, 501, 10, 96]) torch.Size([7, 501, 10, 481])
        c = c.add(c0).view(b, t, self.df_order, 2, self.df_bins).transpose(3, 4)  # [B, T, O, F, 2]
        return c, alpha

**Comment by Rikorose** [comment]
Please format your question and code correctly so I can netter understand what you are asking.

**Comment by Eie1** [comment]
Thanks for your answering ，my questions are as follows
1 in order to know the right input format of net，I input such follows，is it right?  

I find the input format in enc is erb: [B, 1, T, Fe]  ， spec: [B, 2, T, Fc]   ,so i  change code in dfnet by commenting out the first line feat_spec = feat_spec.transpose(1, 4).squeeze(4) # re/im into channel axis ,  I want  to  input data strightly into enc
e0, e1, e2, e3, emb, c0, lsnr = self.enc(feat_erb, feat_spec) ，so I input data  into as follows： 
test_spec=torch.randn(7,1, 501, 481, 2)
test_erb = torch.randn(7, 1, 501, 32)
test_feac= torch.randn(7, 2, 501, 481)
spec, m, lsnr, df_alpha = self.net(spec=test_spec,feat_erb=test_erb,feat_spec=test_feac)

the net is from model:deepfilter
model, epoch = load_model(
        # checkpoint_dir if args.resume else None,
        None,
        state,
        jit=False,
        mask_only=mask_only,
        train_df_only=train_df_only,
    )

2 after input as above，there is errors ，which are about code in df_dec---DfDecoder，the details are as follows:

File "/home/dsp/LHN-GAG/DeepFilterNet-main/DeepFilterNet_code/df/deepfilternet.py", line 382, in forward
df_coefs, df_alpha = self.df_dec(emb, c0)
File "/home/dsp/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
return forward_call(*input, **kwargs)
File "/home/dsp/LHN-GAG/DeepFilterNet-main/DeepFilterNet_code/df/deepfilternet.py", line 272, in forward
c = c.add(c0).view(b, t, self.df_order, 2, self.df_bins).transpose(3, 4) # [B, T, O, F, 2]
RuntimeError: The size of tensor a (96) must match the size of tensor b (481) at non-singleton dimension 3

because of the output errors， I check the error in DfDecoder as follows,I print the size of c and c0,and find that they cannot be computed by add, is there some setting error or input error？

Thanks for your answering very much
