### ISSUE TITLE
Can this be used from python?

### ISSUE THREAD

**Issue by skol101** [Rikorose/DeepFilterNet#181]
Or it could only be used from the command line?

**Comment by Rikorose** [comment]
Yes can be used from python as well

**Comment by skol101** [comment]
@Rikorose  Can you point to inference code, please?

**Comment by Rikorose** [comment]
https://github.com/Rikorose/DeepFilterNet/blob/main/DeepFilterNet/df/enhance.py

You could directly import `main()` but then you would need to manually construct the arguments object.

Or you can use `init_df` for initializing the module for STFT and feature computation and call `enhance()` on every audio file.
