### ISSUE TITLE
What does "Running without ERB stage" means?

### ISSUE THREAD

**Issue by bommyboy** [Rikorose/DeepFilterNet#188]
When I am running deepfilternet3 there is always a warning stating "Running without ERB stage" . Does this mean that the model only applies deep filtering to the input audio? If so, how do I enable running with ERB stage. Is there a settings to be changed in the config.ini file?

**Comment by Rikorose** [comment]
I guess you are using deep filtering for all frequency bins. Then you don't need the ERB stage.

**Comment by bommyboy** [comment]
Is that to say that when looking at the total parameters of the model using model_summary.py I can disregard the ERB parameters contribution since the model does not use it anyways. Thanks!

**Comment by Rikorose** [comment]
No the model architecture is slightly different from dfn2. In dfn3, the DF stage overwrites bins of the ERB stage. So running the ERB stage will only have effects for frequency bins that are not overwritten in the DF stage, i.e. if you only apply DF up to 4 kHz.
