### ISSUE TITLE
Questions about the latency

### ISSUE THREAD

**Issue by SiyuanWei** [Rikorose/DeepFilterNet#19]
Hi, amazing work first! But I've got some questions about the latency  described in  your paper as it says as the following table
![image](https://user-images.githubusercontent.com/20530918/143814489-d025f77e-6cca-4049-a8f2-d564c9191d6f.png)
How many frames (20ms for a stft window, 10ms for the hop size)is the  MACS  calculated under ?

**Comment by Rikorose** [comment]
Hi there, thanks for your interest in DeepFilterNet.

MACS are MAC per 1 second audio. Having a hop size of 10ms, we need 100 frames for a full second, and thus also 100 DNN iterations.

**Comment by SiyuanWei** [comment]
Got it , thanks!
