### ISSUE TITLE
Maybe some tiny bugs in augmentations.rs?

### ISSUE THREAD

**Issue by lhwcv** [Rikorose/DeepFilterNet#199]
Thanks for your great work first!
Some issue may need your guide.

issue1:

**self.equalize_rms is true,  may need  guarding against clipping also, otherwise  will produce clip noise when in clean speech**
maybe this is the reason why "The RandBiquadFilter was not contributing to a better noise reduction performance"? 

```
https://github.com/Rikorose/DeepFilterNet/blob/3b4a0e7f56b0776d0d12d4143779cfc13fd99e58/libDF/src/augmentations.rs#L362


if self.equalize_rms {
            let rms_new = x.map(|&x| x.powi(2)).mean().unwrap().sqrt();
            x.mapv_inplace(|x| x * rms / rms_new)
} else {
            // Guard against clipping
```

----

issue2:

Maybe Array::random((ch, sr), Normal::new(**0.**, 1.).unwrap()). here?

```
https://github.com/Rikorose/DeepFilterNet/blob/3b4a0e7f56b0776d0d12d4143779cfc13fd99e58/libDF/src/augmentations.rs#L660

// Fast path for white noise
Array::random((ch, sr), Normal::new(-1., 1.).unwrap())
```

**Comment by Rikorose** [comment]
Good catch, thanks!

**Comment by lhwcv** [comment]
Thanks for your quick reply， I learn a lot from you repo, and will keep on carefully review.

Issue3:

**May here use power(10,  v) ?**

https://github.com/Rikorose/DeepFilterNet/blob/87f761068cfda096209f9cf1c9e0ce9da5fd3bdb/libDF/src/augmentations.rs#L777

here is my naive python test code
``` python
import numpy as np

class RandReverbSim():
    def __init__(self):
        pass
    def supress_late(self, rir, rt60, offset=0, sr=16000):
        assert len(rir.shape) == 1
        len1 = rir.shape[0]
        if offset >= len1:
            return rir
        decay = np.ones(len1, np.float32)
        dt = 1.0 / sr
        rt60_level = 10** (-60 / 20)
        tau = - rt60 / np.log10(rt60_level)

        x = np.arange(0, len1 - offset, dtype=np.float32)

        x = np.power(10, -x * dt / tau)

        decay[offset: ] = decay[offset: ] * x
        rir = rir * decay

        # this is not correct
        # x = np.exp(-x * dt / tau)
        return rir, x


if __name__ == '__main__':

    sr = 16000
    app = RandReverbSim()
    rir = np.zeros(sr, dtype=np.float32)
    rt60 = 0.5

    _, y = app.supress_late(rir, rt60, sr=sr)

    ratio = y[int(sr * rt60)] / 1.0
    db = 20 * np.log10(ratio)

    # should be -60 db
    print('db: ', db)
```

**Comment by lhwcv** [comment]
@Rikorose 

Issue4:

**idx may always == len, no trim effect?**

https://github.com/Rikorose/DeepFilterNet/blob/87f761068cfda096209f9cf1c9e0ce9da5fd3bdb/libDF/src/augmentations.rs#L794

```rust
for (i, v) in rir_mono.slice(s![ref_idx..]).indexed_iter() {
            if v < &min_level {
                idx = i;
            } else {
                idx = len; // reset
            }
        }
```

**Comment by Rikorose** [comment]
> **May here use power(10, v) ?**

Why do you think, we need a power of 10 here? Do you have any reference?

**Comment by lhwcv** [comment]
> > **May here use power(10, v) ?**
> 
> Why do you think, we need a power of 10 here? Do you have any reference?

No reference, but the following `db` value should be -60?  according to your function hint, 
if use `exp`,  `db` will be -26,  which is not compatible with rt60 means.  
or I miss some keypoints?    I wonder if you can kindly provide some more guide.

```python
if __name__ == '__main__':

    sr = 16000
    app = RandReverbSim()
    rir = np.zeros(sr, dtype=np.float32)
    rt60 = 0.5

    _, y = app.supress_late(rir, rt60, sr=sr)

    ratio = y[int(sr * rt60)] / 1.0
    db = 20 * np.log10(ratio)

    # should be -60 db
    print('db: ', db)
```

**Comment by Rikorose** [comment]
True now I understand what you mean. Thanks.
