### ISSUE TITLE
Python ERB calculation

### ISSUE THREAD

**Issue by JBloodless** [Rikorose/DeepFilterNet#202]
Hi! In `modules.py` I found `test_erb` function, which I assume calculate ERB spectrum in python and compares it to rust function. I tried to apply same method in my pure-python version of code, but I'm getting some strange behavior.

1. Firstly I calculate normalized spectrum with torch.stft, which seems to be fine:
```
def analysis(audio, n_fft, hop):
    stft_norm = 1 / (n_fft ** 2 / (2 * hop))
    spec = torch.stft(
                audio, n_fft=n_fft, hop_length=hop, window=torch.hamming_window(window_length=n_fft),
                return_complex=True, normalized=False, center=False
            ).transpose(1, 2) * stft_norm
    return spec


spec = df.analysis(some_frame.numpy()) 
spec_ = analysis(some_frame, p.fft_size, p.hop_size)
fig, (ax1, ax2) = plt.subplots(1,2)
ax1.imshow(as_real(torch.as_tensor(spec[0, :, :32].T))[..., 0])  # lower spectrum part
ax2.imshow(as_real(spec_[0, :, :32].T)[..., 0])
plt.show()
```

![image](https://user-images.githubusercontent.com/8794436/205078847-16e4291a-376f-4eb6-848f-f53b3510ac9e.png)
(ignore empty part of the spectrum, this is due to specifics of my implementation)

Left is libdf.analysis version, right is python. Overall it seems to be fine.

2. The fun part. This is `erb` function with the help of `modules.test_erb`:

```
from modules import erb_fb

def erb(spec, erb_width, sr):
    erb_sp = erb_fb(erb_width, sr)
    input_abs = spec.abs().square()
    py_erb = torch.matmul(input_abs, erb_sp)
    return py_erb
```

I hardcoded `erb_width` as array for now, but I'm getting the same results with `df_state.erb_width()`

```
spec = analysis(some_frame, p.fft_size, p.hop_size)
df_erb = libdf.erb(spec.numpy(), erb_w)
py_erb = erb(spec, erb_w, p.sr)

fig, (ax1, ax2) = plt.subplots(1, 2)
ax1.imshow(torch.as_tensor(df_erb)[0])
ax2.imshow(py_erb[0])
plt.show()
```

![image](https://user-images.githubusercontent.com/8794436/205080262-d97b5975-78a3-451a-ac36-7aa456f267fb.png)
Again left is libdf version, right is python. There is a huge mismatch in energies, although overall distribution over bins seems to be similar. 

last row from libdf version:
```
[ -46.818428  -36.29398   -42.827415  -39.460117  -47.795444
    -33.985874  -39.07429   -35.439228  -45.613815  -48.311012
    -53.875885  -51.044773  -55.07961   -56.251644  -56.49228
    -48.650555  -50.076977  -53.96145   -52.574924  -62.372894
    -55.0551    -62.427464  -70.88772   -73.882195  -74.01714
    -77.18188   -69.51404   -77.30788   -77.70049   -92.85287
    -98.88032   -99.99631 ]
```
from py_erb:
```
[9.9474e-06, 1.8777e-04, 4.8145e-05, 9.4821e-05, 1.0363e-05,
          3.1055e-04, 8.7718e-05, 2.3666e-04, 1.8138e-05, 1.1224e-05,
          2.9927e-06, 5.7629e-06, 2.1937e-06, 1.8403e-06, 1.7932e-06,
          1.0877e-05, 7.4944e-06, 3.0450e-06, 4.6106e-06, 4.9861e-07,
          2.4991e-06, 4.3865e-07, 6.7705e-08, 3.3798e-08, 3.0448e-08,
          1.4492e-08, 8.8700e-08, 1.4841e-08, 1.3404e-08, 3.4958e-10,
          2.9207e-11, 4.9885e-12]
```

If i plot the results of test_erb(), they look right:

```
# snippet from test_erb()
df_erb = torch.from_numpy(libdf.erb(input.numpy(), erb_widths, False))
py_erb = torch.matmul(input_abs, erb)
fig, (ax1, ax2) = plt.subplots(1, 2)
ax1.imshow(torch.as_tensor(df_erb)[0][0])
ax2.imshow(py_erb[0][0])
plt.show()
```

![image](https://user-images.githubusercontent.com/8794436/205080707-63196889-f59d-4b30-8f8e-d28e66bfa63b.png)

Because of this mismatch, following normalization fails, and the input features are completely wrong.

Can you maybe give me a hint, what am I missing in test_erb()? Why seemingly the same code in my version gives such mismatch?

Appreciate the help.

**Comment by JBloodless** [comment]
P.S. I tried to pass `df.analysis `spectrum to this ERB implementation - result is the same, so it's definitely problem in ERB calculation on my side

**Comment by Rikorose** [comment]
Did you do scaling do decibel?

**Comment by JBloodless** [comment]
Probably not, I basically did what test_erb() do. Where should I apply it?

**Comment by Rikorose** [comment]
Here is the rust function: https://github.com/Rikorose/DeepFilterNet/blob/main/libDF/src/transforms.rs#L214

**Comment by JBloodless** [comment]
I thought that db=None by default, because in python-compiled code
```
def erb(
    input: ndarray, erb_fb: Union[ndarray, List[int]], db: Optional[bool] = None
) -> ndarray: ...
```

**Comment by Rikorose** [comment]
That is indeed an error on the documentation side.

**Comment by JBloodless** [comment]
Okay, I applied logarithmic conversion and it seems to be similar now, big thanks!
