### ISSUE TITLE
train.py returns error: DF Dataset Error

### ISSUE THREAD

**Issue by Penguin168** [Rikorose/DeepFilterNet#215]
Thanks for your awesome work.
I have encountered some problems while run `train.py`, I followed your steps to build environment, and I am using ubuntu in VMware as my workspace, could you tell me how can I solve the problem?

When I use command `python df/train.py path/to/dataset.cfg path/to/data_dir/ path/to/base_dir/` (of course I changed the directory), it gives an error:
```
(.venv) jeffery@dooog:~/Desktop/DFNmain/DeepFilterNet$ python df/train.py dataset.cfg data_hdf5/ base/
2022-12-19 14:06:51 | INFO     | DF | Running on torch 1.13.1+cpu
2022-12-19 14:06:52 | INFO     | DF | Running on host dooog
fatal: not a git repository (or any of the parent directories): .git
2022-12-19 14:06:52 | INFO     | DF | Loading model settings of base
2022-12-19 14:06:52 | INFO     | DF | Running on device cpu
2022-12-19 14:06:52 | INFO     | DF | Initializing model `deepfilternet3`
2022-12-19 14:06:52 | INFO     | DF | Initializing dataloader with data directory data_hdf5/
2022-12-19 14:06:53 | WARNING  | DF | Reverb augmentation enabled but no RIRs provided!
2022-12-19 14:06:53 | WARNING  | DF | Reverb augmentation enabled but no RIRs provided!
2022-12-19 14:06:53 | WARNING  | DF | Reverb augmentation enabled but no RIRs provided!
2022-12-19 14:06:53 | INFO     | DF | Start train epoch 0 with batch size 1
2022-12-19 14:06:53 | ERROR    | DF | An error has been caught in function '<module>', process 'MainProcess' (77712), thread 'MainThread' (140326036959680):
Traceback (most recent call last):

> File "/home/jeffery/Desktop/DFNmain/DeepFilterNet/df/train.py", line 635, in <module>
    main()
    └ <function main at 0x7fa00ea71090>

  File "/home/jeffery/Desktop/DFNmain/DeepFilterNet/df/train.py", line 245, in main
    train_loss = run_epoch(
                 └ <function run_epoch at 0x7fa00ea72050>

  File "/home/jeffery/Desktop/DFNmain/DeepFilterNet/df/train.py", line 352, in run_epoch
    for i, batch in enumerate(loader.iter_epoch(split, seed)):
                              │      │          │      └ 0
                              │      │          └ 'train'
                              │      └ <function PytorchDataLoader.iter_epoch at 0x7fa00ea71e10>
                              └ <libdfdata.torch_dataloader.PytorchDataLoader object at 0x7fa00dd842e0>

  File "/home/jeffery/Desktop/DFNmain/pyDF-data/libdfdata/torch_dataloader.py", line 264, in iter_epoch
    self.loader.start_epoch(split, seed)
    │    │      │           │      └ 0
    │    │      │           └ 'train'
    │    │      └ <method 'start_epoch' of 'builtins._FdDataLoader' objects>
    │    └ <builtins._FdDataLoader object at 0x7fa00ecf3b80>
    └ <libdfdata.torch_dataloader.PytorchDataLoader object at 0x7fa00dd842e0>

ValueError: DF Dataset Error
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libDF/src/dataloader.rs:540:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exception ignored in tp_clear of: <class 'libdfdata.torch_dataloader.PytorchDataLoader'>
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
```
And I'm pretty sure that there are RIR datasets in the folder.
Here is my step to build the environment in clean virtualenv, could you please tell me what step am I wrong or what step I missed?

`sudo apt install cmake`
`sudo apt-get install git`
`sudo apt  install curl`
`sudo apt-get install libhdf5-serial-dev`
`cd DeepFilterNet_main`
`virtualenv .venv`
`source .venv/bin/activate`
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`     Install cargo via rustup
`pip install h5py `
`pip install patchelf`
`pip install torch torchaudio -f https://download.pytorch.org/whl/cpu/torch_stable.html`
`pip install maturin poetry`
`maturin develop --release -m pyDF/Cargo.toml`
`maturin develop --release -m pyDF-data/Cargo.toml`
`maturin develop --release --features hdf5-static -m pyDF-data/Cargo.toml`
`cd DeepFilterNet`
`poetry install -E train -E eval  `
⇧⇧ this command return the error then break:  
```
Package operations: 18 installs, 4 updates, 3 removals

  • Removing cffi (1.15.1)
  • Removing packaging (22.0)
  • Removing pycparser (2.21)
  • Updating numpy (1.24.0 -> 1.23.5): Failed

  CalledProcessError

  Command '['/home/jeffery/Desktop/DFNmain/.venv/bin/python', '-I', '-W', 'ignore', '-']' returned non-zero exit status 1.

  at /usr/lib/python3.10/subprocess.py:524 in run
       520│             # We don't call process.wait() as .__exit__ does that for us.
       521│             raise
       522│         retcode = process.poll()
       523│         if check and retcode:
    →  524│             raise CalledProcessError(retcode, process.args,
       525│                                      output=stdout, stderr=stderr)
       526│     return CompletedProcess(process.args, retcode, stdout, stderr)
       527│ 
       528│ 

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/home/jeffery/Desktop/DFNmain/.venv/bin/python', '-I', '-W', 'ignore', '-'] errored with the following return code 1, and output: 
  Traceback (most recent call last):
    File "<stdin>", line 18, in <module>
    File "<frozen importlib._bootstrap_external>", line 879, in exec_module
    File "<frozen importlib._bootstrap_external>", line 1016, in get_code
    File "<frozen importlib._bootstrap_external>", line 1073, in get_data
  FileNotFoundError: [Errno 2] No such file or directory: '/home/jeffery/Desktop/DFNmain/.venv/lib/python3.10/site-packages/packaging/tags.py'
  input was : 
  import importlib.util
  import json
  import sys
  
  from pathlib import Path
  
  spec = importlib.util.spec_from_file_location(
      "packaging", Path(r"/home/jeffery/Desktop/DFNmain/.venv/lib/python3.10/site-packages/packaging/__init__.py")
  )
  packaging = importlib.util.module_from_spec(spec)
  sys.modules[spec.name] = packaging
  
  spec = importlib.util.spec_from_file_location(
      "packaging.tags", Path(r"/home/jeffery/Desktop/DFNmain/.venv/lib/python3.10/site-packages/packaging/tags.py")
  )
  packaging_tags = importlib.util.module_from_spec(spec)
  spec.loader.exec_module(packaging_tags)
  
  print(
      json.dumps([(t.interpreter, t.abi, t.platform) for t in packaging_tags.sys_tags()])
  )
  

  at ~/Desktop/DFNmain/.venv/lib/python3.10/site-packages/poetry/utils/env.py:1540 in _run
      1536│                 output = subprocess.check_output(
      1537│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1538│                 )
      1539│         except CalledProcessError as e:
    → 1540│             raise EnvCommandError(e, input=input_)
      1541│ 
      1542│         return decode(output)
      1543│ 
      1544│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:
```
`export PYTHONPATH=$PWD`
`pip install loguru`
`pip install icecream`
`python DeepFilterNet/df/enhance.py -m DeepFilterNet2 path/to/noisy_audio.wav`   this command can run successfully

Both version of rusrc and cargo are 1.66.0, use command `rustc -V`, `cargo -V`

Thanks for helping very much!

**Comment by Rikorose** [comment]
The first error is very strange. Please update to latest main (and recompile pydf-data) and run again with `--debug`.

Not sure what the second error is:
```
  FileNotFoundError: [Errno 2] No such file or directory: '/home/jeffery/Desktop/DFNmain/.venv/lib/python3.10/site-packages/packaging/tags.py'
```
There seems something wrong with your env.

**Comment by Penguin168** [comment]
Could you tell me how to recompile pydf-data? I'm not sure how to do it, Is use command `maturin develop --release -m pyDF-data/Cargo.toml`?

**Comment by Penguin168** [comment]
I create a new environment of latest main, recompile pydf-data with command `maturin develop --release -m pyDF-data/Cargo.toml`, and run again with python df/train.py --debug  dataset.cfg data_hdf5 base, then it gives the detail error.

Because the virtual hard disk isn't big enough, I just use 2000 RIR samples, and split to 1400, 300, 300.

```
(.venv) jeffery@dooog:~/Desktop/DFNmain/DeepFilterNet$ python df/train.py --debug  dataset.cfg data_hdf5 base
2022-12-19 18:22:12 | INFO     | df.logger:init_logger:44 | Running on torch 1.13.1+cpu
2022-12-19 18:22:12 | INFO     | df.logger:init_logger:45 | Running on host dooog
fatal: not a git repository (or any of the parent directories): .git
2022-12-19 18:22:12 | INFO     | df.logger:init_logger:67 | Loading model settings of base
2022-12-19 18:22:12 | INFO     | __main__:main:94 | Running on device cpu
2022-12-19 18:22:12 | INFO     | df.model:init_model:21 | Initializing model `deepfilternet3`
2022-12-19 18:22:12 | INFO     | libdfdata.torch_dataloader:__init__:100 | Initializing dataloader with data directory data_hdf5
2022-12-19 18:22:12 | INFO     | libdfdata.torch_dataloader:df:hdf5_key_cache:20 | Loading HDF5 key cache from .cache_dataset.cfg
2022-12-19 18:22:12 | DEBUG    | libdfdata.torch_dataloader:df:dataset:601 | Opened Speech test dataset data_hdf5/TEST_SET_NOISE.hdf5 with 1858 samples
2022-12-19 18:22:12 | DEBUG    | libdfdata.torch_dataloader:df:dataset:601 | Opened Speech test dataset data_hdf5/TEST_SET_SPEECH.hdf5 with 1858 samples
2022-12-19 18:22:12 | DEBUG    | libdfdata.torch_dataloader:df:dataset:601 | Opened Speech test dataset data_hdf5/TEST_SET_RIR.hdf5 with 300 samples
2022-12-19 18:22:12 | WARNING  | libdfdata.torch_dataloader:df:dataset:686 | Reverb augmentation enabled but no RIRs provided!
2022-12-19 18:22:12 | DEBUG    | libdfdata.torch_dataloader:df:dataset:601 | Opened Speech valid dataset data_hdf5/VALID_SET_SPEECH.hdf5 with 1858 samples
2022-12-19 18:22:12 | DEBUG    | libdfdata.torch_dataloader:df:dataset:601 | Opened Speech valid dataset data_hdf5/VALID_SET_RIR.hdf5 with 300 samples
2022-12-19 18:22:12 | DEBUG    | libdfdata.torch_dataloader:df:dataset:601 | Opened Speech valid dataset data_hdf5/VALID_SET_NOISE.hdf5 with 1858 samples
2022-12-19 18:22:12 | WARNING  | libdfdata.torch_dataloader:df:dataset:686 | Reverb augmentation enabled but no RIRs provided!
2022-12-19 18:22:12 | DEBUG    | libdfdata.torch_dataloader:df:dataset:601 | Opened Speech train dataset data_hdf5/TRAIN_SET_NOISE.hdf5 with 8680 samples
2022-12-19 18:22:12 | DEBUG    | libdfdata.torch_dataloader:df:dataset:601 | Opened Speech train dataset data_hdf5/TRAIN_SET_RIR.hdf5 with 1400 samples
2022-12-19 18:22:12 | DEBUG    | libdfdata.torch_dataloader:df:dataset:601 | Opened Speech train dataset data_hdf5/TRAIN_SET_SPEECH.hdf5 with 8680 samples
2022-12-19 18:22:12 | WARNING  | libdfdata.torch_dataloader:df:dataset:686 | Reverb augmentation enabled but no RIRs provided!
2022-12-19 18:22:12 | DEBUG    | __main__:load_opt:514 | Training with optimizer AdamW (
Parameter Group 0
    amsgrad: True
    betas: [0.9, 0.999]
    capturable: False
    eps: 1e-08
    foreach: None
    lr: 0.0005
    maximize: False
    weight_decay: 0.05
)
2022-12-19 18:22:12 | DEBUG    | df.logger:log_model_summary:178 | Failed to import ptflops. Cannot print model summary.
2022-12-19 18:22:12 | DEBUG    | df.config:save:77 | Config not modified. No need to overwrite on disk.
2022-12-19 18:22:12 | INFO     | __main__:run_epoch:337 | Start train epoch 0 with batch size 1
2022-12-19 18:22:12 | ERROR    | __main__:<module>:635 | An error has been caught in function '<module>', process 'MainProcess' (79883), thread 'MainThread' (139966511948224):
Traceback (most recent call last):

> File "/home/jeffery/Desktop/DFNmain/DeepFilterNet/df/train.py", line 635, in <module>
    main()
    └ <function main at 0x7f4c59515090>

  File "/home/jeffery/Desktop/DFNmain/DeepFilterNet/df/train.py", line 245, in main
    train_loss = run_epoch(
                 └ <function run_epoch at 0x7f4c59516050>

  File "/home/jeffery/Desktop/DFNmain/DeepFilterNet/df/train.py", line 352, in run_epoch
    for i, batch in enumerate(loader.iter_epoch(split, seed)):
                              │      │          │      └ 0
                              │      │          └ 'train'
                              │      └ <function PytorchDataLoader.iter_epoch at 0x7f4c59515e10>
                              └ <libdfdata.torch_dataloader.PytorchDataLoader object at 0x7f4c581bfeb0>

  File "/home/jeffery/Desktop/DFNmain/pyDF-data/libdfdata/torch_dataloader.py", line 264, in iter_epoch
    self.loader.start_epoch(split, seed)
    │    │      │           │      └ 0
    │    │      │           └ 'train'
    │    │      └ <method 'start_epoch' of 'builtins._FdDataLoader' objects>
    │    └ <builtins._FdDataLoader object at 0x7f4c597c7910>
    └ <libdfdata.torch_dataloader.PytorchDataLoader object at 0x7f4c581bfeb0>

ValueError: DF Dataset Error
thread '<unnamed>' panicked at 'No train dataset found. Could not stop dataloader worker.', libDF/src/dataloader.rs:546:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exception ignored in tp_clear of: <class 'libdfdata.torch_dataloader.PytorchDataLoader'>
pyo3_runtime.PanicException: No train dataset found. Could not stop dataloader worker.

```

**Comment by Rikorose** [comment]
> 2022-12-19 18:22:12 | DEBUG    | libdfdata.torch_dataloader:df:dataset:601 | Opened Speech train dataset data_hdf5/TRAIN_SET_NOISE.hdf5 with 8680 samples

> pyo3_runtime.PanicException: No train dataset found. Could not stop dataloader worker.

**Comment by Rikorose** [comment]
I improved the error message in b2fcb65

**Comment by Rikorose** [comment]
BTW this is also wrong:
> 2022-12-19 18:22:12 | DEBUG    | libdfdata.torch_dataloader:df:dataset:601 | Opened Speech train dataset data_hdf5/TRAIN_SET_RIR.hdf5 with 1400 samples

**Comment by ZihanLiao** [comment]
> Thanks for your awesome work. I have encountered some problems while run `train.py`, I followed your steps to build environment, and I am using ubuntu in VMware as my workspace, could you tell me how can I solve the problem?
> 
> When I use command `python df/train.py path/to/dataset.cfg path/to/data_dir/ path/to/base_dir/` (of course I changed the directory), it gives an error:
> 
> ```
> (.venv) jeffery@dooog:~/Desktop/DFNmain/DeepFilterNet$ python df/train.py dataset.cfg data_hdf5/ base/
> 2022-12-19 14:06:51 | INFO     | DF | Running on torch 1.13.1+cpu
> 2022-12-19 14:06:52 | INFO     | DF | Running on host dooog
> fatal: not a git repository (or any of the parent directories): .git
> 2022-12-19 14:06:52 | INFO     | DF | Loading model settings of base
> 2022-12-19 14:06:52 | INFO     | DF | Running on device cpu
> 2022-12-19 14:06:52 | INFO     | DF | Initializing model `deepfilternet3`
> 2022-12-19 14:06:52 | INFO     | DF | Initializing dataloader with data directory data_hdf5/
> 2022-12-19 14:06:53 | WARNING  | DF | Reverb augmentation enabled but no RIRs provided!
> 2022-12-19 14:06:53 | WARNING  | DF | Reverb augmentation enabled but no RIRs provided!
> 2022-12-19 14:06:53 | WARNING  | DF | Reverb augmentation enabled but no RIRs provided!
> 2022-12-19 14:06:53 | INFO     | DF | Start train epoch 0 with batch size 1
> 2022-12-19 14:06:53 | ERROR    | DF | An error has been caught in function '<module>', process 'MainProcess' (77712), thread 'MainThread' (140326036959680):
> Traceback (most recent call last):
> 
> > File "/home/jeffery/Desktop/DFNmain/DeepFilterNet/df/train.py", line 635, in <module>
>     main()
>     └ <function main at 0x7fa00ea71090>
> 
>   File "/home/jeffery/Desktop/DFNmain/DeepFilterNet/df/train.py", line 245, in main
>     train_loss = run_epoch(
>                  └ <function run_epoch at 0x7fa00ea72050>
> 
>   File "/home/jeffery/Desktop/DFNmain/DeepFilterNet/df/train.py", line 352, in run_epoch
>     for i, batch in enumerate(loader.iter_epoch(split, seed)):
>                               │      │          │      └ 0
>                               │      │          └ 'train'
>                               │      └ <function PytorchDataLoader.iter_epoch at 0x7fa00ea71e10>
>                               └ <libdfdata.torch_dataloader.PytorchDataLoader object at 0x7fa00dd842e0>
> 
>   File "/home/jeffery/Desktop/DFNmain/pyDF-data/libdfdata/torch_dataloader.py", line 264, in iter_epoch
>     self.loader.start_epoch(split, seed)
>     │    │      │           │      └ 0
>     │    │      │           └ 'train'
>     │    │      └ <method 'start_epoch' of 'builtins._FdDataLoader' objects>
>     │    └ <builtins._FdDataLoader object at 0x7fa00ecf3b80>
>     └ <libdfdata.torch_dataloader.PytorchDataLoader object at 0x7fa00dd842e0>
> 
> ValueError: DF Dataset Error
> thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libDF/src/dataloader.rs:540:17
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Exception ignored in tp_clear of: <class 'libdfdata.torch_dataloader.PytorchDataLoader'>
> pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value
> ```
> 
> And I'm pretty sure that there are RIR datasets in the folder. Here is my step to build the environment in clean virtualenv, could you please tell me what step am I wrong or what step I missed?
> 
> `sudo apt install cmake` `sudo apt-get install git` `sudo apt install curl` `sudo apt-get install libhdf5-serial-dev` `cd DeepFilterNet_main` `virtualenv .venv` `source .venv/bin/activate` `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` Install cargo via rustup `pip install h5py ` `pip install patchelf` `pip install torch torchaudio -f https://download.pytorch.org/whl/cpu/torch_stable.html` `pip install maturin poetry` `maturin develop --release -m pyDF/Cargo.toml` `maturin develop --release -m pyDF-data/Cargo.toml` `maturin develop --release --features hdf5-static -m pyDF-data/Cargo.toml` `cd DeepFilterNet` `poetry install -E train -E eval ` ⇧⇧ this command return the error then break:
> 
> ```
> Package operations: 18 installs, 4 updates, 3 removals
> 
>   • Removing cffi (1.15.1)
>   • Removing packaging (22.0)
>   • Removing pycparser (2.21)
>   • Updating numpy (1.24.0 -> 1.23.5): Failed
> 
>   CalledProcessError
> 
>   Command '['/home/jeffery/Desktop/DFNmain/.venv/bin/python', '-I', '-W', 'ignore', '-']' returned non-zero exit status 1.
> 
>   at /usr/lib/python3.10/subprocess.py:524 in run
>        520│             # We don't call process.wait() as .__exit__ does that for us.
>        521│             raise
>        522│         retcode = process.poll()
>        523│         if check and retcode:
>     →  524│             raise CalledProcessError(retcode, process.args,
>        525│                                      output=stdout, stderr=stderr)
>        526│     return CompletedProcess(process.args, retcode, stdout, stderr)
>        527│ 
>        528│ 
> 
> The following error occurred when trying to handle this error:
> 
> 
>   EnvCommandError
> 
>   Command ['/home/jeffery/Desktop/DFNmain/.venv/bin/python', '-I', '-W', 'ignore', '-'] errored with the following return code 1, and output: 
>   Traceback (most recent call last):
>     File "<stdin>", line 18, in <module>
>     File "<frozen importlib._bootstrap_external>", line 879, in exec_module
>     File "<frozen importlib._bootstrap_external>", line 1016, in get_code
>     File "<frozen importlib._bootstrap_external>", line 1073, in get_data
>   FileNotFoundError: [Errno 2] No such file or directory: '/home/jeffery/Desktop/DFNmain/.venv/lib/python3.10/site-packages/packaging/tags.py'
>   input was : 
>   import importlib.util
>   import json
>   import sys
>   
>   from pathlib import Path
>   
>   spec = importlib.util.spec_from_file_location(
>       "packaging", Path(r"/home/jeffery/Desktop/DFNmain/.venv/lib/python3.10/site-packages/packaging/__init__.py")
>   )
>   packaging = importlib.util.module_from_spec(spec)
>   sys.modules[spec.name] = packaging
>   
>   spec = importlib.util.spec_from_file_location(
>       "packaging.tags", Path(r"/home/jeffery/Desktop/DFNmain/.venv/lib/python3.10/site-packages/packaging/tags.py")
>   )
>   packaging_tags = importlib.util.module_from_spec(spec)
>   spec.loader.exec_module(packaging_tags)
>   
>   print(
>       json.dumps([(t.interpreter, t.abi, t.platform) for t in packaging_tags.sys_tags()])
>   )
>   
> 
>   at ~/Desktop/DFNmain/.venv/lib/python3.10/site-packages/poetry/utils/env.py:1540 in _run
>       1536│                 output = subprocess.check_output(
>       1537│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
>       1538│                 )
>       1539│         except CalledProcessError as e:
>     → 1540│             raise EnvCommandError(e, input=input_)
>       1541│ 
>       1542│         return decode(output)
>       1543│ 
>       1544│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:
> ```
> 
> `export PYTHONPATH=$PWD` `pip install loguru` `pip install icecream` `python DeepFilterNet/df/enhance.py -m DeepFilterNet2 path/to/noisy_audio.wav` this command can run successfully
> 
> Both version of rusrc and cargo are 1.66.0, use command `rustc -V`, `cargo -V`
> 
> Thanks for helping very much!

I'm facing the same problem as your second one. I think the reason is that the poetry removed the packaging first, then the following scripts cannot find the target file. Still don't know how to solve it, guess some changes in the poetry.lock ??
