### ISSUE TITLE
Multithread ?

### ISSUE THREAD

**Issue by jenskastensson** [Rikorose/DeepFilterNet#218]
Hi and thanks for a amazing work !
I tested the ladspa filter on a Allwinner H3 (ARM Cortex-A7 Quad-Core 1.296 GHz) , it was easy to install; great work
The filter seems to be single-threaded, a single core seems not be enough to process. Would it be possible to involve the other cores ?

```
2022-12-22T16:33:37.579Z | WARN |  deep_filter_ladspa | DF 7b7326a9e80d | Underrun detected (RTF: 2.39). Processing too slow!
overrun!!! (at least 277.761 ms long)
2022-12-22T16:33:38.903Z | WARN |  deep_filter_ladspa | DF 3bfb6693797b | Underrun detected (RTF: 2.48). Processing too slow!
overrun!!! (at least 312.537 ms long)
2022-12-22T16:33:40.179Z | WARN |  deep_filter_ladspa | DF 9f61b96d4beb | Underrun detected (RTF: 2.36). Processing too slow!
overrun!!! (at least 266.241 ms long)
2022-12-22T16:33:41.476Z | WARN |  deep_filter_ladspa | DF 54a1822b409f | Underrun detected (RTF: 2.41). Processing too slow!
overrun!!! (at least 284.917 ms long)
```

**Comment by Rikorose** [comment]
Not with the current DNN framework. One option could be #210, but this will only bring approx 30% improvement.

**Comment by jenskastensson** [comment]
Thank you Hendrik for the reply, let's hope the 30% improvement is enough. Having tested the stand alone application on a different device I must say  the results are really amazing, kudos to you and the team !

**Question**: would it make any difference (in regards of CPU), if the required performance of of the filter is reduced / less ambitious ?
 (I know it is a long shot but wanted to ask anyway)

**Comment by UnlimitedCookies** [comment]
:(
Multi-threading could be a real improvement.

**Comment by arrio464** [comment]
It seems that your CPU is quite slow(same on my 2GHz Cortex-A72).
As a workaround, I specified to use `DeepFilterNet3_onnx` model instead of `DeepFilterNet3_ll_onnx` model, sacrificing some "low latency" to reduce CPU useage.
In my cases, it only took about ~50% of Cortex-A72 cpu time, which is equivalent to a 1GHz CPU frequency.
