### ISSUE TITLE
Questions about _fdataloader

### ISSUE THREAD

**Issue by vjrmjf** [Rikorose/DeepFilterNet#229]
Hi. Thank you for your code.
now，i want to view _FdDataLoader in linux to find how to deal with the data ,but i don't know how to do it。
The content of the _FdDataLoader function seems to be in libdf.cpython-38-x86_64-linux-gnu.so, if I want to modify or view this part of the content, what should I do, 
Thanks for helping very much

**Comment by Rikorose** [comment]
Most of the dataloader code is in [dataloader.rs](https://github.com/Rikorose/DeepFilterNet/blob/main/libDF/src/dataloader.rs) and [dataset.rs](https://github.com/Rikorose/DeepFilterNet/blob/main/libDF/src/dataset.rs). The python wrapper around this rust code is in pyDF-data.
