### ISSUE TITLE
Model training hangs during validation

### ISSUE THREAD

**Issue by tyrius02** [Rikorose/DeepFilterNet#236]
On some of the systems where we've been training the DFN2 (low-latency) model the training loop hangs during validation. The only thing I can do at that point is to kill and re-start training. Unfortunately the specific epoch where the hang occurs isn't consistent.

Here's the last pieces from the console where this occurred. I started the training before leaving for the night and, as you can see, training stopped progressing eleven hours before I returned to the task.

> **2023-01-18 07:31:19 | INFO     | DF | Start valid epoch 42 with batch size 192**
> ^CTraceback (most recent call last):
>   File "/home/jovyan/work/DeepFilterNet/train.py", line 735, in <module>
>     main()
>   File "/usr/local/lib/python3.10/dist-packages/loguru/_logger.py", line 1226, in catch_wrapper
>     return function(*args, **kwargs)
>   File "/home/jovyan/work/DeepFilterNet/train.py", line 356, in main
>     val_loss = run_epoch(
>   File "/home/jovyan/work/DeepFilterNet/train.py", line 443, in run_epoch
>     for i, batch in enumerate(loader.iter_epoch(split, seed)):
>   File "/usr/local/lib/python3.10/dist-packages/libdfdata/torch_dataloader.py", line 255, in iter_epoch
>     self.setup_data_queue()
>   File "/usr/local/lib/python3.10/dist-packages/libdfdata/torch_dataloader.py", line 165, in setup_data_queue
>     self.cleanup_pin_memory_thread()
>   File "/usr/local/lib/python3.10/dist-packages/libdfdata/torch_dataloader.py", line 160, in cleanup_pin_memory_thread
>     self.data_queue.join()
>   File "/usr/lib/python3.10/queue.py", line 90, in join
>     self.all_tasks_done.wait()
>   File "/usr/lib/python3.10/threading.py", line 320, in wait
>     waiter.acquire()
> KeyboardInterrupt
> 
> jovyan@f885bc70c8b5:~/work/DeepFilterNet$ date
> **Wed Jan 18 18:31:39 UTC 2023**

Any thoughts on what could be causing the problem?

**Comment by Rikorose** [comment]
I also rarely observe this, but don't know where/why this happens.

**Comment by tyrius02** [comment]
I wonder if it is related to https://github.com/pytorch/pytorch/issues/24927? That issue was supposedly fixed but people continue to report the problem.
The stack traces shared in that issue look very similar to what I'm seeing.

**Comment by tyrius02** [comment]
Is it possible to use a multiprocessing.JoinableQueue rather than a queue.Queue? Lock state is inherited in forked processes and it is possible that the queue lock is being held and then passed to a worker process. At least, that's the gist of the PyTorch issue.

[Multiprocessing pipes and queues](https://docs.python.org/3/library/multiprocessing.html#pipes-and-queues)

**Comment by tyrius02** [comment]
After a little more digging I _think_ the problem has to do with how Python's Queue manages tasks. Every call to `Queue.put()` increments an internal task counter. Every call to `Queue.get()` will fetch an item but leave the task counter unchanged. `Queue.join()` will block until the internal task counter reaches zero.

Inside `PytorchDataLoader` there are two calls to `Queue.get()`. One at [line 233](https://github.com/Rikorose/DeepFilterNet/blob/1627c6e1aa5249edd96fc4187c854e2c11262e6f/pyDF-data/libdfdata/torch_dataloader.py#L233) and the other at [line 161](https://github.com/Rikorose/DeepFilterNet/blob/1627c6e1aa5249edd96fc4187c854e2c11262e6f/pyDF-data/libdfdata/torch_dataloader.py#L161).
The fact that the hang occurs intermittently tells me there's a race condition, which I think is at [line 157](https://github.com/Rikorose/DeepFilterNet/blob/1627c6e1aa5249edd96fc4187c854e2c11262e6f/pyDF-data/libdfdata/torch_dataloader.py#L157). Only if the pin_memory thread is still alive you drain the queue (don't decrement the internal task counter) and then attempt to join the queue.

I've made a couple of changes to `PytorchDataLoader` to decrement the internal task counter after each `Queue.get()`:
```
self.data_queue.get()  
if hasattr(self.data_queue, "task_done"):
    self.data_queue.task_done()
```

I'll test these changes out and see if it resolves the issue.  Reproducing is a little challenging because the pin_memory thread must still be alive for the problem to even manifest itself.

**Comment by Rikorose** [comment]
Thanks for your investigations. If you are successful I am looking forward to a PR.

**Comment by tyrius02** [comment]
Seems to have done the trick. This is the first time I've actually seen the "Pinmemory cleanup done" message in the training log.
