### ISSUE TITLE
ModuleNotFoundError: No module named 'libdfdata'

### ISSUE THREAD

**Issue by rohithmars** [Rikorose/DeepFilterNet#24]
Hello,

When I try to run the df/train.py file, I get ModuleNotFoundError: No module named 'libdfdata' error. I understand the libdfdata is found in pyDF-data folder. 

Is it possible to fix this or is there any modification required from my side?

**Comment by Rikorose** [comment]
Hi there,

you can compile these modules using the instructions in the readme.
You can also only install data loader and libdf from pypi without the DeepFilterNet module when you work within this repo:
https://pypi.org/project/deepfilterdataloader/
https://pypi.org/project/deepfilterlib/

**Comment by rohithmars** [comment]
thanks for the quick reply. 

The issue was fixed after using the installing the modules through pypi.

**Comment by Rikorose** [comment]
Thanks for reporting back. I will try to clarify the installation procedure for training in the readme.
