### ISSUE TITLE
Using Deepfilternet within another Python script

### ISSUE THREAD

**Issue by cweaver-logitech** [Rikorose/DeepFilterNet#247]
Firstly, this is a great piece of work. I've tested it against commercial denoising solutions (such as Waves Clarity and RX Audio) for speech and it scores equally well in my listening tests.

<p style="outline: none !important; margin: 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><b style="outline: none !important;">DNSMOS Scores:</b></p><div class="table-wrap" style="outline: none !important; margin: 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

  | OVRL_raw | SIG_raw | BAK_raw | OVRL | SIG | BAK
-- | -- | -- | -- | -- | -- | --
Cleaning pipeline | 3.55 | 3.88 | 4.16 | 3.17 | 3.47 | 4
Izotope RX 10 | 3.56 | 3.85 | 4.12 | 3.14 | 3.45 | 3.98
Waves Clarity | 3.59 | 3.84 | 3.96 | 3.11 | 3.45 | 3.9
DeepfilterNet2 | 3.58 | 3.83 | 4.24 | 3.17 | 3.44 | 4.05
Voicefixer | 3.35 | 3.82 | 4.19 | 3.15 | 3.44 | 4.03
  |   |   |   |   |   |  
Raw | 3.49 | 3.6 | 4.11 | 3.01 | 3.3 | 3.98

</div>

As per the subject heading, I would like to use Deepfilternet in some speech cleaning scripts but cannot figure out (from the Pip package) how to access the enhance function directly.

Doing `import deepfilter_python` results in a circular import. 

Any help would be appreciated.

**Comment by Rikorose** [comment]
Not sure what you are importing. You should rather use `import df`. I added an example here: #248

**Comment by cweaver-logitech** [comment]
Thank so much for the prompt response. You were quite correct. `Import df` solves the issue. I guess I wasn't quite sure of the module name (I had assumed it was the same as the Pip package)

I hope you don't mind another question. Running your recent example I get the following error:

```
Value 'mask_only' not found in config (defaults not allowed).
  File "/Users/chris/Collabs/1.10/cleaning_eval/deepfilter_python.py", line 17, in <module>
    model, df_state, _ = init_df()
ValueError: Value 'mask_only' not found in config (defaults not allowed).
```

**Comment by Rikorose** [comment]
This is fixed on main. As a workaround use:
```py
    model, df_state, _ = init_df(config_allow_defaults=True)
```
