### ISSUE TITLE
Question about data generation

### ISSUE THREAD

**Issue by rohithmars** [Rikorose/DeepFilterNet#25]
Hi,

In the current framework, it seems the speech, noise and RIRs path have to be provided as lists to create the hdf5 sets for training. I have few questions on the same.
1) How to check the size of dataset used for training? For example, if the number of speech samples is 10 with each sample 3 s in duration, the dataset size used is 30s? In other words, how to prepare datasets of different size? Is it based on the number of speech samples?
2) Regarding data augmentation. I see it is build from dataset.rs . If the values of SNR or gains need to be changed, does it needs to be re-build?

**Comment by Rikorose** [comment]
Hi there,

Indeed, the perpare_data.py script expects a test file containing a list with paths.
1. Yes, dataset size is 30s in this case. You can create larger datasets by providing more audio samples.
2. The SNRs are currently hardcoded. I would accept a PR to make this configurable.
