### ISSUE TITLE
 why the original code of DeeFilterNet is not consistent with the paper

### ISSUE THREAD

**Issue by smylab** [Rikorose/DeepFilterNet#250]
Hi Rikorose,
For the original code of DeepFilterNet, why the architecture in ErbDecoder stage is not consistent with the architecture in the paper ?(This paper :   DeepFilterNet: A Low Complexity Speech Enhancement Framework for Full-Band Audio based on Deep Filtering)

1. The architecture in the paper showed that the ErbEncoder's output (e.g., emb0) is directly input to ErbDecoder.
2. The code on Github is ErbEncoder's output +DFnet's partial output (e.g., emb=emb0+cemb) as the  input to ErbDecoder

ErbDecoder of 1 does not depend on DFnet (framework in the paper)
ErbDecoder of 2 needs to depend on DFnet (actual code on Github )

Is the effect of 2 superior to 1? Why the framework in the paper is not used?

Thank you!

**Comment by Rikorose** [comment]
You are right, the complex features are also processed within the encoder. This is missing in figure 2. This however is beneficial since the complex features are not compressed in frequency.

**Comment by smylab** [comment]
> You are right, the complex features are also processed within the encoder. This is missing in figure 2. This however is beneficial since the complex features are not compressed in frequency.

Thank you very much, this is very helpful to me.
