### ISSUE TITLE
Question about data-preprocessing

### ISSUE THREAD

**Issue by aaronhsueh0506** [Rikorose/DeepFilterNet#26]
Hi, thanks for your amazing works.
I try to follow the step in readme.md to make a dataset.

I am little confused about make hdf5 and cfg:
 1. Because we have 3 categories (speech,noise,RIRs), should I make 3 hdf5 corresponding to the above 3 categories?
2. In dataset.cfg, the readme.md says that it should contain the 3 entries(train,valid,test), and optionally sampling factor.
    - So I need to fill the each entry in the .cfg for 3 hdf5 which generate from question1?
    - The sum of the sampling factor in 3 entries is 1?
    - Is the following wording correct?
```
{
  "train":[
  [
     "TRAIN_SET_SPEECH.hdf5",
     0.6
  ],
  [
     "TRAIN_SET_NOISE.hdf5",
     0.6
  ],
  [
     "TRAIN_SET_RIR.hdf5",
     0.6
  ]
 ],

"valid":[
  [
     "TRAIN_SET_SPEECH.hdf5",
     0.2
  ],
  [
     "TRAIN_SET_NOISE.hdf5",
     0.2
  ],
  [
     "TRAIN_SET_RIR.hdf5",
     0.2
  ]
 ],

"test":[
  [
     "TRAIN_SET_SPEECH.hdf5",
     0.2
  ],
  [
     "TRAIN_SET_NOISE.hdf5",
     0.2
  ],
  [
     "TRAIN_SET_RIR.hdf5",
     0.2
  ]
 ],

}
```

**Comment by Rikorose** [comment]
Hi there,

thanks for you interest in DeepFilterNet. Your example seems mostly correct. 
1. Yes, this should work. I have not tested combining noise/speech/rir datasets into one hdf5.
2. If you don't need RIR augmentation, you can only provide noise and speech datasets. The sum of the sampling factors do not need to sum up to 1. the 60/20/20% split should be done beforehand. This oversampling factor states how often this dataset should be used within one epoch. If it is smaller than 1, not all samples will be used. If it is larger than 1, samples will be used also more then once. Tldr: Set it to 1, if you don't have a good reason for a different sampling factor.

**Comment by aaronhsueh0506** [comment]
Hi Rikorose, Thanks for your sharing!

This means I can make 9 .hdf5 (3 categories and 3 splits), and set the sampling factor to 1.

I will try this way to augment data first, and I will continue to work on DeepFilterNet.

Best regards,
