### ISSUE TITLE
Amplified noise

### ISSUE THREAD

**Issue by Chopin68** [Rikorose/DeepFilterNet#260]
When I use the default configured deepfilter to reduce noise, the noise is amplified
Is there any parameter that can solve this strange phenomenon
![image](https://user-images.githubusercontent.com/75252160/220279997-eae2f479-77cc-4b8f-8349-e7604c4226db.png)
![image](https://user-images.githubusercontent.com/75252160/220280016-da634d85-dcc8-4607-a1c7-d37793f8c57e.png)

**Comment by Chopin68** [comment]
> 
When I use the default configured deepfilter to reduce noise, the noise is amplified
Is there any parameter that can solve this strange phenomenon ![image](https://user-images.githubusercontent.com/75252160/220279997-eae2f479-77cc-4b8f-8349-e7604c4226db.png) ![image](https://user-images.githubusercontent.com/75252160/220280016-da634d85-dcc8-4607-a1c7-d37793f8c57e.png)

**Comment by Rikorose** [comment]
You have some clipping going on there and should also see some warnings. Generally the model should not introduce any clipping, but if your input signal is very close to clipping (i.e. has values around 1 or -1), then you might see this effect. Try to reduce the input amplitude by a small amount. E.g. via sox:

```bash
sox -v 0.95 in.wav out.wav
```

**Comment by Chopin68** [comment]
[test.zip](https://github.com/Rikorose/DeepFilterNet/files/10791372/test.zip)

This is my test audio. It comes from a talk show a long time ago. The noise is similar to the sound of electricity

**Comment by Rikorose** [comment]
Have you tried to reduce the gain as I said?

**Comment by Chopin68** [comment]
> Have you tried to reduce the gain as I said?

This is really effective. After I reduce the loudness, this situation disappears. Thank you for your timely response!
![image](https://user-images.githubusercontent.com/75252160/220296410-ea0b0b11-a5d9-4cb1-807b-a694e21ef31d.png)
