### ISSUE TITLE
about low latency speech enhancement

### ISSUE THREAD

**Issue by mycan12345** [Rikorose/DeepFilterNet#261]
Thanks for you awsome work @Rikorose 
I want use the low latency model to enhance speech file, but i got the wrong message as follow...
(base) a123@123:~/test/DeepFilterNet$ cd DeepFilterNet
(base) a123@123:~/test/DeepFilterNet/DeepFilterNet$ export PYTHONPATH=$PWD
(base) a123@123:~/test/DeepFilterNet/DeepFilterNet$ python /home/a123/test/DeepFilterNet/DeepFilterNet/df/enhance.py -m /home/a123/test/DeepFilterNet/models/DeepFilterNet2_onnx_ll.tar.gz /home/a123/test/DeepFilterNet/audio/VID_20210515_203326-48.wav
Traceback (most recent call last):
  File "/home/a123/test/DeepFilterNet/DeepFilterNet/df/enhance.py", line 332, in <module>
    run()
  File "/home/a123/test/DeepFilterNet/DeepFilterNet/df/enhance.py", line 328, in run
    main(args)
  File "/home/a123/test/DeepFilterNet/DeepFilterNet/df/enhance.py", line 27, in main
    model, df_state, suffix = init_df(
  File "/home/a123/test/DeepFilterNet/DeepFilterNet/df/enhance.py", line 108, in init_df
    raise NotADirectoryError("Base directory not found at {}".format(model_base_dir))
NotADirectoryError: Base directory not found at /home/a123/test/DeepFilterNet/models/DeepFilterNet2_onnx_ll.tar.gz

**Comment by Rikorose** [comment]
As the error states, you need to provide a directory, not an onnx file. If you don't provide anything, the default model will be taken.

The onnx model us meant for the deep-filter binary.

**Comment by mycan12345** [comment]
> As the error states, you need to provide a directory, not an onnx file. If you don't provide anything, the default model will be taken.
> 
> The onnx model us meant for the deep-filter binary.
Thank you for your quick reply!
I'm sorry, I'm a newbie I can't understand what you mean, Could you give me an example of running a low latency model?

**Comment by Rikorose** [comment]
It's documented here: https://github.com/Rikorose/DeepFilterNet#deep-filter

so essentially:
```bash
deep-filter -m /home/a123/test/DeepFilterNet/models/DeepFilterNet2_onnx_ll.tar.gz noisy_audio.wav
```

**Comment by mycan12345** [comment]
> It's documented here: https://github.com/Rikorose/DeepFilterNet#deep-filter
> 
> so essentially:
> 
> ```shell
> deep-filter -m /home/a123/test/DeepFilterNet/models/DeepFilterNet2_onnx_ll.tar.gz /home/a123/test/DeepFilterNet/audio/VID_20210515_203326-48.wav
> ```
When I run "deepFilter /home/a123/test/DeepFilterNet/audio/VID_20210515_203326-48.wav" I got the right result.
but run "deep-filter -m /home/a123/test/DeepFilterNet/models/DeepFilterNet2_onnx_ll.tar.gz /home/a123/test/DeepFilterNet/audio/VID_20210515_203326-48.wav"  NotADirectoryError: Base directory not found at /home/a123/test/DeepFilterNet/models/DeepFilterNet2_onnx_ll.tar.gz
as follow pic show
![image](https://user-images.githubusercontent.com/12930240/220868357-fbdfff31-acda-426a-8c0f-a278bf0b46a8.png)

**Comment by Rikorose** [comment]
You need to download the **binary**, this does not work with python. Please read the documentation again.

**Comment by mycan12345** [comment]
> You need to download the **binary**, this does not work with python. Please read the documentation again.

I have read the documentation and download binary, but I dont know how to run this binary. when I try to run "deep-filter" command. the system return "deep-filter: command not found".  I know this is a sample question. could you help me run this binary. Thank you very much.

**Comment by Rikorose** [comment]
What os are you using?

**Comment by mycan12345** [comment]
> What os are you using?

Ubuntu 22.04.2 LTS

**Comment by Rikorose** [comment]
This is just basic linux stuff and you will find tons of information in the internet how to run a binary. I cannot give you more support than this.

You need to download the binary, put it into your current folder or in a folder included in $PATH and run the binary via `./deep-filter`. You might need to give it executable rights via `chmod +x ./deep-filter`.

**Comment by mycan12345** [comment]
Hi @Rikorose 
when I run deep-filter.exe on Windows system(Win10),some error found, could you help me fix this problem? thanks
H:\dsp\deepfilternet>.\deep-filter.exe -m H:\dsp\deepfilternet\DeepFilterNet-main\models\DeepFilterNet2_onnx_ll.tar.gz H:\dsp\deepfilternet\audio\123-48000.wav
thread 'main' panicked at 'not yet implemented', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\tract-hir-0.18.5\src\ops\array\reshape.rs:133:17
stack backtrace:
   0:     0x7ff7f6525410 - <unknown>
   1:     0x7ff7f639846b - <unknown>
   2:     0x7ff7f6518db1 - <unknown>
   3:     0x7ff7f65270e1 - <unknown>
   4:     0x7ff7f6527767 - <unknown>
   5:     0x7ff7f65275a3 - <unknown>
   6:     0x7ff7f652751f - <unknown>
   7:     0x7ff7f65274f4 - <unknown>
   8:     0x7ff7f7133b85 - <unknown>
   9:     0x7ff7f7133c7c - <unknown>
  10:     0x7ff7f6c17d30 - <unknown>
  11:     0x7ff7f6c16247 - <unknown>
  12:     0x7ff7f6d78d15 - <unknown>
  13:     0x7ff7f6bc836d - <unknown>
  14:     0x7ff7f6c7c7e9 - <unknown>
  15:     0x7ff7f63ed310 - <unknown>
  16:     0x7ff7f631cac0 - <unknown>
  17:     0x7ff7f63ac706 - <unknown>
  18:     0x7ff7f633492d - <unknown>
  19:     0x7ff7f71326cc - <unknown>
  20:     0x7ffb760c7614 - BaseThreadInitThunk
  21:     0x7ffb766226a1 - RtlUserThreadStart

**Comment by Rikorose** [comment]
Could you open a new issue for this. Please build with debug information to provide a meaningful stacktrace
