### ISSUE TITLE
Adding relu and tanh activations for deep filter parameters

### ISSUE THREAD

**Issue by HeuristicHermann** [Rikorose/DeepFilterNet#271]
Hi,

congrats on and thank you for building this awesome repo :)

I have a question about the model architecture:
For the prediction of the deep filter parameters in the df decoder forward pass, we add c and c0.
If I understand correctly, c comes from a tanh activation while c0 comes from a relu activation. What is the rationale regarding this choice?

**Comment by Rikorose** [comment]
`c` comes from the GRU output and is thus a weighted sum of tanh and sigmoid. `c0` is a conv output used to propagate features at the original frequency resolution to the last layers. Here, of course one could argue to also use a tanh activation for these convolutions since it may be better suited for complex numbers. I haven't experimented with this though.

**Comment by HeuristicHermann** [comment]
Thanks for the quick reply. As I see it the c goes through df_out 
`c = self.df_out(c)` 
in line 369.
df_out is defined as 
`self.df_out = nn.Sequential(df_out, nn.Tanh())`, 
i.e., this restricts the values of c to be in [-1,1]. 
c0 goes through a conv layer with relu activation, i.e., the features would be restricted to lie in [0,inf]. 
Adding up via `c= c+c0` thus results in deep filter parameters that are restricted to [-1,inf], where the skip connection feature maps can only increase parameter values by adding a positive value to c.
(In contrast, in the erb decoder, the skip connection and decoder features maps are combined and the subsequent sigmoid ensures that mask values are in [0,1].)
Is this desired behaviour? What is the purpose of restricting the filter parameters via the tanh in general and do you think  it would be fine to use a linear activation, i.e., have unrestricted output ranges for the filter parameters?
