### ISSUE TITLE
Training with custom dataset

### ISSUE THREAD

**Issue by anasvaf** [Rikorose/DeepFilterNet#272]
Hello @Rikorose! Thank you for making your implementation public. It is a great piece of work!
I am in the process of training DeepFilterNet from scratch using your training pipeline in the README.
However, I only have a Train and Validation folder that contains both clean and noisy (stationary/non-stationary noises mixed with the clean) signals. Any tips on how to modify the dataset preparation for training?

Basically my Dataset config would look like:

{
  "train": [
    [
      "TRAIN_SET_SPEECH.hdf5",
      1.0
    ],
    [
      "TRAIN_SET_NOISE.hdf5", --> should be the mixed file, not just the noise itself
      1.0
    ],
  ],
  "valid": [
    [
      "VALID_SET_SPEECH.hdf5",
      1.0
    ],
    [
      "VALID_SET_NOISE.hdf5", --> should be the mixed file, not just the noise itself
      1.0
    ],
  ]
}

Thank you in advance! Apologies if there has already been a similar question asked in the repository.

**Comment by Rikorose** [comment]
This is not supported by the dataloader. You would need to implement your own, e.g. using the pytorch dataloader utils.
