### ISSUE TITLE
class DfOp questions

### ISSUE THREAD

**Issue by Eie1** [Rikorose/DeepFilterNet#277]
Dear author,
Could I use class DfOp to make frequency domain also filtered?
I read a paper "Deep Filtering: Signal Extraction and Reconstruction Using Complex Time-Frequency Filters "
it use filter method in time and  frequency domain at the same time in order to enhance phase, could I use class DfOp to do the same thing as this paper?
Thank you for your answering

**Comment by Rikorose** [comment]
Deep Filtering is only applied in frequency domain. I dont do any time domain filtering. DfOp is doing the same thing as in the paper which is why this repo is called DeepFilterNet.

**Comment by Eie1** [comment]
Thank you for your answering.I have a deep understanding now,
Is the Deep Filter in your paper is for enhance phase and compensate the low precision caused by ERB method at the same time?

**Comment by Rikorose** [comment]
It can do its processing independently of the ERB part, but yes, its for enhancing the phase.

**Comment by Eie1** [comment]
Thank you very much, there is another question, removing noise between speech harmonics is equal to  enhancing the phase or is helpful for  enhancing the phase?

**Comment by Rikorose** [comment]
In speech enhancement case ist equal to enhancing the phase

**Comment by Eie1** [comment]
Thank you,  if I want to use the model in your paper in 16k fs,should I input all frequency bins or also input low frequency bins as in 48k fs?

**Comment by Rikorose** [comment]
If you want to use my pretrained model from python, you can input any audio, it will do the resampling automatically.

**Comment by Eie1** [comment]
Okay,thank you for answering again,is the model in your paper is more appropriate   for 48k fs,and it is not a good choise to change to use  in 16k fs?Or I can also change code and use  in 16k fs and get a good result

**Comment by Rikorose** [comment]
You can also retrain it with a sampling rate of 16k. You might want to change the following options as well: 
```
sr = 16000
fft_size = 320
hop_size = 160
nb_erb = 24
nb_df = 96
min_nb_erb_freqs = 1
```

**Comment by Eie1** [comment]
Okay,thank you for helping

**Comment by Eie1** [comment]
Dear author,one of the df_decoder `s input c0(whose size is 96,=nb_df) is low frequency bins cut from 161 ,is it right?
could I cut the 96 strightly from 161?

**Comment by Rikorose** [comment]
Yes

**Comment by Eie1** [comment]
Okay，thank you , and what is the best group number for gru and linear which is 1 group in code

**Comment by Eie1** [comment]
Dear author，could you help to explain the questions above？I will appreciate if you can help，thank you again

**Comment by Rikorose** [comment]
I think the defaults are good. Of course, you can do your own research and try to optimize these parameters
