### ISSUE TITLE
unexpected keyword argument 'p_interfer_sp'

### ISSUE THREAD

**Issue by sparx00** [Rikorose/DeepFilterNet#278]
Hi @Rikorose. Thank you very much for making this available to the community. It is amazing.

I have been trying out training DeepFilterNet on a small portion of the DNS dataset but I have run into a problem. I am following the approach outlined in the repo readme, meaning that I split the audio and noise data into 3 groups each (train, validation, and test). I am not using RIRs. Next, I transform the data into hdf5 format, yielding six hdf5 files that I put into data_dir folder and create a dataset config. I also create the model base_dir where I put the config from DeepFilterNet2 model. Then I run python df/train.py path/to/dataset.cfg path/to/data_dir/ path/to/base_dir. However, after a while, I am getting 
`TypeError: __init__() got an unexpected keyword argument 'p_interfer_sp'`.

I am probably missing something, How can I go around this? Thank you.

**Comment by Rikorose** [comment]
Hi, which version are you running exactly. This is fixed on latest main.

**Comment by sparx00** [comment]
0.4.0

**Comment by Rikorose** [comment]
Then you need to use latest main, or wait for the next release
