### ISSUE TITLE
noisy to enhanced unexpected result

### ISSUE THREAD

**Issue by lflyme** [Rikorose/DeepFilterNet#283]
![noisy2enhanced](https://user-images.githubusercontent.com/9213295/227089643-b057cfa6-d762-4582-8005-a240299521ce.jpg)
Hi Rikorose,    
when the magnitude of noisy is  larger or overflow, the enhanced speech will generate a strong harmonic and overflow, the result show as above figure,  why this happen?  Is the deepfilternet stage2 result? but I try to training only erb, the result still the same.

**Comment by Rikorose** [comment]
> larger or overflow

What do you mean with that? If your input is clipping, then try to reduce the amplitude.
