### ISSUE TITLE
Not getting the results I was hoping for

### ISSUE THREAD

**Issue by wslbeck** [Rikorose/DeepFilterNet#286]
Thanks for your awesome work!
I am trying to use DNS4 track1 data to reproduce the results of deepfilternet2, which has been unable to meet the performance indicators of your paper. 
I would like to ask if you only use the first three seconds of each speech, even though it is more than 10 seconds long?
Looking forward to your reply. Thank you

**Comment by Rikorose** [comment]
I only use 3 second samples for training

**Comment by wslbeck** [comment]
Thank you for your reply.
I still have the following two questions. Could you please answer them?
 1. In this case, the network should actually process about one-third of the total data in an epoch, if each voice is 10 seconds long
 2. May I ask whether you use different three-second data in different epoch？If so, how many different 3 seconds would a 10-second speech be divided into? In each epoch, it's 3 seconds of random cuts, right?

**Comment by Rikorose** [comment]
1. Yes
2. Different random cuts in each training epoch
