### ISSUE TITLE
about libdf python code?

### ISSUE THREAD

**Issue by Yaho-b** [Rikorose/DeepFilterNet#290]
Hi,
I'm retraining DeepFilterNet2 and learning code?I want to konw libdf detailed implementation about python code,such as: analysis, erb, erb_norm function,etc in pyDF/libdf.pyi. Can u share it? Thanks!
Now libdf.pyi just like: I cannot konw the specific role.
def analysis(self, input: ndarray) -> ndarray:
        """Analysis of a time-domain signal.
        Args:
            input (ndarray): 2D real-valued array of shape [C, T].
            reset (bool): Reset STFT buffers before processing. Defaults to `true`.
        Output:
            output (ndarray): 3D complex-valued array of shape [C, T', F], where F is the `fft_size`,
                and T' the original time T divided by `hop_size`.
        """
    ...
def erb_norm(erb: ndarray, alpha: float, state: Optional[ndarray] = None) -> ndarray: ...

**Comment by shawnyxf** [comment]
> pyDF

Hi，is there any python source code, thanks for your reply in advance
