### ISSUE TITLE
Value 'mask_only' not found in config

### ISSUE THREAD

**Issue by PhucLee2605** [Rikorose/DeepFilterNet#293]
I have just pip deepfilternet from Pypi, torch==1.13.1 and I try to run provided python script for inferring df.enhance. The ValueError returned "Value 'mask_only' not found in config"
![image](https://user-images.githubusercontent.com/88246407/230032559-6c58d9a6-0b1d-42a2-b578-eeb5170401c4.png)

**Comment by PhucLee2605** [comment]
@neural-loop I'm still struggling with this problem, can you please show me a complete code snippet for using it?

**Comment by grazder** [comment]
i've fixed this problem with flag `config_allow_defaults=True`, but i'm not sure if model with run properly with this flag
