### ISSUE TITLE
The output of onnx model

### ISSUE THREAD

**Issue by Penguin168** [Rikorose/DeepFilterNet#296]
Thank you for your excellent work! 
I am attempting to use an ONNX model to generate a WAV file in Python identical to that produced by enhance.py.
My understanding is that after extracting the features from the input WAV file, they are fed into the encoder, and the resulting output is obtained after passing through the ERB decoders and DF decoders. This output consists of the coefficients of the DF decoder.
Do I understand correctly?

My question is how to convert these coefficients to a WAV file using only ONNX models? Do you have any suggestions or examples that could assist me in achieving this?

**Comment by Penguin168** [comment]
Thank you for the suggestions you provided!

I have successfully implemented all the methods in enhance.py using Python, and replaced the model part with an ONNX model. However, the sound quality generated using the ONNX model is not as good as using the original model. I have tried using my own trained ONNX model as well as the one provided by you, but the results are not satisfactory.
I'm wondering if there might be some onnx functions in export.py that are not optimized properly, causing significant differences in the output results. Do you have any thoughts or suggestions on how to improve this issue?

My testing wav file which sample rate is surely 48000

**Comment by 63liucan63** [comment]
hello，I am trying to export the onnx model using export.py, but I have encountered some issues as follows:
/*****************************************************************************************************************************
RuntimeError:
Expected a default value of type Tensor (inferred) on parameter "h".Because "h" was not annotated with an explicit type it is assumed to be type 'Tensor'.:
  File "/DeepFilterNet-0.4.0/DeepFilterNet/df/modules.py", line 693
    def forward(self, input: Tensor, h=None) -> Tuple[Tensor, Tensor]:
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        input = self.linear_in(input)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        x, h = self.gru(input, h)
        ~~~~~~~~~~~~~~~~~~~~~~~~~
        if self.gru_skip is not None:
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            x = x + self.gru_skip(input)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        x = self.linear_out(x)
        ~~~~~~~~~~~~~~~~~~~~~~
        return x, h
        ~~~~~~~~~~~ <--- HERE
/**********************************************************************************************************************************
I want to know if you have encountered similar problems and how to solve them？

**Comment by Penguin168** [comment]
> hello，I am trying to export the onnx model using export.py, but I have encountered some issues as follows: /***************************************************************************************************************************** RuntimeError: Expected a default value of type Tensor (inferred) on parameter "h".Because "h" was not annotated with an explicit type it is assumed to be type 'Tensor'.: File "/DeepFilterNet-0.4.0/DeepFilterNet/df/modules.py", line 693 def forward(self, input: Tensor, h=None) -> Tuple[Tensor, Tensor]: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ input = self.linear_in(input) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ x, h = self.gru(input, h) ~~~~~~~~~~~~~~~~~~~~~~~~~ if self.gru_skip is not None: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ x = x + self.gru_skip(input) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ x = self.linear_out(x) ~~~~~~~~~~~~~~~~~~~~~~ return x, h ~~~~~~~~~~~ <--- HERE /********************************************************************************************************************************** I want to know if you have encountered similar problems and how to solve them？

I have not encountered this problem before, but after several days of testing, I found that there are some bugs in export.py.
Outputting encoder, erb_decoder, and df_decoder separately is not feasible. The entire model needs to be converted together to obtain the same output results as the original model, but onnx can not tranfer the full model in this issue. 
Using torch.jit.trace() is better.

**Comment by 63liucan63** [comment]
> > hello，I am trying to export the onnx model using export.py, but I have encountered some issues as follows: /***************************************************************************************************************************** RuntimeError: Expected a default value of type Tensor (inferred) on parameter "h".Because "h" was not annotated with an explicit type it is assumed to be type 'Tensor'.: File "/DeepFilterNet-0.4.0/DeepFilterNet/df/modules.py", line 693 def forward(self, input: Tensor, h=None) -> Tuple[Tensor, Tensor]: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ input = self.linear_in(input) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ x, h = self.gru(input, h) ~~~~~~~~~~~~~~~~~~~~~~~~~ if self.gru_skip is not None: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ x = x + self.gru_skip(input) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ x = self.linear_out(x) ~~~~~~~~~~~~~~~~~~~~~~ return x, h ~~~~~~~~~~~ <--- HERE /********************************************************************************************************************************** I want to know if you have encountered similar problems and how to solve them？
> 
> I have not encountered this problem before, but after several days of testing, I found that there are some bugs in export.py. Outputting encoder, erb_decoder, and df_decoder separately is not feasible. The entire model needs to be converted together to obtain the same output results as the original model, but onnx can not tranfer the full model in this issue. Using torch.jit.trace() is better.

I tried torch. jit. trace() before, but still encountered some issues that couldn't be resolved. Can I take a look at your modified script? And scripts for reasoning and validation using the onnx model?

**Comment by 63liucan63** [comment]
> > > > hello，I am trying to export the onnx model using export.py, but I have encountered some issues as follows: /***************************************************************************************************************************** RuntimeError: Expected a default value of type Tensor (inferred) on parameter "h".Because "h" was not annotated with an explicit type it is assumed to be type 'Tensor'.: File "/DeepFilterNet-0.4.0/DeepFilterNet/df/modules.py", line 693 def forward(self, input: Tensor, h=None) -> Tuple[Tensor, Tensor]: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ input = self.linear_in(input) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ x, h = self.gru(input, h) ~~~~~~~~~~~~~~~~~~~~~~~~~ if self.gru_skip is not None: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ x = x + self.gru_skip(input) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ x = self.linear_out(x) ~~~~~~~~~~~~~~~~~~~~~~ return x, h ~~~~~~~~~~~ <--- HERE /********************************************************************************************************************************** I want to know if you have encountered similar problems and how to solve them？
> > > 
> > > 
> > > I have not encountered this problem before, but after several days of testing, I found that there are some bugs in export.py. Outputting encoder, erb_decoder, and df_decoder separately is not feasible. The entire model needs to be converted together to obtain the same output results as the original model, but onnx can not tranfer the full model in this issue. Using torch.jit.trace() is better.
> > 
> > 
> > I tried torch. jit. trace() before, but still encountered some issues that couldn't be resolved. Can I take a look at your modified script? And scripts for reasoning and validation using the onnx model?
> 
> ![aa](https://user-images.githubusercontent.com/60143927/236418994-330e3016-3705-45fd-95d2-b6665c4c39a6.PNG) Just give a model and inputs to torch.jit.trace(), then save it.

I tried, but still reported an error here at jit. When jit=true, it displayed RuntimeError: NYI: Named tensors are not supported with the tracer. I looked up some information but couldn't find a suitable solution. The error appeared in "deepfilternet2. py, line 290, in forward coefs=coefs. unflatten (-1, (5, 2)). permute (0, 3, 1, 2, 4)" here, when I modified the export_ Full: bool=True, the same error occurred.
Now I have set jit=False and exported three models, but I have not verified whether the models are correct. Did you say before that exporting three models separately resulted in incorrect results? But I can't export the entire model now

**Comment by Penguin168** [comment]
If you just want to use the onnx model, authors have provided onnx models already. (in /model/DeepFilterNet2_onnx.tar.gz)
But if you want to export the onnx model which is trained by yourself, maybe you can download the new version of DeepFilterNet and retry it, I can export onnx model and torch jit model successfully, either exporting three models or exporting entire model.

(I found the way that export entire onnx model successfully and have same results of original model, but need to modify deepfilternet3.py )

**Comment by 63liucan63** [comment]
> @63liucan63
> 
> If you just want to use the onnx model, author has provided onnx models already. (in /model/DeepFilterNet2_onnx.tar.gz) But if you want to export the onnx model which is trained by yourself, maybe you can download the new version of DeepFilterNet and retry it, I can export onnx model and torch jit model successfully, either exporting three models or exporting entire model.
> 
> (I found the way that export entire onnx model successfully and have same results of original model, but need to modify deepfilternet3.py )

I want to export my own model. Do you mean that the result of exporting the model from deepfilternet2 is incorrect? (Whether it is a separate three small models or the entire model?), I may need to retrain with deepfilternet3. May I ask what specific modifications need to be made to deepfilternet3? Now I'm using deepfilternet2 to export the entire model. It seems that the main issue is with the opset version

**Comment by 63liucan63** [comment]
> @63liucan63
> 
> In my opinion, I won't say the result of exporting the model from deepfilternet2 is incorrect, but need to make sure all the model version that you used is the same.
> 
> In the latest version, the default model is deepfilternet3, so if you trained with deepfilternet2, check all the related parameters and change to deepfilternet2 (maybe in model.py, config.ini)
> 
> I didn't modify any code when I was training, and the model is deepfilternet3, maybe the default model is deepfilternet3 in that time. But I using the pretrained model (deepfilternet2) which is provided by author to convert to onnx model is successfull.
> 
> And the opset version is not the main issue, I tried using opset version from 11 to 18, all of them can not export entire onnx model, but can export three model separately.

Well, the only error I'm showing now is the opset version
In order to improve the noise reduction effect, I loaded the author's pre trained model "model_96. ckpt. best" and continued training on this basis. Parameter correspondence is indeed an important issue. The default code is DeepFilterNet3. Initially, I used the automatically generated config.ini for training, but the training effect was obviously incorrect. Therefore, I used the author's original DeepFilterNet2 config.ini directly for subsequent training, The training effect is acceptable, and now it is stuck in the export of the complete model.
I exported the "model_96. ckpt. best" model as you mentioned, using 2 or 3 for config.ini and DeepFilterNet3 for the model. However, none of them were able to export the complete model, and the error displayed was only the opset version. So have you solved the problem with OPSET?Or where is the main problem?

**Comment by Penguin168** [comment]
@63liucan63 

What's the error message that show on your computer?
Yeah, using automatically generated config.ini for training is absolutly incorrect, if you used original config.ini for training, then should use the same config.ini for exporting onnx model.

I have encountered the problem which is about opset version while I was exporting the onnx model, but In this situation I set `export_full: bool = True`,  and the error message is talking about that opset version is not support with torch.view_as_complex(). I modifed deepfilternet3.py to solve this problem.

**Comment by 63liucan63** [comment]
> @63liucan63
> 
> What's the error message that show on your computer? Yeah, using automatically generated config.ini for training is absolutly incorrect, if you used original config.ini for training, then should use the same config.ini for exporting onnx model.
> 
> I have encountered the problem which is about opset version while I was exporting the onnx model, but In this situation I set `export_full: bool = True`, and the error message is talking about that opset version is not support with torch.view_as_complex(). I modifed deepfilternet3.py to solve this problem.

Let me recreate my mistake, it may be a bit long. Thank you for your patience
**Premise**
 I have ensured the consistency between the model and config.ini, using both deepfilternet2，and the model training has loaded the author's pre trained model and continued training using my own data.

Firstly, in export.py, I only modified line 97 of 'if jit: model=torch. jit. script (model)', and as I initially described to you, the error displayed on line 691 of module. py after running, 'Expected a default value of type Tensor (preferred) on parameter' h '. Because' h 'was not annotated with an explicit type it is accumulated to be type' Tensor '
”
def forward(self, input: Tensor, h=None) -> Tuple[Tensor, Tensor]:
”
I printed the shape of h as "torch. Size ([1, 1, 256]) and torch. Size ([2, 1, 256])". I tried to set h to torch. zero (1/2, 1，256), but the shape of h is not fixed, which is clearly incorrect.

Then I modified "if jit: model=torch. git. script (model)" to "if jit: model=torch. git. trace (model, inputs)" and placed this sentence after torch. onnx. export() on line 101 of export.py. After running the code, three models were output, but it showed：

“/DeepFilterNet-0.4.0/env/DeepFilterNet/lib/python3.8/site-packages/torch/onnx/symbolic_opset9.py:1941: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. ”

And a warning appeared, 'Warning | DF | Number of tensors (2) does not match provided names: ['coefs']'

So I think the output of the three models in this way is incorrect because the dimensions of the coefs are inconsistent

As for the output of the complete model, I only modified "export_full: bool=True" and it displayed "RuntimeError: Exporting the operator view_as_complex to ONNX opset version 12 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub." May I ask which part of DeepFilterNet3. py did you modify?

If only DeepFilterNet3 can output the correct model, then it can only be retrained. This must ensure that there are enough types and quantities of noise data to achieve the effect. I want to use the model to denoise only one type of noise.

But currently, even if the three models are outputted separately, I think my results are still incorrect, and the entire model is currently unable to output.
I'm a bit confused now, I don't know where the problem really lies. The model export problem has been bothering me for two weeks now.

**Comment by Penguin168** [comment]
@63liucan63 
So now you can export three models with onnx way and torch.jit way right? If you can, that means you have already exported the entire model. (Try just using torch.jit.trace and ignore the warning from onnx)

You can ignore the warning above, those three models still work (but the result is less than original models).

**Comment by 63liucan63** [comment]
> @63liucan63 So now you can export three models with onnx way and torch.jit way right? If you can, that means you have already exported the entire model. (Try just using torch.jit.trace, ignore the warning from onnx and set `export_full: bool = False`)
> 
> You can ignore the warning above, those three models still work (but the result is less than original models).

It seems like this, changing 'if jit: model=torch. jit. script (model)' to 'if jit: model=torch. jit. trace (model, inputs)' and placing it after torch. onnx. export() did output three models, but I haven't written the onnx inference script yet, so I can't verify the effectiveness of the model yet.
I want to know why the output of the model is so much worse? Is it just a matter of choosing between DF2 and DF3？

**Comment by Penguin168** [comment]
@63liucan63 

Actually, you exported 7 models, 3 of onnx models, 3 of torch models, and a enrire toch model, or you can just use torch.jit() to export models (3 separated models and 1 entire model )

I suggest to use torch full model, it is easier to use, and the onnx model is a little bit difficult for you to use.
I don't know what the exact reason that the output of the three models is relatively poor, but I'm absolutely sure it is not about choosing DF2 or DF3.

**Comment by 63liucan63** [comment]
@Penguin168 
Well, considering the requirements of the device side, deploying resources directly using torch model will increase the usage. I would like to first write a script to verify the effectiveness of the three ONNX models before considering the deployment issue. If the ONNX model really cannot solve the problem, I will try deploying using torch model again.

**Comment by 63liucan63** [comment]
@Penguin168 
I still want to ask about the "RuntimeError: Exporting the operator view_ as_ complex to ONNX opset version 12 is not supported.  Please feel free to request support or submit a pull request on PyTorch GitHub. ”
What modifications did you make to DeepFilterNet3. py for this error?

**Comment by Penguin168** [comment]
@63liucan63 

If you want export full model with onnx, modify DeepFilterNet3. py, comment out last two lines.
```
# spec = self.df_op(spec, df_coefs)
# spec[..., self.nb_df :, :] = spec_m[..., self.nb_df :, :]
```
Then implemeant df_op() by yourself.

**Comment by 63liucan63** [comment]
@Penguin168 
Thank you！I wrote a view_ as_ complex function to replace 'torch. view_as_complex', now DF3 can export the complete model normally.

**Comment by Penguin168** [comment]
@63liucan63 

No problem !
Could I take a look your view_ as_ complex function? I want to learn how other people to do this.

**Comment by Penguin168** [comment]
@63liucan63 

Thank you! It is almost the same as mine lol, I use complex instead of torch.complex.
I just want to know how to do in different dimension without using`if`.

**Comment by 63liucan63** [comment]
@Penguin168 
I haven't considered this issue yet.
May I ask if your ONNX model results are almost the same as the pt model? I observed the spectrograms of them and found that the onnx model processed speech with less vocal information below 4000Hz than the pt model. Are there any other issues that I haven't noticed besides the ones we mentioned earlier?

**Comment by 63liucan63** [comment]
![image](https://github.com/Rikorose/DeepFilterNet/assets/62200746/1b865948-ba84-4ad7-8023-a600cb866d6d)
@Penguin168 
just like this.

**Comment by Penguin168** [comment]
@63liucan63 

Yeah, ONNX model are almost the same as the pt model, I tested both ONNX model and pt model of 20 wav files(48000Hz), the stoi and pesq are almost the same too.

If your onnx model is not good below 4000Hz(precisely is 4800Hz), maybe your df_op() has something wrong.
![Uploading 66.PNG…]()

**Comment by 63liucan63** [comment]
@Penguin168 
I only modified 'view_as_complex' function, and did not modify any other parts of deepfilter3. py, nor did df. op(). May I ask what specific changes you made to df. op()?

**Comment by Penguin168** [comment]
@63liucan63 

I tried your view_as_complex funtion, but couldn't export onnx model, I wanna know how did you export it. The error message is about onnx is not support torch.complex().

In deepfilternet3.py, I comment out last two lines to export onnx model, then using df_op() at output of onnx model.
```
# spec = self.df_op(spec, df_coefs)
# spec[..., self.nb_df :, :] = spec_m[..., self.nb_df :, :]
```
Maybe you can try data which sample rate is 48kHz for testing.

**Comment by 63liucan63** [comment]
@Penguin168 
Regardless of whether those two lines are commented out or not, the complete model can be exported by modifying "view_as_complex". I have encountered this error when using DF2, but DF3 does not have this issue. I think it may be due to a torch version issue.
When I kept these two lines, a warning appeared as follows:
![image](https://github.com/Rikorose/DeepFilterNet/assets/62200746/f3904e6b-6634-4563-ac67-2c4c4720b7b2)

I don't quite understand what 'using df_op() at output of onnx model' means? Can I see how you did it specifically？

**Comment by Penguin168** [comment]
@Penguin168 

Ignoring the warning, it doesn't affect anything, the result is same as pt model.

In deepfilternet3.py, 471th line 
`spec = self.df_op(spec, df_coefs)`
350th line
`self.df_op = MF.DF(num_freqs=p.nb_df, frame_size=p.df_order, lookahead=self.df_lookahead)`
In multiframe.py, 160th line (class DF)
170th and  171th line
```
spec_u = self.spec_unfold(torch.view_as_complex(spec))
coefs = torch.view_as_complex(coefs)
```
The problem is in here.

**Comment by 63liucan63** [comment]
@Penguin168 
emm...
I know the problem is that 'torch. view_as_complex()' cannot be used, so I replaced it with my own 'view_as_complex()', like this:
![image](https://github.com/Rikorose/DeepFilterNet/assets/62200746/7496b056-bc86-426c-b472-0ebcd714e637)

In this case, the following two lines do not need to be removed, do they?
What I want to know is what other modifications did you make after removing these two lines?
 **spec = self.df_op(spec, df_coefs)
 spec[..., self.nb_df :, :] = spec_m[..., self.nb_df :, :]**
ps：I  replaced all the  "torch. view_as_complex()"  that appear in the multiframe.py script with my own function.

**Comment by 63liucan63** [comment]
@Penguin168 
I only modified the 10 "view_as_complex()" functions that appeared in the multiframe.py script, and did not make any other changes.
May I ask if you can now export the complete model of DF2 normally and verify the consistency of the results?

**Comment by Penguin168** [comment]
@63liucan63 

I know your problem now.
I remember you trained the model which is using deepfilternet2, but you export the model with deepfilternet3, that means you didn't export the correct full model. 

When `export_full: bool = True`  exporting the model that use deepfilternet2 will get the error message:
`Exporting the operator 'aten::unflatten' to ONNX opset version 12 is not supported`
That means there are no torch.view_as_complex() in deepfilternet2, so all you need to do is changing to the correct model for exporting and comment out two lines that I said, then implement `self.df_op()` by yourself.

I can export the full model of DF2 by comment out `self.df_op()` but I can't verify the results because the way of implement df_op() has difference between deepfilternet2 and deepfilternet3, I can't use df filter in the same method.

**Comment by 63liucan63** [comment]
@Penguin168 
I did not export the DF2 model using DF3, as these two models themselves have two different nodes.
The error reported by DF2 exporting the model is:
![image](https://github.com/Rikorose/DeepFilterNet/assets/62200746/efd9abc5-1e6c-485d-9ab6-19cbdd455b7e)
My problem now is that the DF3 does not perform well after normal export. As you mentioned earlier, there is a loss in the frequency spectrum below 4800Hz. I would like to ask if you are satisfied with DF for DF3_ Has op() made any modifications?
I tried a 48k model and the problem is the same, so I don't think it's a matter of frequency.

**Comment by Penguin168** [comment]
@63liucan63 
You said you continue training model_96. ckpt. best, and this model is based on DF2. If you want to export it to onnx model, you should modify deepfilteernet2.py instead of deepfilteernet3.py, so there have an error while using DF2 model to exporting is normal, onnx model not support torch.complex currently.

In your case, should not use any script or code which is contained DF3.
I didn't modify df_op(), I just not use it to export the full onnx model.
Yeah, the problem is not about sample rate, the problem is your onnx model not using df filter, that's why noise reduction not active below 4800Hz.

**Comment by 63liucan63** [comment]
@Penguin168 
Perhaps what I said was a bit confusing, but I ensured that there was no mixing of DF2 and DF3.

For **DF2**, I continued training with DF2 on its pre trained model and was unable to export the complete model. The error is that onnx does not support 'torch. complex()'. So, if I want to export the complete DF2 ONNX model, what modifications do I need to make to 'deepfilternet2. py'?
PS: I tried to remove the "df_dec" model and only use the enc model and erb model. The effect is acceptable, which means there is a problem with DF filtering?

For **DF3**, after modifying the "view_as_complex()" function,  "df_op()" should have been fine, but the actual effect of the onnx model has deteriorated. I mainly don't understand this. I used a df filter, but its effect is not very good.

**Comment by Penguin168** [comment]
@63liucan63 

If you use model_96. ckpt as the original model, then no more talk about DF3, deepfilternet2.py and deepfilternet3.py are different, the structure of model_96. ckpt is deepfilternet2, you can't use deepfilternet3.

The problem is not in DF filtering, the probelm is onnx not support 'torch. complex(), but I can't understand why the rusult is acceptable while you remove the df decoder. Is there no noise below 4.8kHz of enhanced audio?

**Comment by 63liucan63** [comment]
@Penguin168 
Can you take a look at how your DF3 "torch. view_as_complex()" function is written? The complete onnx model can be obtained by running the function I modified on Linux before, but an error occurred when switching to local:
“torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::view_as_complex' to ONNX opset version 12 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.”

**Comment by 63liucan63** [comment]
@Penguin168 
Now I can obtain the correct onnx results, but I would like to know how you synthesized the simulated HRTFs mentioned in the author's dataset?

**Comment by Penguin168** [comment]
@63liucan63 
In the end, I didn't use any function which using torch. view_as_complex() while exporting the onnx model, since onnx not support it. I process the tensors which are output of onnx model by using some function that using torch. view_as_complex().

I don't understand your question, there are no HRTFs in dataset.

**Comment by 63liucan63** [comment]
@Penguin168 
I refer to the 60000 simulated reverberation data mentioned in the author's literature, and I don't know how this data was synthesized.

**Comment by zeynepgulhanuslu** [comment]
Hi @63liucan63 I try to convert best deepfilternet3 model to onnx format as whole. From what I understand you managed to do that. If you have time, can you tell me how can I achieve this. Also can you provide a small code snippet for inference with onnx as well. I didn't quite understand how to use this model with onnx format.

Thanks in advance.

**Comment by 63liucan63** [comment]
@Penguin168 
Have you tried to transform the model into a streaming model? After I made the modifications, I found that the effect was still good, but there was some distortion compared to the original model.

**Comment by Penguin168** [comment]
@63liucan63 
I remember that author mentioned he use RIR for reverberation, not HRTFs.
I'm not sure if the onnx model or pth model can be converted to a streaming model, but I'm tring to use the model in real time recently(Python and C). Although author provided the example in rust, I still not understand what algorithm that author use, cause I'm not good at rust.

In my opinion, using the model in real time, using the method of fixed size frame by frame without overlap as an input is not a good way, it cause the ehanced audio has some distortion. I'm not sure what method that you implement streaming, maybe you can discribe it more detail.

**Comment by iPwnXX** [comment]
> > > > > hello，I am trying to export the onnx model using export.py, but I have encountered some issues as follows: /***************************************************************************************************************************** RuntimeError: Expected a default value of type Tensor (inferred) on parameter "h".Because "h" was not annotated with an explicit type it is assumed to be type 'Tensor'.: File "/DeepFilterNet-0.4.0/DeepFilterNet/df/modules.py", line 693 def forward(self, input: Tensor, h=None) -> Tuple[Tensor, Tensor]: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ input = self.linear_in(input) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ x, h = self.gru(input, h) ~~~~~~~~~~~~~~~~~~~~~~~~~ if self.gru_skip is not None: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ x = x + self.gru_skip(input) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ x = self.linear_out(x) ~~~~~~~~~~~~~~~~~~~~~~ return x, h ~~~~~~~~~~~ <--- HERE /********************************************************************************************************************************** I want to know if you have encountered similar problems and how to solve them？
> > > > 
> > > > 
> > > > I have not encountered this problem before, but after several days of testing, I found that there are some bugs in export.py. Outputting encoder, erb_decoder, and df_decoder separately is not feasible. The entire model needs to be converted together to obtain the same output results as the original model, but onnx can not tranfer the full model in this issue. Using torch.jit.trace() is better.
> > > 
> > > 
> > > I tried torch. jit. trace() before, but still encountered some issues that couldn't be resolved. Can I take a look at your modified script? And scripts for reasoning and validation using the onnx model?
> > 
> > 
> > ![aa](https://user-images.githubusercontent.com/60143927/236418994-330e3016-3705-45fd-95d2-b6665c4c39a6.PNG) Just give a model and inputs to torch.jit.trace(), then save it.
> 
> I tried, but still reported an error here at jit. When jit=true, it displayed RuntimeError: NYI: Named tensors are not supported with the tracer. I looked up some information but couldn't find a suitable solution. The error appeared in "deepfilternet2. py, line 290, in forward coefs=coefs. unflatten (-1, (5, 2)). permute (0, 3, 1, 2, 4)" here, when I modified the export_ Full: bool=True, the same error occurred. Now I have set jit=False and exported three models, but I have not verified whether the models are correct. Did you say before that exporting three models separately resulted in incorrect results? But I can't export the entire model now

have you fixed the 'Named tensors are not supported with the tracer' problem? im using deepFilterNet 2 as well, and encountered the same error when using export the full model to onnx.

**Comment by 63liucan63** [comment]
@iPwnXX 
Onnx does not support complex number calculations. In fact, the author's code provides code for real number operations. You can use DFreal to replace DF.

**Comment by victorbcyang** [comment]
@63liucan63 

I am able to produce same results from DFreal and DF. However, when I tried to export the model to onnx, I got this error message:

torch.onnx.errors.SymbolicValueError: Unsupported: ONNX export of operator Unfold, input size not accessible. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues 

Judging from the error message, it seems like onnx doesn't support Unfold. I am wondering did you encounter this before? If yes, how did you resolve this?

Thanks!

**Comment by gyujin-kim** [comment]
@victorbcyang 
Author serve the 'as_windowed' in multiframe.py. check it.
currently, commented in 'spec_unfold_real'

**Comment by 63liucan63** [comment]
@victorbcyang 
Onnx does not support the unfold function, you need to rewrite this function.

**Comment by gyujin-kim** [comment]
@63liucan63 @victorbcyang 
As mentioned above, you can replace 'unfold' to 'as_windowd'

` 
   def spec_unfold_real(self, spec: Tensor):
        if self.need_unfold:
            # spec = self.pad(spec).unfold(-3, self.frame_size, 1)
            # return spec.permute(0, 1, 5, 2, 3, 4)
            return as_windowed(self.pad(spec), self.frame_size, 1, dim=-3)
        return spec.unsqueeze(-1)
`
