### ISSUE TITLE
C++ api execution error.

### ISSUE THREAD

**Issue by tingyang01** [Rikorose/DeepFilterNet#299]
Hello.
I am trying to use this C API.
I've built C API dll with rust 1.68.2 and DeepFilterNet-0.4.0.
#include
#include "deep_filter.h"
#pragma comment(lib,"WS2_32")

int main()
{
float atten_lim = 12.0;
const char* onnxPath = "models/DeepFilterNet2_onnx.tar.gz";
DFState *_dfModel = df_create(onnxPath, atten_lim);
//df_free(dfModel);
std::cout << "Hello World!\n";
}

But I am getting this error on running the execution file:
DeepFilterNet\DeepFilterNetWindows\x64\Release>DeepFilterNetWindows.exe
thread '' panicked at 'not yet implemented', C:\Users\tings.cargo\registry\src\github.com-1ecc6299db9ec823\tract-hir-0.18.4\src\ops\array\reshape.rs:133:17
stack backtrace:
0: std::panicking::begin_panic_handler
at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library\std\src\panicking.rs:575
1: core::panicking::panic_fmt
at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library\core\src\panicking.rs:64
2: core::panicking::panic
at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library\core\src\panicking.rs:111
3: tract_hir::ops::array::reshape::to_axis_ops
4: <tract_hir::ops::array::reshape::Reshape as tract_hir::ops::expandable::Expansion>::wire
5: tract_hir::ops::expandable::<impl tract_hir::infer::rules::InferenceRulesOp for alloc::boxed::Box>::to_typed
6: tract_hir::infer::rules::::to_typed
7: ZN512
$LT$tract_core..model..graph..Graph$LT$tract_hir..infer..fact..InferenceFact$C$alloc..boxed..Box$LT$dyn$u20$tract_hir..infer..ops..InferenceOp$GT$$GT$$u20$as$u20$tract_hir..infer..model..InferenceModelExt$GT$..into_typed..ToTypedTranslator$u20$a
8: tract_core::model::translator::Translate::translate_model
9: <tract_core::model::graph::Graph<tract_hir::infer::fact::InferenceFact,alloc::boxed::Box> as tract_hir::infer::model::InferenceModelExt>::into_typed
10: deepfilter::tract::DfTract::new
11: df_create
12: main
at deepfilternetwindows\deepfilternetwindows\deepfilternetwindows.cpp:13
13: invoke_main
at d:\agent_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
14: __scrt_common_main_seh
at d:\agent_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
15: BaseThreadInitThunk
16: RtlUserThreadStart
note: Some details are omitted, run with RUST_BACKTRACE=full for a verbose backtrace.

Thanks

**Comment by tingyang01** [comment]
Ok, I've fixed the issue on rust 1.67.0.

**Comment by pamzerbhu** [comment]
Hi @tingyang01 ,

Have you been able to use this API successfully? I have tried to use it but it doesn't seem to produce the same denoising results as the pytorch/prebuilt apps. Would you mind helping me figure out what the issue might be?
Best regards,

here is my code,

```
#include <sndfile.h>
#include <samplerate.h>
#include "deep_filter.h"
#include <vector>
#include <iostream>
#include <chrono>
std::vector<float> readWavFile(const char* path, int& sampleRate, size_t& numFrames, int& channels) {
    SF_INFO sfinfo;
    SNDFILE* infile = sf_open(path, SFM_READ, &sfinfo);
    if (!infile) {
        std::cerr << "Failed to open file: " << path << std::endl;
        exit(1);
    }

    std::vector<float> data(sfinfo.frames * sfinfo.channels);
    numFrames = sfinfo.frames;
    channels = sfinfo.channels;
    sampleRate = sfinfo.samplerate;

    if (sf_readf_float(infile, data.data(), sfinfo.frames) != sfinfo.frames) {
        std::cerr << "Failed to read samples from file: " << path << std::endl;
        sf_close(infile);
        exit(1);
    }

    sf_close(infile);
    return data;
}

std::vector<float> resample(const std::vector<float>& input, int srcSampleRate, int targetSampleRate, size_t numFrames, int channels) {
    SRC_DATA srcData;
    srcData.data_in = input.data();
    srcData.input_frames = numFrames;
    srcData.data_out = new float[numFrames * channels * targetSampleRate / srcSampleRate];
    srcData.output_frames = numFrames * targetSampleRate / srcSampleRate;
    srcData.src_ratio = double(targetSampleRate) / srcSampleRate;

    if (src_simple(&srcData, SRC_SINC_BEST_QUALITY, channels) != 0) {
        std::cerr << "Resampling error." << std::endl;
        delete[] srcData.data_out;
        exit(1);
    }

    std::vector<float> output(srcData.data_out, srcData.data_out + srcData.output_frames_gen * channels);
    delete[] srcData.data_out;
    return output;
}

void writeWavFile(const char* path, const std::vector<float>& data, int sampleRate, size_t numFrames, int channels) {
    SF_INFO sfinfo;
    sfinfo.frames = numFrames;
    sfinfo.samplerate = sampleRate;
    sfinfo.channels = channels;
    sfinfo.format = SF_FORMAT_WAV | SF_FORMAT_FLOAT;

    SNDFILE* outfile = sf_open(path, SFM_WRITE, &sfinfo);
    if (!outfile) {
        std::cerr << "Failed to open file for writing: " << path << std::endl;
        exit(1);
    }

    if (sf_writef_float(outfile, data.data(), numFrames) != numFrames) {
        std::cerr << "Failed to write samples to file: " << path << std::endl;
        sf_close(outfile);
        exit(1);
    }

    sf_close(outfile);
}

void process(std::vector<float>& input, std::vector<float>& output) {
    const size_t BUFFER_SIZE = 480;
    float bufin[BUFFER_SIZE];
    float bufout[BUFFER_SIZE];
    size_t inputSize = input.size();

    float atten_lim = 0;
    const char* onnxPath = "models/DeepFilterNet3_ll_onnx.tar.gz";
    DFState *_dfModel = df_create(onnxPath, atten_lim);
    df_set_post_filter_beta(_dfModel, 0.05);
    for (size_t i = 0; i < inputSize; i += BUFFER_SIZE) {
        size_t chunkSize = std::min(BUFFER_SIZE, inputSize - i);
        std::copy(input.begin() + i, input.begin() + i + chunkSize, bufin);
        df_process_frame(_dfModel, bufin, bufout);
        output.insert(output.end(), bufout, bufout + chunkSize);
    }
}

int main(int argc, char* argv[]) {
    if (argc < 3) {
        std::cerr << "Usage: " << argv[0] << " <input.wav> <output.wav>" << std::endl;
        return 1;
    }

    const char* inputPath = argv[1];
    const char* outputPath = argv[2];
    const int targetSampleRate = 48000;

    int sampleRate, channels;
    size_t numFrames;
    auto inputData = readWavFile(inputPath, sampleRate, numFrames, channels);

    auto resampledData = resample(inputData, sampleRate, targetSampleRate, numFrames, channels);
    size_t resampledFrames = resampledData.size() / channels;
    auto start = std::chrono::high_resolution_clock::now();

    std::vector<float> resampledDataout;
    process(resampledData, resampledDataout);
    auto stop = std::chrono::high_resolution_clock::now();
    auto duration = std::chrono::duration_cast<std::chrono::microseconds>(stop - start);

    std::cout << "Time taken by function: " 
         << duration.count() << " microseconds" << std::endl;
    std::cout << "Hello World!\n";
    writeWavFile(outputPath, resampledDataout, targetSampleRate, resampledFrames, channels);

    return 0;
}
```

**Comment by tingyang01** [comment]
Yes, the pytorch result is different from the C++ result.
I've not yet found the reason.

**Comment by crazypotatoo** [comment]
> Yes, the pytorch result is different from the C++ result. I've not yet found the reason.

Same issue, have you solved this problem?

**Comment by LeventureQys** [comment]
well,I met the same situation in cpp exe,I noticed that the function df_create seems be modified so I don't know if it works for your problem.I just change log_level as "Trace" and it's work,that's odd
