### ISSUE TITLE
Occurrence of NaN during training

### ISSUE THREAD

**Issue by rohithmars** [Rikorose/DeepFilterNet#30]
Hi,

There seems to be occurrence of NaN for loss after few epochs during training. 

Is there any way to avoid it?

Is it possible to resume the training from a particular checkpoint? I understand the training is resumed from the last saved checkpoint. But if the last saved checkpoint is NaN, then resuming the training would be an issue.

**Comment by Rikorose** [comment]
Hi,

yes in some rare circumstances NaNs may occur. I am not quite sure what causes them exactly. Starting again from the last checkpoint should work though since it will be checked if the weights contain NaNs before writing the checkpoint.

**Comment by rohithmars** [comment]
Hello,
yes, resuming the training from previous check point helps. Thank you!
