### ISSUE TITLE
compress the model size with 16khz sample rate audio

### ISSUE THREAD

**Issue by flytair** [Rikorose/DeepFilterNet#303]
hi,
it is a amazing project, thanks for your great contributions.

if the sample rate of the training data is decreased to 16khz, do you think it is reasonable to reduce the cnn layers and the first cnn layer kernel size(from 3x3 to 1x3), if keep the receptive field size(in ms) the same as 48khz.

or could you please give some suggestions for compression the model size with 16hz sampling rate training data?

**Comment by flytair** [comment]
thanks for your suggestion, i will try with your parameter setting.

**Comment by JBloodless** [comment]
> thanks for your suggestion.
> in your experiment, is the sampling rate 16KHz?

Yes, I've tried 48k, 24k and 16k with these parameters, all of these cases work as expected

**Comment by flytair** [comment]
> 
thanks for your sharing.

**Comment by 63liucan63** [comment]
@JBloodless 
I am trying to use the parameters you provided to train 16k data, and currently it seems that the effect has significantly decreased. I would like to know if you have taken any other measures to restore the noise reduction effect?
