### ISSUE TITLE
Number of channels/filters in convolutions

### ISSUE THREAD

**Issue by anasvaf** [Rikorose/DeepFilterNet#304]
Dear Hendrik,

I have one question regarding the number of channels/filters of the encoder in the code of DeepFilterNet2. In the paper, there is no mention that the Channels are doubling after each convolution. In the code I could see, based on the comments, that after each convolution the channels/filters are doubling. However, in the arguments you have the channels fixed to 16 (except for the first convolution for ERBs and DFs), as you only change the fstrides. Could you help me with this?
I have attached 2 images to show what I mean.

Thank you in advance!
![channels](https://user-images.githubusercontent.com/23378874/232473181-8ed5eb3a-8aaf-410a-b8a7-c6dea2f507f5.PNG)

![Encoder](https://user-images.githubusercontent.com/23378874/232473184-4c29a4d6-908c-4f76-9f25-fb4ec4658c10.PNG)

![Capture](https://user-images.githubusercontent.com/23378874/232488682-acba5d64-e0dc-4f8c-afa6-51654d4402e1.PNG)

**Comment by Yaho-b** [comment]
You  can find it in ./models/config.ini
