### ISSUE TITLE
Unable to use DeepFilterNet2_onnx_ll.tar.gz with binary `deep-filter`

### ISSUE THREAD

**Issue by weirenlan** [Rikorose/DeepFilterNet#305]
Very thanks for your project, the repo is really awesome.

### Situation
- Currently, i meet a little issue about loading DeepFilterNet2_onnx_ll.tar.gz  with `deep-filter`
- OS: Macos X86_64
- Binary: https://github.com/Rikorose/DeepFilterNet/releases/tag/v0.4.0
    - I downloaded `deep-filter-v0.4.0-x86_64-apple-darwin`
- Usage
```
./deep-filter-v0.4.0-x86_64-apple-darwin -m DeepFilterNet2_onnx_ll.tar.gz test_48k.wav
```
   - Error message
   ```
    thread 'main' panicked at 'not yet implemented', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tract-hir-0.18.5/src/ops/array/reshape.rs:133:17

   ``` 
 - It is okay to load the `DeepFilterNet3_onnx.tar.gz`, if we want to use Deepfilternet2, whether we will  need to make any adjustments? 
 
 Very thanks

**Comment by tangpeng19** [comment]
The same problem with me.
