### ISSUE TITLE
Windows binary error

### ISSUE THREAD

**Issue by jarredou** [Rikorose/DeepFilterNet#307]
Hello.
I'm getting this immediate error when trying to use the CLI version on windows:
``thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TooWide', libDF\src\wav_utils.rs:87:39``

**Comment by UnlimitedCookies** [comment]
I also ran into this issue, I'd suggest an improved error message. Something like "Stereo isn't implemented, try mono".

**Comment by jurihock** [comment]
It also looks like `deep-filter` does not support 24-bit wav files either...
