### ISSUE TITLE
failed to run custom build command for `hdf5-sys v0.8.1`

### ISSUE THREAD

**Issue by Tim5Tang** [Rikorose/DeepFilterNet#32]
when i use the cmd follow install libdfdat, but failed
# Optional: Install libdfdata python package with dataset and dataloading functionality for training
maturin develop --release -m pyDF-data/Cargo.toml

error: failed to run custom build command for `hdf5-sys v0.8.1`

Caused by:
  process didn't exit successfully: `E:\data\deeplearning\pytorch\DeepFilterNet\target\release\build\hdf5-sys-8ffb164969e6e670\build-script-build` (exit code: 101)
  --- stdout
  Searching for installed HDF5 (any version)...
  Found no HDF5 installations.

  --- stderr
  thread 'main' panicked at 'Unable to locate HDF5 root directory and/or headers.', C:\Users\tangzixing\.cargo\registry\src\github.com-1ecc6299db9ec823\hdf5-sys-0.8.1\build.rs:548:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit code: 101": `cargo rustc --message-format json --manifest-path pyDF-data/Cargo.toml --release --lib -- -C link-arg=-s`

**Comment by Rikorose** [comment]
Hi there,

as the error says ` Found no HDF5 installations.` you don't have HDF5 development headers installed.

Refer to http://www.hdfgroup.org/solutions/hdf5/ or your preferred package manger for install instructions.

**Comment by Tim5Tang** [comment]
may this is a good job, but it is hard for me to build the env.

**Comment by Rikorose** [comment]
`pip install deepfilternet[train]` should not require any installed hdf5 libs or rust compiler. It just fetches the prebuild wheel from pypi. Not sure what is going on.

If you want to build the package yourself, could you give me the output of `cargo build`?

**Comment by Tim5Tang** [comment]
thanks for you replay, the info is :
Compiling cfg-if v1.0.0
   Compiling autocfg v1.0.1
   Compiling proc-macro2 v1.0.33
   Compiling unicode-xid v0.2.2
   Compiling libc v0.2.111
   Compiling syn v1.0.82
   Compiling memchr v2.4.1
   Compiling scopeguard v1.1.0
   Compiling serde_derive v1.0.131
   Compiling regex-syntax v0.6.25
   Compiling crossbeam-utils v0.8.5
   Compiling pyo3-build-config v0.15.1
   Compiling proc-macro-hack v0.5.19
   Compiling pkg-config v0.3.24
   Compiling serde v1.0.131
   Compiling lazy_static v1.4.0
   Compiling once_cell v1.8.0
   Compiling parking_lot_core v0.8.5
   Compiling crossbeam-epoch v0.9.5
   Compiling smallvec v1.7.0
   Compiling rawpointer v0.2.1
   Compiling strength_reduce v0.2.3
   Compiling rayon-core v1.9.1
   Compiling unindent v0.1.7
   Compiling log v0.4.14
   Compiling hdf5-types v0.8.1
   Compiling ascii v1.0.0
   Compiling hdf5 v0.8.1
   Compiling ppv-lite86 v0.2.15
   Compiling tinyvec_macros v0.1.0
   Compiling serde_json v1.0.72
   Compiling byteorder v1.4.3
   Compiling itoa v0.4.8
   Compiling either v1.6.1
   Compiling paste v1.0.6
   Compiling ryu v1.0.9
   Compiling bitflags v1.3.2
   Compiling hound v3.4.0
   Compiling cfg-if v0.1.10
   Compiling libloading v0.7.2
   Compiling instant v0.1.12
   Compiling tinyvec v1.5.1
   Compiling lock_api v0.4.5
   Compiling matrixmultiply v0.3.2
   Compiling ogg v0.8.0
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling memoffset v0.6.5
   Compiling rayon v1.5.1
   Compiling crossbeam-channel v0.5.1
   Compiling aho-corasick v0.7.18
   Compiling quote v1.0.10
   Compiling lewton v0.10.2
   Compiling getrandom v0.2.3
   Compiling num_cpus v1.13.0
   Compiling crossbeam-deque v0.8.1
   Compiling rand_core v0.6.3
   Compiling parking_lot v0.11.2
   Compiling pyo3 v0.15.1
   Compiling paste-impl v0.1.18
   Compiling rand_chacha v0.3.1
   Compiling rand_xoshiro v0.6.0
   Compiling rand v0.8.4
   Compiling num-complex v0.4.0
   Compiling paste v0.1.18
   Compiling regex v1.5.4
   Compiling primal-check v0.3.1
   Compiling transpose v0.2.1
   Compiling rustfft v6.0.1
   Compiling pyo3-macros-backend v0.15.1
   Compiling hdf5-sys v0.8.1
error: failed to run custom build command for `hdf5-sys v0.8.1`

Caused by:
  process didn't exit successfully: `/home/tangzixing/data/deeplearning/program/audio/DeepFilterNet/target/debug/build/hdf5-sys-4c8472666dcac2f7/build-script-build` (exit status: 101)
  --- stdout
  Attempting to find HDF5 via pkg-config...
  cargo:rerun-if-env-changed=HDF5_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=HDF5_STATIC
  cargo:rerun-if-env-changed=HDF5_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'Unable to locate HDF5 root directory and/or headers.', /home/tangzixing/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/hdf5-sys-0.8.1/build.rs:548:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by Rikorose** [comment]
You are still missing the HDF5 headers. Did you install them via `apt-get install libhdf5-dev` if you are on ubuntu?

**Comment by Tim5Tang** [comment]
thanks
cargo build pass.
the reason is that i install the hdf5 by the source code.

**Comment by wenbozhang** [comment]
> You are still missing the HDF5 headers. Did you install them via `apt-get install libhdf5-dev` if you are on ubuntu?
What could I do on Windows 11 system?  THANKS A LOT.
