### ISSUE TITLE
Can't get DeepFilterNet to work on Ubuntu 23.04

### ISSUE THREAD

**Issue by marcjohnen** [Rikorose/DeepFilterNet#328]
Hello everyone,

I have a Ryzen 9 7950x CPU so I downloaded https://github.com/Rikorose/DeepFilterNet/releases/download/v0.4.0/libdeep_filter_ladspa-v0.4.0-aarch64-unknown-linux-gnu.so
and copied it to /home/marc/.ladspa/libdeep_filter_ladspa.so
I copy the config https://github.com/Rikorose/DeepFilterNet/blob/main/ladspa/filter-chain-configs/deepfilter-mono-source.conf to /home/marc/.config/pipewire/filter-chain.conf.d/deepfilter-mono-source.conf
The only thing I change in the config is setting `plugin = /home/marc/.ladspa/libdeep_filter_ladspa.so`

I get the following errors:
```marc@me:~$ sudo pipewire -c deepfilter-mono-source.conf
[W][00502.886978] pw.conf      | [          conf.c:  939 try_load_conf()] can't load config deepfilter-mono-source.conf: No such file or directory
```
so I'm thinking maybe provide the absolute path and get this error:
```marc@me:~$ sudo pipewire -c /home/marc/.config/pipewire/filter-chain.conf.d/deepfilter-mono-source.conf
[E][00564.708193] default      | [ ladspa_plugin.c:  272 load_ladspa_plugin()] failed to load plugin '/home/marc/.ladspa/libdeep_filter_ladspa.so': No such file or directory
[E][00564.708229] mod.filter-chain | [module-filter-ch: 2371 pipewire__module_init()] can't load graph: No such file or directory
[E][00564.708335] pw.conf      | [          conf.c:  594 load_module()] 0x558ac28b6de0: could not load mandatory module "libpipewire-module-filter-chain": No such file or directory
[E][00564.708371] default      | [      pipewire.c:  125 main()] failed to create context: No such file or directory
```
I've been googling and reading a lot and still am clueless on how to make it work.

**Comment by marcjohnen** [comment]
So it looks like I used the wrong binary. When using libdeep_filter_ladspa-v0.4.0-x86_64-unknown-linux-gnu.so I get the following error though:
`marc@gandalf-the-white:~$ pipewire -c /home/marc/.config/pipewire/filter-chain.conf.d/deepfilter-mono-source.conf
[E][01221.959164] pw.core      | [          core.c:  382 core_new()] 0x56306f8ef610: can't find protocol 'PipeWire:Protocol:Native': Operation not supported
[E][01221.959206] mod.filter-chain | [module-filter-ch: 2387 pipewire__module_init()] can't connect: Operation not supported
[E][01221.959447] pw.conf      | [          conf.c:  594 load_module()] 0x56306f8d6ed0: could not load mandatory module "libpipewire-module-filter-chain": Operation not supported
[E][01221.959486] default      | [      pipewire.c:  125 main()] failed to create context: Operation not supported
`

**Comment by marcjohnen** [comment]
So to make it work in Ubuntu 23.04 these lines (or one of them) are missing
`    {   name = libpipewire-module-protocol-native }
    {   name = libpipewire-module-client-node }
    {   name = libpipewire-module-adapter }`

before { name = libpipewire-module-filter-chain

**Comment by xquilt** [comment]
In my case, the error message was confined to `can't load config deepfilter-mono-source.conf: No such file or directory`, which was because of the old version of `pipe wire` at `Ubuntu Jammy` official repos, and thus I had to build & install from [source](https://pipewire.org/) to load this config.
'm not sure if the old version of Pipewire had a different convention, but I was frustrated enough and wasn't gonna take time to sift through the docks.
