### ISSUE TITLE
Question about Near-Ultrasound Inaudible audio

### ISSUE THREAD

**Issue by jenskastensson** [Rikorose/DeepFilterNet#341]
The paper below explores a new attack class that attacks a mobile or smart-speaker microphone, Near-Ultrasound Inaudible Trojan (NUIT).
Can DeepFilterNet protect against attacks of this type?
 https://www.usenix.org/system/files/sec23fall-prepub-261-xia-qi.pdf

**Comment by Rikorose** [comment]
This sounds interesting. It would be interesting to try it out. But I guess since the attack also sounds like speech, DeepFilterNet may not suppress it.
