### ISSUE TITLE
[LADSPA] Are the defaults any good?

### ISSUE THREAD

**Issue by ManuLinares** [Rikorose/DeepFilterNet#349]
Issue: When trying to use LADSPA plugin on Ardour7, the defaults don't seem to be working fine.

I hear Garbled voice, no real noise filtering.
Defaults are:
![image](https://github.com/Rikorose/DeepFilterNet/assets/3720020/0d1f0e17-d97d-4a60-95ea-18d4fc52264e)

I'm using arch, ardour7, pipewire, and a buffer size of 1024.

edit: Lowering MaxERB and MaxDF to ~20db seems to work fine.

**Comment by Rikorose** [comment]
@ManuLinares I fixed a bug in the LADSPA version. Could try out version 0.5.1?

**Comment by ManuLinares** [comment]
> @ManuLinares I fixed a bug in the LADSPA version. Could try out version 0.5.1?

Working fine, thanks.
