### ISSUE TITLE
config.ini for reproducing results

### ISSUE THREAD

**Issue by rohithmars** [Rikorose/DeepFilterNet#35]
Hi,

Is it possible to provide a config.ini to reproduce the results in the paper?

Is the pre-trained model's config.ini same as the one used to get the results in the paper?

**Comment by Rikorose** [comment]
Yes, indeed. You can e.g. reproduce the results in table 1 using the pretrained weights and the corresponding config via test_voicebank_demand.py

**Comment by rohithmars** [comment]
Thanks for the reply.

Yes, I can get the scores that you have reported in Table 1 using the pre-trained model and its config file.
