### ISSUE TITLE
Guidance on wasm-pack Integration for DeepFilterNet

### ISSUE THREAD

**Issue by peili** [Rikorose/DeepFilterNet#350]
I am currently exploring the possibility of compiling the DeepFilterNet codebase into WebAssembly using wasm-pack for local execution within the browser. Given the complexity of the codebase, I would appreciate any guidance.

How can we handle the dependencies such as jemallocator, ndarray, and tract in the WebAssembly environment? Are there any known compatibility issues or workarounds that we should be aware of?

**Comment by grazder** [comment]
@peili Hello! I'm also interested in providing DeepFilterNet into web. Do you have any progress on this?
