### ISSUE TITLE
converting a 48khz wav file : killed out of nowhere

### ISSUE THREAD

**Issue by otyugh** [Rikorose/DeepFilterNet#351]
Hey, I wonder if this is a bug or something I'm missing ?

```
$ ./deepFilter '/home/implijer/Bureau/a.wav' --output-dir /home/implijer/Bureau/ -d
2023-06-07 13:25:41 | INFO     | df.logger:init_logger:44 | Running on torch 2.0.1+cpu
2023-06-07 13:25:41 | INFO     | df.logger:init_logger:45 | Running on host pc
fatal: not a git repository (or any of the parent directories): .git
2023-06-07 13:25:41 | INFO     | df.logger:init_logger:67 | Loading model settings of DeepFilterNet3
2023-06-07 13:25:41 | INFO     | df.enhance:init_df:142 | Using DeepFilterNet3 model at /home/implijer/.cache/DeepFilterNet/DeepFilterNet3
2023-06-07 13:25:41 | INFO     | df.model:init_model:21 | Initializing model `deepfilternet3`
2023-06-07 13:25:42 | INFO     | df.checkpoint:read_cp:76 | Found checkpoint /home/implijer/.cache/DeepFilterNet/DeepFilterNet3/checkpoints/model_120.ckpt.best with epoch 120
2023-06-07 13:25:42 | DEBUG    | df.enhance:init_df:169 | Loaded checkpoint from epoch 120
2023-06-07 13:25:42 | INFO     | df.enhance:init_df:175 | Running on device cpu
2023-06-07 13:25:42 | INFO     | df.enhance:init_df:176 | Model loaded
Killed
```

I created the wav file using 
```ffmpeg -i origin.mp3 -b:a 48k a.wav```
I installed deepFilter using pipe (DeepFilterNet 0.5.0)

**Comment by Rikorose** [comment]
How large is the audio? I guess you ran out of memory.

**Comment by otyugh** [comment]
It is 170Mo, mhhh. Oh yeah, I had 2Go free ram and it's shrinking. I'll add swap and see. Thanks !

**Comment by Rikorose** [comment]
You should be able to process the, if you use the rust binary

**Comment by otyugh** [comment]
Rust binary ? I'll try looking for that, since adding some dusty 4Go RAM didn't do the trick >_< ( if I wasn't on SSD I'd just make huge swap !)

**Comment by Rikorose** [comment]
You can find the binary at the release page:
https://github.com/Rikorose/DeepFilterNet/releases/tag/v0.5.0

**Comment by otyugh** [comment]
Hey, sorry I'm so slow at following suit.
```
./deep-filter-0.5.0-x86_64-unknown-linux-musl './file.wav' 
Illegal instruction
```

Any idea why it'd do that ?

**Comment by Rikorose** [comment]
What OS are you using? If you are using Linux please provide:
```bash
uname -a
lscpu
```

**Comment by Rikorose** [comment]
By the way, could you try [this build](https://github.com/Rikorose/DeepFilterNet/files/11815399/deep-filter-logging.zip) and run it with
```bash
./deep-filter -vvvvv './file.wav' 
```
and maybe upload the logs as text file

**Comment by otyugh** [comment]
$./deep-filter -vvvvv './file.wav' 
```
./deep-filter: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./deep-filter)
./deep-filter: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./deep-filter)
./deep-filter: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./deep-filter)
./deep-filter: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./deep-filter)
```

Does it means an obsolete libc version ?
$file /lib/x86_64-linux-gnu/libc.so.6
```
/lib/x86_64-linux-gnu/libc.so.6: symbolic link to libc-2.31.so
```

**Comment by Rikorose** [comment]
Ah ok, let me build a linux-musl build so that it bundles the correct libc version.

**Comment by Rikorose** [comment]
Here is a new musl build: [deep-filter-logging-musl.zip](https://github.com/Rikorose/DeepFilterNet/files/11816528/deep-filter-logging-musl.zip)

Since the log file may get quite big run this command:
```bash
deep-filter assets/noisy_snr0.wav -o /tmp -vvvvvv 2>&1 | zip log.zip -
```

Thanks for your help!

**Comment by otyugh** [comment]
It worked with your binary !
500Mo file tho ?! I'll be a bit painful for my ADSL connexion, but let me show a token of appreciation here ^^'
https://drop.chapril.org/download/938b5a48e5442986/#ROwUCvDASw2BhL0NV7mpZw

**Comment by Rikorose** [comment]
If it worked good! I was expecting it to fail (so that the output is not as big).

**Comment by otyugh** [comment]
Thanks again :)

**Comment by otyugh** [comment]
It worked too, albeit with this error message at the start

> [libDF/src/bin/enhance_wav.rs:82] &tract_level = Error

**Comment by Rikorose** [comment]
Ah perfect, that's just a debug message, that I forgot to remove

**Comment by ashu5644** [comment]
Hi @Rikorose,@otyugh. I want to use deep-filter for 2.5 hrs long audio file. Python code is giving out-of-memory error. Would binary method work for long file as well ? Can you guide me through installation steps of 'deep-filter-0.5.3-x86_64-unknown-linux-musl' binary on ubuntu20.04 i.e what commands needs to be run for installation ?

**Comment by otyugh** [comment]
It's just a binary. Download it, set it executable, and just give the file.wav path to it. It'll do it's magic.
Latest actual version can be downloaded here : https://github.com/Rikorose/DeepFilterNet/releases/tag/v0.5.3

**Comment by ashu5644** [comment]
Thanks @otyugh. Binary execution works fine. But still it looks to be taking longer for ~2hr audio file. I waited for 10 mins, but was still in progress. I also checked `nvidia-smi` output. It seems to be not using gpu. Is it expected behaviour or can I provide some argument for running it on gpu? I am expecting latency <5 mins for ~2hr audio file. @otyugh , @Rikorose
