### ISSUE TITLE
How to use the project in a Python app? 

### ISSUE THREAD

**Issue by rickyplc** [Rikorose/DeepFilterNet#352]
Hello, Maintainers of DeepFilterNet

I am reaching out to request some assistance regarding the installation and utilization of your DeepFilterNet framework in Python. I've been trying to follow the instructions in your README documentation but have found the process quite complex.

Even after performing the pip installation of the package and attempting to import the deepfilternet library in my Python script, I continue to face errors. I believe the core issue lies in the Python import, as the error message I receive is "Import 'df' could not be resolved". I have verified that the package is installed in my Python environment, but the import issue persists.

Could you please provide a step-by-step tutorial or clearer instructions regarding:

- How to install the DeepFilterNet Python package correctly, including any necessary dependencies?
- How to import and use the DeepFilterNet package in a Python script, using the correct module name(s) to enhance audio?

I also wanted to suggest that these instructions might be an excellent addition to your README file. Having a more straightforward, detailed guide would undoubtedly aid users like myself who are interested in your project but struggle with the initial setup.

### My Code
```bash
pip install deepfilternet
```

```python
from df import enhance, init_df

model, df_state, _ = init_df()


enhance(model, df_state, audio_file)

```

**Comment by Rikorose** [comment]
Installation is described here: https://github.com/Rikorose/DeepFilterNet#deepfilternet-python-pypi
```bash
# Install cpu/cuda pytorch (>=1.9) dependency from pytorch.org, e.g.:
pip install torch torchaudio -f https://download.pytorch.org/whl/cpu/torch_stable.html
# Install DeepFilterNet
pip install deepfilternet
```

Your code is correct. I just tested the installation procedure in a new environment again and run your code. Works for me. If you have any issues I need a better description of what you did and what error you got.

**Comment by rickyplc** [comment]
Thank you for the fast response, I will try those steps again.
