### ISSUE TITLE
Question on package

### ISSUE THREAD

**Issue by rohithmars** [Rikorose/DeepFilterNet#37]
Hi,

I found a case that even if I remove a file such as loss.py from the project, the train.py still runs. 

How is this possible? Maybe I am overlooking something.

Is it possible to edit loss.py ? Currently when I edit loss.py I can't see any changes happening. If I move loss.py out of df folder also, train.py does not throw any error.

**Comment by Rikorose** [comment]
You probably installed DeepFilterNet globally in your env. Use `pip remove deepfilternet` to remove the package and use the development version in the repo.
There are multiple options to work locally (e.g., set PYTHONPATH, install in editable mode, reinstall after each modification).
