### ISSUE TITLE
Code seems to differ slightly from the paper?

### ISSUE THREAD

**Issue by mralgos** [Rikorose/DeepFilterNet#379]
Hello, I was reading the first DeepFilterNet paper (v1) and am I wrong or the signal flow showed in Fig. 2 (https://arxiv.org/pdf/2110.05588.pdf) is not exactly what happens in the code?

For example the first Conv rectangle in DFNet is implemented in the Encoder (https://github.com/Rikorose/DeepFilterNet/blob/f96e8366f222776bcb31d0725bdbacc814220412/DeepFilterNet/df/deepfilternet.py#L124). 
Similarly, the output of the second Conv rectangle seems to be fed into the 2xGGRU rectangle but the forward pass of DfDecoder does something different (https://github.com/Rikorose/DeepFilterNet/blob/f96e8366f222776bcb31d0725bdbacc814220412/DeepFilterNet/df/deepfilternet.py#L214). Am I looking at the wrong code?

Thank you

**Comment by Rikorose** [comment]
Hi, this was reported before. The figure in the paper is not 100% correct. Thus, using this code directly is of course the best option for reproducing the results.

**Comment by mralgos** [comment]
Thank you. I’m closing the issue.
