### ISSUE TITLE
question about dataloader (dataset.rs) in libDF

### ISSUE THREAD

**Issue by iPwnXX** [Rikorose/DeepFilterNet#383]
im training dfn to remove a certain type of noise that i collected and built in the training noise set.  
I located the codes function for on-the-fly snr mixing, inside the libDF/src/dataset.rs, and i found that:
 in `load_aug_speech()`, a speech slice is cutted at random starting position from a picked sample, while the noise slice (`load_aug_noise`) is cutted from the beginning: ` ns.slice_axis_inplace(Axis(1), Slice::from(..self.max_samples));`. 
Is this reasonable?  suppose i prepared a list of noise wav files, some of them are long audios, and they had not been cut into short slices. then when going through this mixing procedure, only the beginning part of the noise wave have chance to be used for training.

**Comment by iPwnXX** [comment]
another one: the noise mixing randomly picked 1~5 noise examples to increase variability, and this has been hard coded into the `dataset.rs`.  However, we want to adapt the dfn to reduce a certain type of noise (wind noise for e.g.) so it's better to only mix one noise at a time. can it be updated to let "the number of noises to be mixed" be a parameter in the config.ini, so that the user can modify accordingly.

**Comment by Rikorose** [comment]
Yes, patches are welcome
