### ISSUE TITLE
purpose of the local snr

### ISSUE THREAD

**Issue by iPwnXX** [Rikorose/DeepFilterNet#385]
from my understanding of the lsnr codes, there are two relevant parts: 
- in model forward, the encoder predict a lsnr value from the enc embedding; 
- and in loss module, the ground truth lsnr is calcuated from the (clean, noise), then the lsnr loss is given by the mse of the predicted lsnr and the gt_lsnr.    
 
Im confused about the purpose of doing this: what's the meaning by predicting a correct lsnr value? ( and it's not even a local snr, since "the local SNR for frequencies below f_DF" ,which is mentioned in DFN paper 1, is not set / None by default. I suppose the only difference is that it clamp the min/max snr to a given range).

**Comment by Rikorose** [comment]
Its a frame-wise SNR estimate which could be used for any downstream task. I use it e.g. to disable both decoders if no speech is detected (i.e. SNR<=-15dB).

**Comment by wslbeck** [comment]
I'm also a bit confused about this, does it make the enhanced performance better?

**Comment by wslbeck** [comment]
I'm also a bit confused about this, does it make the enhanced performance better? And, can you tell me what the 'lsnr_droput' parameter does in the deepfilternet3 code?

**Comment by iPwnXX** [comment]
> 这个就是相当于做后处理，如果信噪比特别低，滤波器肯定只能抑制一部分噪声，但是通过snr估计，可以知道在只有噪声的时候，直接将音频置零。膜拜一下作者。

'which part of codes is for what you mentioned: set audio to zero if it's in low snr?'

**Comment by shenxiaozheng** [comment]
我的认为是这样的，如果是纯粹的噪声段，通过snr的估计，loss函数特别大，这样去训练使得gain特别小，接近于零。

**Comment by zxj329** [comment]
> 我的认为是这样的，如果是纯粹的噪声段，通过snr的估计，loss函数特别大，这样去训练使得gain特别小，接近于零。
那如果在测试阶段，会不会存在小于-15db的时候，语音也被置于0呢
