### ISSUE TITLE
clean speech is suppressed totally with df3 model, while df2 model is ok

### ISSUE THREAD

**Issue by flytair** [Rikorose/DeepFilterNet#389]
hi,
thanks for your amazing work, and you are so nice to open source your work.
when i compare the performance of your released pre-trained df2 and df3 model, i find sometimes, the clean speech(high snr) is suppressed totally by df3, it seems df3 models treats it as interference, while the df2 model works normally. please refer to the plot below:
![image](https://github.com/Rikorose/DeepFilterNet/assets/30205746/e75b7b57-972d-4c8c-8cdb-e9501f75cef1)

the noisy, output of df2 and df3 model
[badcase.zip](https://github.com/Rikorose/DeepFilterNet/files/12036139/badcase.zip)

i wander what is the cause of the different performance, is it caused by the architecture difference between df2 and df3 or different training set, df3 training set includes speech interference as noise?

**Comment by lnicola** [comment]
@flytair I think you filed this twice by mistake, you might want to close this issue in favor of #388.

**Comment by flytair** [comment]
duplicated with #388
