### ISSUE TITLE
RuntimeError: Pin memory thread exited unexpectedly and RuntimeError: DF dataloader error: ThreadJoinError("Any { .. }")

### ISSUE THREAD

**Issue by Cagemoney** [Rikorose/DeepFilterNet#393]
hello, I encountered some problems in the process of reproducing DeepFilterNet 2.
I configure the training environment according to README.md.

1、when the pin memory was set to true,  it will raise error in 52 epoch, details as follows：
thread 'DataLoader Worker 7' panicked at 'assertion failed: k <= self.len()', /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/slice/mod.rs:3419:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error during worker shutdownException in thread PinMemoryLoop:
![pip_memory](https://github.com/Rikorose/DeepFilterNet/assets/61931515/2618de73-5db2-44cf-82f3-ae4fa14c1760)

2、when the pin memory was set to false,  it also raise error in 52 epoch, details as follows：
thread 'DataLoader Worker 5' panicked at 'assertion failed: k <= self.len()', /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/slice/mod.rs:3419:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error during worker shutdown2023-07-19 15:28:12 | ERROR    | DF | An error has been caught in function '<module>', process 'MainProcess' (3088919), thread 'MainThread' (140374050034880):
![thread](https://github.com/Rikorose/DeepFilterNet/assets/61931515/28c5ed21-7b9d-4edb-b044-5fc5ea0f6e67)

so, can you provide your ideas or solutions? thank you!

**Comment by Rikorose** [comment]
Could you run again with `--log-level=debug` or `--log-level=trace`?

Does this always happen in epoch 52? And before it works?

**Comment by Cagemoney** [comment]
Thank you for your quick reply.

I run the train.py with "--log-level=trace", but also raise the same error in epoch. two errors always happen in epoch 52.

When I remove the rir.hdf5 in the dataset.cfg , no error raised.  I'm not sure whether it is caused by the hdf5 file now, because it was not reported incorrectly in the first 51 epoch. Looking forward to your advice.

**Comment by Rikorose** [comment]
I know, adding more logs does not solve the error. But if you provide me the logs, I may solve the error..

**Comment by Cagemoney** [comment]
Thanks, I provide the train logs with --log-level=trace.
[train_trace.log](https://github.com/Rikorose/DeepFilterNet/files/12102698/train_trace.log)

**Comment by Rikorose** [comment]
Thanks for the logs. I could not find an error message like `thread 'DataLoader Worker 7' panicked at 'assertion failed: k <= self.len()', /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/slice/mod.rs:3419:9`
Do you still get this message?

Can you try this version which add some more logs?
[df_dataloader.zip](https://github.com/Rikorose/DeepFilterNet/files/12103605/df_dataloader.zip)

**Comment by Cagemoney** [comment]
I run this project on linux, and the terminal will get this error. I will try your suggestion and keep in touch. Thanks!

**Comment by QQQQQQQQY** [comment]
> Thank you for your quick reply.
> 
> I run the train.py with "--log-level=trace", but also raise the same error in epoch. two errors always happen in epoch 52.
> 
> When I remove the rir.hdf5 in the dataset.cfg , no error raised. I'm not sure whether it is caused by the hdf5 file now, because it was not reported incorrectly in the first 51 epoch. Looking forward to your advice.

Hi, I have the same problem as you. May I ask how you solved it? Looking forward to your reply.
