### ISSUE TITLE
How to balance the trade-off between signal-to-noise ratio and speech distortion during training.

### ISSUE THREAD

**Issue by shenxiaozheng** [Rikorose/DeepFilterNet#396]
In my training process, I found that to achieve better noise suppression performance, it is beneficial to simulate some extreme low signal-to-noise ratio (SNR) data and include them in the training, such as SNR of -100. On the other hand, if the goal is to minimize speech distortion and focus on high SNR speech signals, adding more high SNR speech data, and even clean speech data during training can be helpful. Therefore, it is related to the characteristics of the test dataset. Do you have any experimental findings or conclusions to share on this matter?

**Comment by Rikorose** [comment]
Ideally, a large enough model with a high variety of input SNRs should perform well for low and high SNRs. Practically, you can try to find a trade-off by providing different input distribution as you described. I dont have any findings here. If you have some results, feel free to share here!
