### ISSUE TITLE
PyTorchDataLoader's source code or documentation.

### ISSUE THREAD

**Issue by shenxiaozheng** [Rikorose/DeepFilterNet#397]
During my experimentation, I found that PyTorchDataLoader is used for feature extraction, but mainly as compiled library files. Could you please share the source code or documentation for PyTorchDataLoader? This would be helpful for optimizing and understanding the feature extraction process.

**Comment by Rikorose** [comment]
You can find the source code here: https://github.com/Rikorose/DeepFilterNet/tree/main/pyDF-data and here: https://github.com/Rikorose/DeepFilterNet/blob/main/libDF/src/dataloader.rs
