### ISSUE TITLE
Add python 3.11 support

### ISSUE THREAD

**Issue by zh-plus** [Rikorose/DeepFilterNet#399]
Fantastic project! The noise suppression is fast and excellent. However, it appears that the published packages from [PYPI](https://pypi.org/project/deepfilterlib/#files) only support Python 3.8, 3.9, and 3.10. Are there any plans to release a version compatible with Python 3.11?

**Comment by Rikorose** [comment]
I added python 3.11 to the CI pipeline. So it should be included in the next release.

**Comment by zh-plus** [comment]
Thank you!
