### ISSUE TITLE
ModuleNotFoundError: No module named 'libdf'

### ISSUE THREAD

**Issue by NewEricWang** [Rikorose/DeepFilterNet#40]
"from libdf import DF" in DeepFilterNet/df/checkpoint.py

I change it to "from libDF import DF" and setup correct package path. But error is still.

**Comment by Rikorose** [comment]
Then you didn't install [deepfilterlib](https://pypi.org/project/deepfilterlib/). Please follow the instructions in the readme.

**Comment by NewEricWang** [comment]
Thanks!
