### ISSUE TITLE
`pad_spec` and `pad_feat` in DF3

### ISSUE THREAD

**Issue by grazder** [Rikorose/DeepFilterNet#402]
Hello! I'm looking at padding right now and it looks like it should be `pad_spec` instead of `pad_feat`. Because they are both in the constructor and `pad_spec` is not used anywhere.

https://github.com/Rikorose/DeepFilterNet/blob/7087df6b95eaebd69255bbb5f7932cdc3f5bc037/DeepFilterNet/df/deepfilternet3.py#L410

Also, could you describe the logic with those paddings, `df_lookahead` and `conv_lookahead`? Because it seems to work for input with `T > 1`, but if we use `T = 1` it will break. And with this padding, the first two samples on T will be forgotten.

**Comment by Rikorose** [comment]
Theoretically you could have a different lookahead for the DNN (conv_lookahead) and for deep filtering (df_lookahead). Practically, this is usually the same. I did not test different lookaheads within the real-time rust version.
What do you mean with `T=1`? The spectrogram only has 1 time step?

**Comment by grazder** [comment]
like yes, if we would put only one time-frame into model

I'm looking into the real-time rust version. Did I understand correctly that we always put multiple frames (current and previous multiple from buffer) in the encoder to provide context?

**Comment by Rikorose** [comment]
Yes, only providing one time frame does not really make sense, the rnn layers need some context for good noise reduction.

Also if the algorithm requires some lookahead `l`, you need `l+1` frames until it can produce the first output frame.

**Comment by grazder** [comment]
understood thanks

**Comment by Rikorose** [comment]
The padding ensures the correct alignment for the lookahead.

**Comment by grazder** [comment]
It looks like `self.pad_spec` is not being used in the code

**Comment by grazder** [comment]
@Rikorose 

> Yes, only providing one time frame does not really make sense, the rnn layers need some context for good noise reduction.

https://github.com/Rikorose/DeepFilterNet/blob/df690ffa0fd156a2df96e043a6cbf694fdba7e22/libDF/src/tract.rs#L454

I see here that erb_features with `T=1` go into encoder. Is it true? And rnn here see only one frame.

https://github.com/Rikorose/DeepFilterNet/blob/df690ffa0fd156a2df96e043a6cbf694fdba7e22/libDF/src/tract.rs#L420

Or am I missing something... I will be very glad for your help

**Comment by Rikorose** [comment]
This is a real time implementation. The DNN models store the state internally.

**Comment by grazder** [comment]
Could you show where this is happening?

**Comment by Rikorose** [comment]
Within tract

**Comment by grazder** [comment]
@Rikorose I have researched this moment and saw this issue - https://github.com/sonos/tract/issues/496

Did I understand correctly that all convolutions and gru are wrapped in PulsedModel? And for each block, we have some kind of running buffer?
