### ISSUE TITLE
Checkpoint quantization

### ISSUE THREAD

**Issue by anasvaf** [Rikorose/DeepFilterNet#408]
Hello,

Has anyone tried to quantize the weights of the model, or even the full model to INT8 in order to check its performance?
I am doing it as follows (I noticed significant degradation in performance):
```
# Convert the state dictionary to int8
quantized_state_dict = {}
for key, value in quantized_model.state_dict().items():
    print(key)
    if key == 'enc.lsnr_fc.0._packed_params.dtype' or key == 'enc.lsnr_fc.0._packed_params._packed_params'\
        or key == 'df_dec.df_fc_a.0._packed_params.dtype' or key == 'df_dec.df_fc_a.0._packed_params._packed_params':
        continue
    if key.endswith('.weight') or key.endswith('.weight_ih_l0') or key.endswith('.weight_hh_l0')\
        or key.endswith('.weight_ih_l1') or key.endswith('.weight_hh_l1'):
        quantized_state_dict[key] = value.to(torch.int8)
    else:
        quantized_state_dict[key] = value.to(torch.int32)
```

It looks like it cannot denoise an audio clip anymore. It just scales down the amplitude of the noisy waveform, as all the weights are 0. I have also tried with qint8 but I get errors about unsupported ops.

**Comment by shenxiaozheng** [comment]
模型里面包括gru层，这是非常核心的一部分，int8量化gru不是一个很好的选择。
