### ISSUE TITLE
v0.5.4 - Version ValueError: Value 'EMB_GRU_SKIP_ENC' not found in config (defaults not allowed).

### ISSUE THREAD

**Issue by Sharrnah** [Rikorose/DeepFilterNet#421]
Getting this error with v0.5.4.

```
Traceback (most recent call last):
  # ...
  File "df\enhance.py", line 159, in init_df
    p = ModelParams()
  File "df\model.py", line 12, in __init__
    self.__params = getattr(import_module("df." + self.__model), "ModelParams")()
  File "df\deepfilternet3.py", line 55, in __init__
    self.emb_gru_skip_enc: str = config(
  File "df\config.py", line 136, in __call__
    raise ValueError(f"Value '{option}' not found in config (defaults not allowed).")
ValueError: Value 'EMB_GRU_SKIP_ENC' not found in config (defaults not allowed).
```

Tried to delete the cached model in case the config.ini is missing something and its not downloading the new one automatically, but it downloaded the same and error still persists.

**Comment by zhenghaoyuan** [comment]
Same here. Do you find any solutions on this ?

**Comment by Sharrnah** [comment]
I just downgraded to v0.5.3 for the time being.

**Comment by paul-krug** [comment]
you have to set config_allow_defaults = True in the init_df() function:

from df import enhance, init_df
model, df_state, _ = init_df( config_allow_defaults = True )  # Load default model

**Comment by Sharrnah** [comment]
thanks. the example code should be updated in the readme then if this is intended behaviour.

**Comment by Rikorose** [comment]
I changed the default to True now, so this disappear.
