### ISSUE TITLE
Process small chunks of data for streaming application within Python

### ISSUE THREAD

**Issue by H-G-11** [Rikorose/DeepFilterNet#422]
Hi,

I am building a smart speaker where I will have to cancel the noise on small batches of incoming audio data (16KHz, mono-input, 500ms but later might be 20ms).

The noise cancellation will be running on a raspberry Pi or in the cloud.

I saw that cancelling input from the microphone can be used with LADSPA. Using it on the Pi [should work](https://forums.raspberrypi.com/viewtopic.php?t=46997) but I was wondering if there would be a way of having low-latency, low-RAM consumption noise cancellation on small chunks of data directly within Python. That way, we could have it running in the cloud - chunks are incoming very fast and we should not block the pipeline.

According to [this comment](https://github.com/Rikorose/DeepFilterNet/issues/261#issuecomment-1441458307), this is not feasible, but I wanted to double-check as I saw there were also ONNX models. [This comment](https://github.com/Rikorose/DeepFilterNet/issues/296#issuecomment-1523226078) suggests it is feasible to use in Python but need to adapt the `enhance.py` to use ONNX.

Is it the only way?

I know I'm being difficult here, thanks a lot for your time and hard-work for this library

**Comment by Rikorose** [comment]
The rust library is ment for low memory chunk-wise processing. There needs to be done a lot for a python streaming application, and it won't be low memory. This is not on the agenda.

**Comment by HeChengHui** [comment]
@Rikorose 
> The rust library is ment for low memory chunk-wise processing. There needs to be done a lot for a python streaming application, and it won't be low memory. This is not on the agenda.

After reading through issues related to a causal/streaming implementation, it seems like it is possible with V2 while someone is trying to do a torch implementation for V3. May i check how do i use V2 for causal use case?
