### ISSUE TITLE
How to use other models in Windows executable?

### ISSUE THREAD

**Issue by musicalman** [Rikorose/DeepFilterNet#426]
Hello,
When I first became aware of this repo, the Windows executable didn't yet exist, so I used deepfilternet through pip. Back then, deepfilternet2 was the latest model.

Now I am trying to use the deepfilternet.exe application. It works great for denoising speech, but I personally find the default model (I believe it is deepfilternet 3), a bit too aggressive.

I downloaded deepfilternet2 models from here: https://github.com/Rikorose/DeepFilterNet/tree/main/models
I tried both of the tar.gz files on the page. When I tried using them in the executable, I got this error:
thread 'main' panicked at 'not yet implemented', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tract-hir-0.19.16\src\ops\array\reshape.rs:131:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I am also a bit confused by the files, since there are 2 tar.gz files for deepfilternet2 and 3, but none for the original deepfilternet, which I would also like to have handy in case I need it for some reason.

So yeah, I am lost and in need of advice. Thanks so much for any help you can provide!

**Comment by Rikorose** [comment]
The executable only supports deepfilternet3 models. deepfilternet2 is only included for legacy purpose and requires an old executable version.
