### ISSUE TITLE
I've made a torch reimplementation for both offline and streaming implementation. Would you be interested in accepting this contribution?

### ISSUE THREAD

**Issue by grazder** [Rikorose/DeepFilterNet#430]
Hello! I wrote a complete torch implementation without using rust or tract. I'm thinking about PR. So I decided to ask you, would you be interested in accepting this contribution? This may be more helpful for understanding the model because the rust/tract is difficult to understand  right now for average torch user.
Also my streaming implementation can be fully exported into a single ONNX model. This is useful, for example, for easier use for web inference.
I've made tests, that show equivalence with current code (or with not very old commit)

**Comment by Penguin168** [comment]
> Hello! I wrote a complete torch implementation without using rust or tract. I'm thinking about PR. So I decided to ask you, are you interested in this? This may be more helpful for understanding the model because the rust/tract is difficult to understand right now for average torch user. Also my streaming implementation can be fully exported into a single ONNX model. This is useful, for example, for easier use for web inference.

I'm very interesing in your implementation. I tried to implement in streaming way in pure C with onnx model, but the delay is too long, I'd like to know how you implemented the streaming algorithm.

**Comment by skyler14** [comment]
I'm very interested in this as well, you should submit a PR and see what they say. Have you tried running the standalone onnx with like onnxjs, and how big a footprint does the model leave?

**Comment by grazder** [comment]
Yeah, I've tried it using onnxruntime-web in web worker. It works fine. I didn't look at footprint, only on CPU usage. I can calculate it later

**Comment by skyler14** [comment]
Can you toss a link to the branch/commit you're looking at PRing, I'd love to take it for a spin

**Comment by grazder** [comment]
My code is currently in my private gitlab repository. I think I'll be able to share this soon.

**Comment by grazder** [comment]
So, I've created draft PR to show my changes. I'll be glad to hear your feedback.

**Comment by Penguin168** [comment]
I'm not sure if I've misunderstood, the main difference between 'Offline' and 'Streaming' as you mentioned is the ability to convert the entire model into ONNX format, rather than the difference in their applications, such as full audio processing and real-time applications (like internet calls), is it right?

**Comment by GreatDarrenSun** [comment]
Thanks grazder.Great Job!Have you tested the streaming mode performance on your phone's CPU? I tried it on Android today and found that the RTF is very large. Can the RTF be reduced by increasing hop_size?

**Comment by grazder** [comment]
I didn't tested it on phones, but soon i'm going to try it. I think, that changing hop_size can lead to quallity reducing.

**Comment by zeynepgulhanuslu** [comment]
Hi, 

Great work, thanks! I tried using an ONNX model with WebAssembly in a web browser. After 15 seconds, the sound became robotic. What do you think the problem might be here?

**Comment by grazder** [comment]
@zeynepgulhanuslu 

I got a robotic voice if the model did not work fast enough and the AudioWorklet did not have time to send audio samples in time. So it can be due to web implementation. Currently I have working demo with worklet + worker + ringbuffer setup. And It works fine on my mac. 
You can check model speed in your implementation. And if it's not, so it because of model quallity, but I didn't face it yet.

Also can you share details about your Web setup?

**Comment by zeynepgulhanuslu** [comment]
I actually attempted to use it within Jitsi-Meet as a replacement for the RNNoise module, and it takes 7 ms for inference on 480 samples. Perhaps I could use VAD (Voice Activity Detection) so that I don't have to run the model all the time. If you're interested, I can send the CPP code via email. Thank you for the detailed answer

**Comment by grazder** [comment]
Yeah, that would be great. Do you build wasm module using CPP?
7ms seems enough, because you have 10ms window to run model

**Comment by grazder** [comment]
@zeynepgulhanuslu I understood the problem. Jitsi if im not mistaken run wasm module inside AudioWorklet. So there you have only 128 / sampleRate * 1000 window (here is 2.6 ms). So 7ms is too long for it. Every time you run inference inside AudioWorklet `.process` function a lag is created. So because of delay sound can be robotic

**Comment by zeynepgulhanuslu** [comment]
@grazder thank you for your suggestions, I will examine different solutions as well. I thought jitsi meet takes 128 long sound and sends it to the process function when it is 480. Later when I tested it in python code and with wasm, I noticed that it process some frames in 15 ms. Maybe it could be related to this. Do you have any idea what can be done to speed up the model? 

`    /**
     * Process an audio frame, optionally denoising the input pcmFrame and returning the Voice Activity Detection score
     * for a raw Float32 PCM sample Array.
     * The size of the array must be of exactly 480 samples, this constraint comes from the rnnoise library.
     *
     * @param {Float32Array} pcmFrame - Array containing 32 bit PCM samples. Parameter is also used as output
     * when {@code shouldDenoise} is true.
     * @param {boolean} shouldDenoise - Should the denoised frame be returned in pcmFrame.
     * @returns {Float} Contains VAD score in the interval 0 - 1 i.e. 0.90 .
     */
    processAudioFrame(pcmFrame: Float32Array, shouldDenoise: Boolean = false): number {
        // Convert 32 bit Float PCM samples to 16 bit Float PCM samples as that's what rnnoise accepts as input
        for (let i = 0; i < RNNOISE_SAMPLE_LENGTH; i++) {
            this._wasmInterface.HEAPF32[this._wasmPcmInputF32Index + i] = pcmFrame[i] * SHIFT_16_BIT_NR;
        }

        // Use the same buffer for input/output, rnnoise supports this behavior
        const vadScore = this._wasmInterface._rnnoise_process_frame(
            this._context,
            this._wasmPcmInput,
            this._wasmPcmInput
        );

        // Rnnoise denoises the frame by default but we can avoid unnecessary operations if the calling
        // client doesn't use the denoised frame.
        if (shouldDenoise) {
            // Convert back to 32 bit PCM
            for (let i = 0; i < RNNOISE_SAMPLE_LENGTH; i++) {
                pcmFrame[i] = this._wasmInterface.HEAPF32[this._wasmPcmInputF32Index + i] / SHIFT_16_BIT_NR;
            }
        }

        return vadScore;
    }
`

**Comment by grazder** [comment]
I think you can remove normalization steps for model. I don't do it and it works fine. 
Also you can profile your solution in browser. I saw some lags because of garbage collector.

Also I use wasm-simd for ONNX inference and it works faster than wasm onnx (i don't build wasm module right now).
About model speed up: I've already said about Post-training static quantization or inference in fp16 (idk if it will work fine). Right now I don't have other ideas. May be I will try some things if it will be necessary for me

**Comment by dingchaoyue** [comment]
Thank you for your great work!

In the code [torch_df_offline.py], sample_rate is set to 48000,
and self.erb_indices = torch.tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5, 7, 7, 8, 10, 12, 13 , 15, 18, 20, 24, 28, 31, 37, 42, 50, 56, 67])

When sample_rate=16000, what should self.erb_indices be set to?

**Comment by walletiger** [comment]
> @Penguin168 The `Offline` model processes audio completely - we put the full audio spectrogram into the model. The `Streaming` model processes audio frame by frame. Only the streaming model can be exported to ONNX. And it can be used in real-time applications where the offline model cannot be used in this way. If we process one audio with both models separately, the result will be the same.

thanks for the excellent job ,  i test the  PR BRANCH "Git commit: 5224ed4, branch: torchDF-changes" , both offline and streaming modes, and found that the quality of the voice processed by the offline version was consistent with the official testing procedure, while the audio quality loss returned by the streaming mode was more severe (start from about 6s, 0~6s was ok). I don't know what caused it. Could you help me? Thank you!
offline infer log:
 python3 torch_df_offline.py  --input-folder ./data/in/ --output-folder ./data/out/
/workspace/aec/DeepFilterNet/DeepFilterNet/df/io.py:9: UserWarning: `torchaudio.backend.common.AudioMetaData` has been moved to `torchaudio.AudioMetaData`. Please update the import path.
  from torchaudio.backend.common import AudioMetaData
2023-10-18 18:02:43 | INFO     | DF | Running on torch 2.1.0+cu121
2023-10-18 18:02:43 | INFO     | DF | Running on host hugo-home
2023-10-18 18:02:43 | INFO     | DF | Git commit: 5224ed4, branch: torchDF-changes
2023-10-18 18:02:43 | INFO     | DF | Loading model settings of DeepFilterNet3
2023-10-18 18:02:43 | INFO     | DF | Using DeepFilterNet3 model at /root/.cache/DeepFilterNet/DeepFilterNet3
2023-10-18 18:02:43 | INFO     | DF | Initializing model `deepfilternet3`
2023-10-18 18:02:43 | INFO     | DF | Found checkpoint /root/.cache/DeepFilterNet/DeepFilterNet3/checkpoints/model_120.ckpt.best with epoch 120
2023-10-18 18:02:43 | INFO     | DF | Running on device cuda:0
2023-10-18 18:02:43 | INFO     | DF | Model loaded
Reading audio from folder - ./data/in/
Found 1 audio in ./data/in/
Inferencing model to folder - ./data/out/...

streaming infer logs:
python3 torch_df_streaming.py  --audio-path ../linein_aec2.wav --output-path data/out/denoised_test_streaming22.wav
/workspace/aec/DeepFilterNet/DeepFilterNet/df/io.py:9: UserWarning: `torchaudio.backend.common.AudioMetaData` has been moved to `torchaudio.AudioMetaData`. Please update the import path.
  from torchaudio.backend.common import AudioMetaData
2023-10-18 17:49:47 | INFO     | DF | Running on torch 2.1.0+cu121
2023-10-18 17:49:47 | INFO     | DF | Running on host hugo-home
2023-10-18 17:49:47 | INFO     | DF | Git commit: 5224ed4, branch: torchDF-changes
2023-10-18 17:49:47 | INFO     | DF | Loading model settings of DeepFilterNet3
2023-10-18 17:49:47 | INFO     | DF | Using DeepFilterNet3 model at /root/.cache/DeepFilterNet/DeepFilterNet3
2023-10-18 17:49:47 | INFO     | DF | Initializing model `deepfilternet3`
2023-10-18 17:49:47 | INFO     | DF | Found checkpoint /root/.cache/DeepFilterNet/DeepFilterNet3/checkpoints/model_120.ckpt.best with epoch 120
2023-10-18 17:49:47 | INFO     | DF | Running on device cuda:0
2023-10-18 17:49:47 | INFO     | DF | Model loaded

**Comment by GreatDarrenSun** [comment]
> I didn't tested it on phones, but soon i'm going to try it. I think, that changing hop_size can lead to quallity reducing. I thought about trying quantization to reduce RTF and checkpoint size. But didn't tried it yet

Thank you for your reply. As far as I know, torch quantification is not very friendly. How is the progress of your model quantification?

**Comment by grazder** [comment]
@GreatDarrenSun I'm not currently working on this because the current latency suits my current needs. But maybe someday later I'll start

**Comment by walletiger** [comment]
> > @Penguin168 The `Offline` model processes audio completely - we put the full audio spectrogram into the model. The `Streaming` model processes audio frame by frame. Only the streaming model can be exported to ONNX. And it can be used in real-time applications where the offline model cannot be used in this way. If we process one audio with both models separately, the result will be the same.
> 
> thanks for the excellent job , i test the PR BRANCH "Git commit: [5224ed4](https://github.com/Rikorose/DeepFilterNet/commit/5224ed47e19b6b327c9f22df6c5a061e3c3f6d5f), branch: torchDF-changes" , both offline and streaming modes, and found that the quality of the voice processed by the offline version was consistent with the official testing procedure, while the audio quality loss returned by the streaming mode was more severe (start from about 6s, 0~6s was ok). I don't know what caused it. Could you help me? Thank you! offline infer log: python3 torch_df_offline.py --input-folder ./data/in/ --output-folder ./data/out/ /workspace/aec/DeepFilterNet/DeepFilterNet/df/io.py:9: UserWarning: `torchaudio.backend.common.AudioMetaData` has been moved to `torchaudio.AudioMetaData`. Please update the import path. from torchaudio.backend.common import AudioMetaData 2023-10-18 18:02:43 | INFO | DF | Running on torch 2.1.0+cu121 2023-10-18 18:02:43 | INFO | DF | Running on host hugo-home 2023-10-18 18:02:43 | INFO | DF | Git commit: [5224ed4](https://github.com/Rikorose/DeepFilterNet/commit/5224ed47e19b6b327c9f22df6c5a061e3c3f6d5f), branch: torchDF-changes 2023-10-18 18:02:43 | INFO | DF | Loading model settings of DeepFilterNet3 2023-10-18 18:02:43 | INFO | DF | Using DeepFilterNet3 model at /root/.cache/DeepFilterNet/DeepFilterNet3 2023-10-18 18:02:43 | INFO | DF | Initializing model `deepfilternet3` 2023-10-18 18:02:43 | INFO | DF | Found checkpoint /root/.cache/DeepFilterNet/DeepFilterNet3/checkpoints/model_120.ckpt.best with epoch 120 2023-10-18 18:02:43 | INFO | DF | Running on device cuda:0 2023-10-18 18:02:43 | INFO | DF | Model loaded Reading audio from folder - ./data/in/ Found 1 audio in ./data/in/ Inferencing model to folder - ./data/out/...
> 
> streaming infer logs: python3 torch_df_streaming.py --audio-path ../linein_aec2.wav --output-path data/out/denoised_test_streaming22.wav /workspace/aec/DeepFilterNet/DeepFilterNet/df/io.py:9: UserWarning: `torchaudio.backend.common.AudioMetaData` has been moved to `torchaudio.AudioMetaData`. Please update the import path. from torchaudio.backend.common import AudioMetaData 2023-10-18 17:49:47 | INFO | DF | Running on torch 2.1.0+cu121 2023-10-18 17:49:47 | INFO | DF | Running on host hugo-home 2023-10-18 17:49:47 | INFO | DF | Git commit: [5224ed4](https://github.com/Rikorose/DeepFilterNet/commit/5224ed47e19b6b327c9f22df6c5a061e3c3f6d5f), branch: torchDF-changes 2023-10-18 17:49:47 | INFO | DF | Loading model settings of DeepFilterNet3 2023-10-18 17:49:47 | INFO | DF | Using DeepFilterNet3 model at /root/.cache/DeepFilterNet/DeepFilterNet3 2023-10-18 17:49:47 | INFO | DF | Initializing model `deepfilternet3` 2023-10-18 17:49:47 | INFO | DF | Found checkpoint /root/.cache/DeepFilterNet/DeepFilterNet3/checkpoints/model_120.ckpt.best with epoch 120 2023-10-18 17:49:47 | INFO | DF | Running on device cuda:0 2023-10-18 17:49:47 | INFO | DF | Model loaded

it sounds slight bad when some states not update and the input sound be slilence .  continue update states fixed this.

**Comment by 308627993** [comment]
> Hello! I wrote a complete torch implementation without using rust or tract. I'm thinking about PR. So I decided to ask you, would you be interested in accepting this contribution? This may be more helpful for understanding the model because the rust/tract is difficult to understand right now for average torch user. Also my streaming implementation can be fully exported into a single ONNX model. This is useful, for example, for easier use for web inference. I've made tests, that show equivalence with current code (or with not very old commit)

hello, can you share me the streaming implementation, i am very insteresting , but i don't know how to do it, thank you very much, my email is : jiawanjiayuan@gmail.com

**Comment by 308627993** [comment]
hi, thanks a lot for your help!







---Original---
From: "Alexey ***@***.***&gt;
Date: Tue, Oct 31, 2023 16:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Rikorose/DeepFilterNet] I've made a torch reimplementation forboth offline and streaming implementation. Would you be interested inaccepting this contribution? (Issue #430)




 
@308627993
 
You can find it here - https://github.com/Rikorose/DeepFilterNet/blob/5224ed47e19b6b327c9f22df6c5a061e3c3f6d5f/torchDF/torch_df_streaming.py

**Comment by ZacharyYarostTechsmith** [comment]
@grazder Hey! Thank you for your work on this. It's really cool to see the torch reimplementation running!

I wanted to get your input on what I think is a bug with the streaming model.

If you listen to [this collection of samples](https://youtu.be/evHhZfnZOqA?si=auERhYPXRDRJEip9) there is some light chop in the `streaming` version that does not appear in the `offline` or normal DF3 output.

Do you have any thoughts on what might be causing it?

**Comment by grazder** [comment]
Well, you can try infer with `apply_all_stages=True` parameter (in init), so you will get output like in offline model. I bet problem here. It's made to reach full match with rust implementation

**Comment by ZacharyYarostTechsmith** [comment]
> Well, you can try infer with `apply_all_stages=True` parameter (in init), so you will get output like in offline model. I bet problem here. It's made to reach full match with rust implementation

I appreciate the reply! I just gave that a try but the output still retained the choppiness.

Does anything else come to mind that be might at play?

**Comment by grazder** [comment]
Can you send an audio please? I'll try to debug it tomorrow

**Comment by ZacharyYarostTechsmith** [comment]
> Can you send an audio please? I'll try to debug it tomorrow

Of course. Thanks for looking into it!

I've attached the original sample and the two denoised versions from my video.

[AudioSamples.zip](https://github.com/Rikorose/DeepFilterNet/files/13245571/AudioSamples.zip)

**Comment by grazder** [comment]
I found some shapes errors in my code. I'll try to fix it later. But about audio - my tests passing with that audio. So output on offline model and on streaming model are similar.

Also tried to inference it, seems like ok. I also updated code to enable `--always-apply-all-stages` activation

```
poetry run python torch_df_streaming.py --audio-path examples/Sample_original.wav --output-path examples/enhanced.wav --always-apply-all-stages
```

Output:
https://drive.google.com/file/d/1btlup55w3PiC2tMmV7apD1fUYXvCKfFE/view?usp=sharing

**Comment by ZacharyYarostTechsmith** [comment]
That seems to have done it! I applied the changes to my local branch without much success, but a fresh clone had everything working. Thank you.

I have one more possible bug report.

While testing the `streaming` ONNX model I've noticed that the `atten_lim_db` input doesn't seem to affect the output. An input of `0.0`, `50.0`, and `99.0` results in what sounds like identical audio. Do you see this behavior as well?

**Comment by grazder** [comment]
Well, It seems like it should work

https://github.com/grazder/DeepFilterNet/blob/1097015d53ced78fb234e7d7071a5dd4446e3952/torchDF/torch_df_streaming.py#L540

But I didn't play with it a lot, because it's not important for my case.
Try it on super noisy audio with `atten_lim_db = 0.01`

**Comment by ZacharyYarostTechsmith** [comment]
You were right, @grazder.

I had written my own sample code and must have set something incorrectly while testing the `atten_lim_db` input. I tried things out again and It seems to be working just fine. Thanks for the link to the code in question!

**Comment by 308627993** [comment]
Hello,about the RTF , streaming version and offline version, is so big difference:
I test the offline version RTF(0.053) (RUN&nbsp; python enhance.py test.wav) , and the streaming version RTF(0.68 ) ,&nbsp; why the streaming version RTF and offline version RTF value so big difference ?&nbsp; and is there any way to speed up the streaming version ?
thanks for your help, the streaming version got the same enhanced result as the offline version ,the only problem is that the speed is too slow .







---Original---
From: "Alexey ***@***.***&gt;
Date: Tue, Oct 31, 2023 16:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Rikorose/DeepFilterNet] I've made a torch reimplementation forboth offline and streaming implementation. Would you be interested inaccepting this contribution? (Issue #430)




 
@308627993
 
You can find it here - https://github.com/Rikorose/DeepFilterNet/blob/5224ed47e19b6b327c9f22df6c5a061e3c3f6d5f/torchDF/torch_df_streaming.py

**Comment by walletiger** [comment]
> Hello,about the RTF , streaming version and offline version, is so big difference: I test the offline version RTF(0.053) (RUN&nbsp; python enhance.py test.wav) , and the streaming version RTF(0.68 ) ,&nbsp; why the streaming version RTF and offline version RTF value so big difference ?&nbsp; and is there any way to speed up the streaming version ? thanks for your help, the streaming version got the same enhanced result as the offline version ,the only problem is that the speed is too slow .
> […](#)
> ---Original--- From: "Alexey ***@***.***&gt; Date: Tue, Oct 31, 2023 16:52 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [Rikorose/DeepFilterNet] I've made a torch reimplementation forboth offline and streaming implementation. Would you be interested inaccepting this contribution? (Issue #430) @308627993 You can find it here - https://github.com/Rikorose/DeepFilterNet/blob/5224ed47e19b6b327c9f22df6c5a061e3c3f6d5f/torchDF/torch_df_streaming.py — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;
i tried to calc stft and istft outside the onnx-model  , and then it's speed improved as fast as the official demo !

**Comment by 308627993** [comment]
thanks for your reply,&nbsp; i have separate stft and istft part outside the model, but i also split the model to 3 sub-model ( encoder，erb_dec and df_dec), maybe this split action caused the speed slow , i will test again.&nbsp; thanks !



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 21, 2023 21:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Rikorose/DeepFilterNet] I've made a torch reimplementation forboth offline and streaming implementation. Would you be interested inaccepting this contribution? (Issue #430)




  
Hello,about the RTF , streaming version and offline version, is so big difference: I test the offline version RTF(0.053) (RUN&nbsp; python enhance.py test.wav) , and the streaming version RTF(0.68 ) ,&nbsp; why the streaming version RTF and offline version RTF value so big difference ?&nbsp; and is there any way to speed up the streaming version ? thanks for your help, the streaming version got the same enhanced result as the offline version ,the only problem is that the speed is too slow .
 …
 ---Original--- From: "Alexey @.&gt; Date: Tue, Oct 31, 2023 16:52 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [Rikorose/DeepFilterNet] I've made a torch reimplementation forboth offline and streaming implementation. Would you be interested inaccepting this contribution? (Issue #430) @308627993 You can find it here - https://github.com/Rikorose/DeepFilterNet/blob/5224ed47e19b6b327c9f22df6c5a061e3c3f6d5f/torchDF/torch_df_streaming.py — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
 i tried to calc stft and istft outside the onnx-model  , and then it's speed improved as fast as the official demo !

**Comment by gozkil** [comment]
Great work. Do anyone have some basic code to share, showing the streaming version of torch-onnx running with microphone input?

**Comment by grazder** [comment]
@gozkil Hello! I have a couple of examples for the Web. I think I'll be able to share soon

**Comment by rodrigoGA** [comment]
A 16KHz streaming version would be really useful.

**Comment by AINoise** [comment]
> I actually attempted to use it within Jitsi-Meet as a replacement for the RNNoise module, and it takes 7 ms for inference on 480 samples. Perhaps I could use VAD (Voice Activity Detection) so that I don't have to run the model all the time. If you're interested, I can send the CPP code via email. Thank you for the detailed answer

Hi, my friend, can you send the cpp implement to my email?  This is my current trouble.  Thanks.

**Comment by zeynepgulhanuslu** [comment]
Hi, Can you send me your mail so that I can send you the code?

**Comment by AINoise** [comment]
> Hi, Can you send me a mail so that I can send you the code? You can find my address on my profile.

My email : reborn06080712@gmail.com , Thank you very much. You can find my address on my profile.

**Comment by melodyze-ai** [comment]
> Great Job!Have you tested the streaming mode performance on your phone's CPU? I tried it on Android today and found that the RTF is very large. Can the RTF be reduced by increasing hop_size?
@GreatDarrenSun could you please provide me some pointers as in how you implemented it on Android?

**Comment by rizwanishaq** [comment]
I have this error when I try to load the streaming task AttributeError: 'Encoder' object has no attribute 'df_conv0_ch'. Did you mean: 'df_conv0'?

**Comment by grazder** [comment]
https://github.com/grazder/DeepFilterNet/blob/1097015d53ced78fb234e7d7071a5dd4446e3952/DeepFilterNet/df/deepfilternet3.py#L120

It exists, please make sure that you've cloned everything right

**Comment by GreatDarrenSun** [comment]
> > Great Job!Have you tested the streaming mode performance on your phone's CPU? I tried it on Android today and found that the RTF is very large. Can the RTF be reduced by increasing hop_size?
> 
> @GreatDarrenSun could you please provide me some pointers as in how you implemented it on Android?
Sorry, I just saw the message. I tested it using pytorch, you can refer to this link：
https://pytorch.org/mobile/android/
