### ISSUE TITLE
Use model to enhance audios with sample rate 16Khz or 8 Khz

### ISSUE THREAD

**Issue by HiAlexa** [Rikorose/DeepFilterNet#432]
Can you suggest how can we use or change the model for audios with sample rate 16Khz or 8Khz ?
 i dont want to upsample the input to 48Khz. 
any help in this direction is much appreciated

**Comment by StuartIanNaylor** [comment]
Usually most soundcards will support 48Khz so you can just downsample auto with the plug devices

```
pcm.ladspa {
    type ladspa
    slave.pcm "plughw:3,0";
    path "/usr/lib/ladspa";
    plugins [{
        label deep_filter_mono
        input {
            control [ 100 ]
        }
    }]
}

pcm.deepfilter {
    type=plug
    slave = {
    pcm "ladspa"
    channels 1
    rate 48000}
}
```
If you put the ladspa in /usr/lib/ladspa then the plug device will auto resample even though the input is 48Khz

**Comment by rodrigoGA** [comment]
I'm also keenly interested in this. It's important for many streaming services and phone calls that typically use 16KHz or 8KHz. Direct enhancement at these rates would be incredibly useful.
