### ISSUE TITLE
Is DeepFilterNet able to perform the opposite task

### ISSUE THREAD

**Issue by Psarpei** [Rikorose/DeepFilterNet#435]
I am thinking about if DeepFilterNet is able to do the opposite task. So instead of isolating the speech, removing only the speech.
Is it in theory possible to do that by switching background with speech, or are there any restrictions from the models design, that this makes no sense ?

**Comment by lnicola** [comment]
I think you can subtract the speech from the input to get the noise.

**Comment by Exxi80** [comment]
> I think you can subtract the speech from the input to get the noise.

How? And is it possible to cut off all sounds except piano for example?

**Comment by lnicola** [comment]
> How?

Subtract the de-noised version from the original, sample by sample.

> And is it possible to cut off all sounds except piano for example?

That's something completely different, I'll let others answer.
