### ISSUE TITLE
Export model through ONNX

### ISSUE THREAD

**Issue by ooshyun** [Rikorose/DeepFilterNet#456]
Thanks for great work! However, I want to ask about supporting onnx export. When I try to export using script/export.py and `python DeepFilterNet/df/scripts/export.py -m DeepFilterNet3 --output-dir ./out --simplify export_dir`, it raises the error `RuntimeError: Unsupported value kind: Tensor` at `torch.jit.script` in export/export_impl. I am trying to figure out why, but if anyone resolves this, please advise me!

Thanks for reading!

**Comment by avramandrei** [comment]
@ooshyun I am encountering the same issue as you do. Have you managed to fix it?

**Comment by ooshyun** [comment]
Hi, I changed torch.jit.script to torch.jit.trace in export_impl function(df/script/sexport.py) as below,

```python
# df/script/sexport.py
# model = torch.jit.script(model, example_inputs=[tuple(a for a in inputs)]) # error part
model = torch.jit.trace(model, tuple(a for a in inputs))
```

It can resolve the issue, but I'm not sure it is correct way to get a result!
