### ISSUE TITLE
training_set.txt missing

### ISSUE THREAD

**Issue by enricguso** [Rikorose/DeepFilterNet#461]
Hello! Thanks for sharing this model, really cool. Is it possible that you add to the repo the .txt file that specifies which DNS4/5 files where used? In my opinion it's a bit misleading trying to replicate the training without it. Thank you!

**Comment by enricguso** [comment]
I ended up doing a speaker-based train/val/test separation of the DNS4 (DNS5 speakerphone track). Attaching the files here in case it is for use for anyone, i hope it's ok to do this. You should join `training_set_speech0x` into a single file.

[test_set_noise.txt](https://github.com/Rikorose/DeepFilterNet/files/13514163/test_set_noise.txt)
[test_set_speech.txt](https://github.com/Rikorose/DeepFilterNet/files/13514165/test_set_speech.txt)
[test_set_rirs.txt](https://github.com/Rikorose/DeepFilterNet/files/13514168/test_set_rirs.txt)
[training_set_speech03.txt](https://github.com/Rikorose/DeepFilterNet/files/13514147/training_set_speech03.txt)
[training_set_speech02.txt](https://github.com/Rikorose/DeepFilterNet/files/13514148/training_set_speech02.txt)
[training_set_speech01.txt](https://github.com/Rikorose/DeepFilterNet/files/13514151/training_set_speech01.txt)
[training_set_speech00.txt](https://github.com/Rikorose/DeepFilterNet/files/13514155/training_set_speech00.txt)
[training_set_noise.txt](https://github.com/Rikorose/DeepFilterNet/files/13514162/training_set_noise.txt)
[training_set_rirs.txt](https://github.com/Rikorose/DeepFilterNet/files/13514161/training_set_rirs.txt)
[validation_set_speech.txt](https://github.com/Rikorose/DeepFilterNet/files/13514156/validation_set_speech.txt)
[validation_set_rirs.txt](https://github.com/Rikorose/DeepFilterNet/files/13514159/validation_set_rirs.txt)
[validation_set_noise.txt](https://github.com/Rikorose/DeepFilterNet/files/13514160/validation_set_noise.txt)

**Comment by WoodieDudy** [comment]
I made a guide how to prepare dataset and train model  
https://github.com/WoodieDudy/open-source-stuff/tree/main/DeepFilerNet/prepare_dataset
