### ISSUE TITLE
Question: Stereo signal input

### ISSUE THREAD

**Issue by chillcloud-dev** [Rikorose/DeepFilterNet#473]
Hello, 
first of all, thanks for this amazing work. 

I am currently working on denoising a microphone array and I would like to know if your model supports stereo input. 

Is there any configuration that needs adjustment or a preprocessing step that needs to done before feeding the stereo signal into your model ? 

Thanks in advance !

**Comment by enricguso** [comment]
+1, I'd also use it in binaural if someone has the time to adapt it 

Thanks!

**Comment by chillcloud-dev** [comment]
@Rikorose 
Hi there
can you give us a short feedback ? 
Is it possible at least ?

**Comment by Qubitium** [comment]
Why dont you run and test it? If it doesnt support stereo just split stereo into two channels and run it twice?

**Comment by skinkie** [comment]
I have noticed that providing stereo to this tool (and quite some others) that there are temporal distortions between the tracks. That may also suggested that processing will cause lipsync issues. Now there is precombined stereo and there are multi track recordings which will be added to a stereo master. It seems that the model has quite some difficultly with panned speech input. If I would have had completely isolated recordings this would likely be less an issue. I also don't have issues with mono input of multiple speakers.
