### ISSUE TITLE
DeepFilterNet not clearing GPU cache

### ISSUE THREAD

**Issue by drohack** [Rikorose/DeepFilterNet#486]
Issue: When running DeepFilterNet on a piece of audio, then running faster_whisper on that audio to get the transcript the faster_whisper transcribe runs really slow (like 10x slower). Both are using Torch to use the GPU.

Fix: if I run `torch.cuda.empty_cache()` then faster_whisper runs just fine. 

This could be an issue where DeepFilterNet is not running the `empty_cache()` when it's done.
Or faster_whisper not running it ahead of time (though I wouldn't normally expect that to happen as empty_cache() isn't exactly instantaneous, so it's not guaranteed to clear the cache before it's function runs).

So please run `torch.cuda.empty_cache()` at the end of the `enhance()` function.

My code:
```
    print_with_timestamp("Reduce audio start")
    reduce_audio_file_path = os.path.join(temp_dir, "temp_reduced_audio.wav")
    df_model, df_state, _ = init_df()
    audio, _ = load_audio(temp_audio_file_path, sr=df_state.sr())
    enhanced = enhance(df_model, df_state, audio, atten_lim_db=6)
    # Save for listening
    save_audio(reduce_audio_file_path, enhanced, df_state.sr())
    # Clear GPU memory
    torch.cuda.empty_cache()
    print_with_timestamp("Reduce audio end")
```

**Comment by lnicola** [comment]
Not directly related, but you might want to be aware of https://github.com/Rikorose/DeepFilterNet/issues/483.

**Comment by Rikorose** [comment]
You can clear the cache on your own. I need to run enhance() multiple times so I do not want to clear the cache after each run.
