### ISSUE TITLE
Cannot set negative "--min-db-thresh"

### ISSUE THREAD

**Issue by Mikkolehtimaki** [Rikorose/DeepFilterNet#522]
Seems that the default value is `-15`. When trying to set a negative value, the following error is shown:

```
deep-filter --output-dir out-deepfilter -a 10 --min-db-thresh '-14' file.wav 
error: unexpected argument '-1' found

  tip: to pass '-1' as a value, use '-- -1'

Usage: deep-filter [OPTIONS] <FILES>...

For more information, try '--help'.

```

**Comment by lnicola** [comment]
So did you try `deep-filter file.wav --output-dir out-deepfilter -a 10 --min-db-thresh -- -14`?

**Comment by Mikkolehtimaki** [comment]
That results in `error: a value is required for '--min-db-thresh <MIN_DB_THRESH>' but none was supplied`

I'm sure there's something basic I'm missing. On Linux bash btw.

**Comment by tbarbugli** [comment]
what about `--min-db-thresh='-42'`?

**Comment by lnicola** [comment]
Right, `--min-db-thresh=-15` works :upside_down_face:.
