### ISSUE TITLE
training_set, valid_set, test_set and dataset.cfg

### ISSUE THREAD

**Issue by satvik-venkatesh** [Rikorose/DeepFilterNet#528]
Dear @Rikorose 

Thank you for this amazing project! Could you kindly provide the training_set.txt, valid_set.txt, test_set.txt, and dataset.cfg used to train DeepFilterNet2 on the DNS-4 challenge dataset? I am planning to reproduce the results and it would be helpful to know if I got the data correct before launching the entire training.

The paper says you have included only English examples, but does this include the singing, emotional, VCTK datasets? And did you oversample specific datasets for DeepFilterNet2?

I would be grateful if you could answer these questions. Thank you very much!

**Comment by WoodieDudy** [comment]
I made a guide how to prepare dataset and train model  
https://github.com/WoodieDudy/open-source-stuff/tree/main/DeepFilerNet/prepare_dataset
