### ISSUE TITLE
quesion on train  

### ISSUE THREAD

**Issue by l2009312042** [Rikorose/DeepFilterNet#54]
follow #31  and readme ,i have prepare the speech and noise hdf5 files and dateset.cfg file ,

the speech and noise data is from  dns challenge，the num is 50  and the batchsize i set is 2 

when i train the net ,erros occur as follows :
![image](https://user-images.githubusercontent.com/5296159/150058452-45199db1-4922-469a-a3fb-131c4ad3c8d7.png)

![image](https://user-images.githubusercontent.com/5296159/150058187-894fda10-680f-402b-8e92-7c1648efd9a4.png)

can you give me some advice to fix this error?  thanks

**Comment by l2009312042** [comment]
and sometime  it report anthor erro

**Comment by Rikorose** [comment]
The most relevant part of the log is the git commit. Could you tell me on which commit you are? The master branch is going under some changes and may currently be broken.

**Comment by l2009312042** [comment]
commit 528287c909656c0d5dd7419a40b90022e1d1ae7f (HEAD -> main, origin/main, origin/HEAD)

**Comment by Rikorose** [comment]
I recommend to use the last release from pypi. This should work.

**Comment by l2009312042** [comment]
thanks for your immediate reply， by  pip install deepfilternet ，the erro same occur 
![image](https://user-images.githubusercontent.com/5296159/150084622-d92c5471-fdbc-4d11-a752-9d1d4e1d7fc9.png)
the batchsize i set is 32 ，but the log is 33？
