### ISSUE TITLE
lsnr is not used, what is the use of this  variable? 

### ISSUE THREAD

**Issue by l2009312042** [Rikorose/DeepFilterNet#55]
`lsnr = self.lsnr_fc(emb) * self.lsnr_scale + self.lsnr_offset`

i found in the code，  this variable is calculated, but  not used for loss and other place ,so  what is the use of this target？

**Comment by Rikorose** [comment]
This is a frame-level SNR prediction. This can be used for a voice detection or to turn of the decoder/dfnet for parts where we only have noise (e.g. [here](https://github.com/Rikorose/DeepFilterNet/blob/1683235eebb2bd0441d165029a0174aae0c97acb/libDF/src/bin/df-tract.rs#L329))

**Comment by l2009312042** [comment]
thanks ,  this  make sense

**Comment by Rikorose** [comment]
Oh yea. It should be off, i.e. the other way round. The PR that I linked is not merged and could have some bugs.

But what the paper states is enforced via alpha. 
I.e. here
https://github.com/Rikorose/DeepFilterNet/blob/ae55008adcea72a78e96534d0fd17c275d657206/DeepFilterNet/df/deepfilternet.py#L279
and here
https://github.com/Rikorose/DeepFilterNet/blob/ae55008adcea72a78e96534d0fd17c275d657206/DeepFilterNet/df/loss.py#L262

**Comment by l2009312042** [comment]
thx,i got it
