### ISSUE TITLE
requirement files installation problem

### ISSUE THREAD

**Issue by kirti2k23** [Rikorose/DeepFilterNet#552]
I am trying to install requirements file but I am getting error ERROR: Failed building wheel for deepfilterdataloader. I even tried to install it using command pip install deepfilterdataloader individually but still not working.
Building wheel for deepfilterdataloader (pyproject.toml) ... error
error: subprocess-exited-with-error

**Comment by lichengxi1** [comment]
Me too, have you solved this?

**Comment by zxj329** [comment]
> Me too, have you solved this

have u solved this problem？can u tell me?
