### ISSUE TITLE
[BUG] Only works with sample rate == 48000

### ISSUE THREAD

**Issue by ManuLinares** [Rikorose/DeepFilterNet#569]
Using de ladspa plugin with carla and pipewire, if I open carla with any other sample rate than 48KHz, carla crashes.

---

How to reproduce:
open carla with `pw-jack -p 128 -s44100 carla` or `pw-jack -p 128 -s88200 carla` or `pw-jack -p 128 -s96000 carla`

Add ladspa plugin, `Aborted (dore dumped)`

---
System Archlinux:
libdeep_filter_ladspa-bin 0.5.6-1
linux 6.8.9.arch1-2
carla 2.5.8-1
pipewire 1:1.0.6-1

**Comment by dillfrescott** [comment]
It says under the readme: `Currently, only wav files with a sampling rate of 48kHz are supported.`

**Comment by ManuLinares** [comment]
Oh ok, but it didn't mention the LADSPA plugin.

**Comment by dillfrescott** [comment]
I think its because of the ai model itself and how it was trained so its probably universal
