### ISSUE TITLE
the window should be used after square? in the transposed  calculation of  istft  in stoi.py， 

### ISSUE THREAD

**Issue by l2009312042** [Rikorose/DeepFilterNet#57]
https://github.com/Rikorose/DeepFilterNet/blob/1819b97f50920f63db90410419cab1031b44adaf/DeepFilterNet/df/stoi.py#L95

the way to calculate istft by transposed  convolution，i think the window should be square then to be used  ，

which i compare  is  as follow
[istft](https://github.com/huyanxin/DeepComplexCRN/blob/bc6fd38b0af9e8feb716c81ff8fbacd7f71ad82f/conv_stft.py#L98)

the reference  i have checked,it is the same as librosa istft

**Comment by Rikorose** [comment]
There are many ways to calculate an STFT. You should probably compare to the stoi reference implementation or maybe pystoi. As far as I remember, I did some tests against pystoi.
