### ISSUE TITLE
16k model training configuration and 16k pre-trained model

### ISSUE THREAD

**Issue by lhbing-ai** [Rikorose/DeepFilterNet#576]
Hi, I need to train a 16 kHz model for noise removal in the meeting scenario, and there are two questions: 
1. If I train based on 16K audio data, what modifications need to be made in the config.ini, for example, is it okay for me like this? 
[df]
sr = 16000
fft_size = 480
hop_size = 240
nb_erb = 16
nb_df = 48

Is that so? Are there any other places that need to be modified to make the model effect optimal?

2. Are there any 16k pre-trained models? Thank you very much.

**Comment by zzgnb** [comment]
I met the same confusion, have you ever solved it? Thanks for reply.
