### ISSUE TITLE
Crashes when p_reverb=1.0 (both with DNS5 and SoundSpaces rirs)

### ISSUE THREAD

**Issue by enricguso** [Rikorose/DeepFilterNet#584]
When changing the default DFN3 recipe p_reverb to 1.0, it crashes during training, both for DNS and SoundSpaces RIR datasets.

2024-07-03 12:04:30 | TRACE    | libdfdata.torch_dataloader:df:dataset:1275 | Sampled RIR .._.._guso_│
in24_rirs_train_SSmp3d_left_SSmp3d_left_Vt2qJdWjCF2_84_160.wav with shape [1, 8072]                  │
thread '<unnamed>' panicked at 'assertion failed: k <= self.len()', /rustc/5680fa18feaa87f3ff04063800│
aec256c3d4b4be/library/core/src/slice/mod.rs:3420:9                                                  │
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace                        │
Aborted (core dumped)                                                                                │

Removing that particular RIR from the dataset seems to fix it, but the error appears very often making it hard to train.

Anyone has found a fix for this? Thanks

**Comment by Rikorose** [comment]
> Removing that particular RIR from the dataset seems to fix it, but the error appears very often making it hard to train.

Do you mean that removing `..._SSmp3d_left_SSmp3d_left_Vt2qJdWjCF2_84_160.wav` RIR seems to fix it? It then might be the problem with the shape. Maybe try to reshape it to a 1D Tensor `[8072]`.

If this does not help, insert some `dbg()` messages within `RandReverbSim::transform()` in augmentation.rs

**Comment by enricguso** [comment]
Thanks for your answer, @Rikorose. We've been digging a bit more into it and basically these IRs seem to be loaded incorrectly resulting into empty arrays. 

We've modified `libDF/src/dataset.rs::1271` so when this happens we add a trivial IR:

`let mut speech_distorted = {
           if !self.rir_keys.is_empty() {
               self.reverb.transform(&mut speech, &mut noise, || {
                   let (rir_name, rir_key) = self.rir_keys.iter().choose(&mut rng).unwrap();

                   // here the result is unwrapped if it's valid,
                   // otherwise the calling function propagates the error
                   // (questionmark operator)
                   // if we want to mutate it, we need to add the "mut"
                   // keyword ..
                   let mut rir = self.read(rir_name, rir_key)?;

                   log::trace!("Sampled RIR {} with shape {:?}", rir_key, rir.shape());

                   if rir.sum() == 0.0 {
                       log::trace!(
                           "Sampled RIR {} is empty, turning it into a dirac RIR",
                           rir_key
                       );
                       // read returns a 2D array, so the 0 element
                       // should be accessed like so:
                       rir[[0, 0]] = 1.0;
                   }

                   Ok(rir)
               })?
           } else {
               None
           }
       }
       .unwrap_or_else(|| speech.clone());`

and then the same at `libDF/src/dataset.rs::1343` :

`if let Some((rir_name, rir_key)) = self.rir_keys.iter().choose(&mut rng) {
                   let mut rir = self.read(rir_name, rir_key)?;

                   log::trace!("Sampled RIR {} with shape {:?}", rir_key, rir.shape());

                   if rir.sum() == 0.0 {
                       log::trace!(
                           "Sampled RIR {} is empty, turning it into a dirac RIR",
                           rir_key
                       );
                       // read returns a 2D array, so the 0 element
                       // should be accessed like so:
                       rir[[0, 0]] = 1.0;
                   }

                   self.reverb.transform_single(&mut speech, rir)?;
               }`
Then compiled again with pyDF and pyDF-data. Hope this helps! Thank you
