### ISSUE TITLE
Question about WAV Encoding

### ISSUE THREAD

**Issue by zhs2326** [Rikorose/DeepFilterNet#62]
Hi, thanks for your amazing work! I have some questions about the wav encoding. For the training and test script, which encoding(signed 16, signed 32, float 32) is supported? Thank you!

**Comment by Rikorose** [comment]
Hi there, the model requires float32 input, but I think the enhance.py script should work with every input and do the conversion automatically.

**Comment by zhs2326** [comment]
Great! I use float32 input now, and it works fine for me. BTW, if I set the sr to 16000, and train and inference the model on 16000 Hz audios, which hyper-parameters(e.g. nb_erb) would you recommending tuning in order to get a relatively better performance? Thanks!

**Comment by Rikorose** [comment]
You could start with nb_erb=16, nb_df=48, fft_size=480, hop=240 for a sr of 16kHz
