### ISSUE TITLE
Ability to run on CPU

### ISSUE THREAD

**Issue by egorsmkv** [Rikorose/DeepFilterNet#624]
It would be useful to have an additional `device` parameter in `init_df` function to load the model on CPU.

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the init_model function in DeepFilterNet/df/model.py to include a device parameter, allowing the model to be loaded on a specified device (e.g., CPU or GPU).

You can review changes in this commit: https://github.com/mark-addams001881/Rikorose-DeepFilterNet-624/commit/1ca333cebb59950b33acd03f96237e6c9a7bd75b.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by egorsmkv** [comment]
Figured out that https://github.com/Rikorose/DeepFilterNet/pull/619 actually proposes this ability
