### ISSUE TITLE
Read the hdf5 file failed

### ISSUE THREAD

**Issue by Tim5Tang** [Rikorose/DeepFilterNet#65]
I want to reproduce your job ,but when i run the train,  load the hdf5 failed.

2022-03-01 14:40:46 | INFO     | DF | Running on torch 1.10.0
2022-03-01 14:40:46 | INFO     | DF | Running on host ultralab-server
2022-03-01 14:40:46 | INFO     | DF | Git commit: 05da995, branch: main
2022-03-01 14:40:46 | INFO     | DF | Running on device cuda:0
2022-03-01 14:40:46 | INFO     | DF | Initializing model `deepfilternet`
2022-03-01 14:40:53 | WARNING  | DF | Failed to print model summary: No module named 'ptflops'
2022-03-01 14:40:53 | INFO     | DF | Running with normalization window alpha = '0.996'
2022-03-01 14:40:53 | INFO     | DF | Initializing dataloader with data directory ../data/dns/
2022-03-01 14:40:53 | ERROR    | DF | An error has been caught in function '<module>', process 'MainProcess' (19629), thread 'MainThread' (140105826391808):
Traceback (most recent call last):

> File "df/train.py", line 425, in <module>
    main()
    └ <function main at 0x7f6cccc270d0>

  File "df/train.py", line 103, in main
    dataloader = DataLoader(
                 └ <class 'libdfdata.torch_dataloader.PytorchDataLoader'>

  File "/home/tangzixing/data/deeplearning/program/audio/DeepFilterNet-0.1.10/pyDF-data/libdfdata/torch_dataloader.py", line 99, in __init__
    self.loader = _FdDataLoader(
    │             └ <class 'builtins._FdDataLoader'>
    └ <libdfdata.torch_dataloader.PytorchDataLoader object at 0x7f6ccc9ae460>

RuntimeError: DF dataset error: Hdf5ErrorDetail { source: H5Fopen(): unable to open file: bad superblock version number, msg: "Error during File::open of dataset ../data/dns/val_speech.hdf5" }

**the h5py verision is 3.6.0
h5py.version.hdf5_version is 1.2.1**

**which version of h5py you use ?**

**Comment by Rikorose** [comment]
Hi there,

I use the same h5py version (3.6.0).
How did you generate your datasets ('../data/dns/val_speech.hdf5')? Does it work to open them via h5py?
Could you try to open the testing datasets in the assets folder? Does `cargo test` work?

**Comment by Tim5Tang** [comment]
i use the the follow cmd to generate datasets:
python df/scripts/prepare_data.py noise ../data/list/val_noise.txt ../data/dns/val_speech.hdf5 --sr 48000 --num_workers 4

**Comment by Tim5Tang** [comment]
I use the the follow cmd to generate datasets:
python df/scripts/prepare_data.py noise ../data/list/val_noise.txt ../data/dns/val_speech.hdf5 --sr 48000 --num_workers 4

and i used python test read the hdf5
import h5py
import sys
file = h5py.File(sys.argv[1], 'r')
print(file.keys())

**Test the hdf5 i generate:**
python testh5py.py data/dns/val_speech.hdf5
<KeysViewHDF5 ['speech']>
**Test the assets hdf5:**
 python testh5py.py ../DeepFilterNet/assets/clean.hdf5
<KeysViewHDF5 ['speech']>

**Comment by Tim5Tang** [comment]
i alse run the cargo test
   Compiling DeepFilterLib v0.1.10 (/home/*/data/deeplearning/program/audio/DeepFilterNet-0.1.10/pyDF)
    Finished test [unoptimized + debuginfo] target(s) in 12.89s
     Running unittests (/home/tangzixing/data/deeplearning/program/audio/DeepFilterNet-0.1.10/target/debug/deps/libdf-0a45b61dd403e40a)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


   Compiling DeepFilterDataLoader v0.1.10 (/home/tangzixing/data/deeplearning/program/audio/DeepFilterNet-0.1.10/pyDF-data)
    Finished test [unoptimized + debuginfo] target(s) in 18.98s
     Running unittests (/home/tangzixing/data/deeplearning/program/audio/DeepFilterNet-0.1.10/target/debug/deps/libdfdata-6c4c22948509ab29)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

**Comment by Rikorose** [comment]
You did not run any tests:
> running 0 tests

Please run it in the root directory. It should look like this:
```
$ cargo test
   Compiling deep_filter v0.1.11-pre (/home/hendrik/projects/DeepFilterNet/libDF)
   Compiling DeepFilterLib v0.1.11-pre (/home/hendrik/projects/DeepFilterNet/pyDF)
   Compiling DeepFilterDataLoader v0.1.11-pre (/home/hendrik/projects/DeepFilterNet/pyDF-data)
    Finished test [unoptimized + debuginfo] target(s) in 11.29s
     Running unittests (target/debug/deps/libdfdata-3dab9df1ac6f0f5d)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/libdf-2be8b528664fdd3a)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/df-6fc14f0d3126efdf)

running 20 tests
test reexport_dataset_modules::dataset::tests::test_hdf5_slice::case_01 ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_slice::case_02 ... ok
test reexport_dataset_modules::augmentations::tests::test_rand_resample ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_slice::case_03 ... ok
test reexport_dataset_modules::augmentations::tests::test_low_pass ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_slice::case_05 - should panic ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_slice::case_06 - should panic ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_slice::case_07 - should panic ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_slice::case_04 - should panic ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_read_pcm ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_slice::case_08 ... ok
test reexport_dataset_modules::util::test_find_max_abs ... ok
test tests::test_erb_inout ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_slice::case_10 ... ok
test reexport_dataset_modules::augmentations::tests::test_reverb ... ok
test reexport_dataset_modules::dataset::tests::test_hdf5_slice::case_09 ... ok
test reexport_dataset_modules::dataset::tests::test_mix_audio_signal ... ok
git test reexport_dataset_modules::dataset::tests::test_hdf5_read_flac ... ok
stattest reexport_dataset_modules::dataset::tests::test_hdf5_read_vorbis ... ok
us
test reexport_dataset_modules::dataloader::tests::test_fft_dataset ... ok

test result: ok. 20 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 30.29s

   Doc-tests df

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

**Comment by Tim5Tang** [comment]
ok thanks, i will rebuild my env and test it.

**Comment by Tim5Tang** [comment]
Maybe i have locate this question, the hdf5 i have installed in the system with the command "sudo apt-get install libhdf5-dev" is 1.8.16
I also install hdf5 1.12.1 by the source code in the /usr/local/, but the hdf5-rust find the 1.8.16
**Do you known how to let the hdf5-rust find the /usr/local hdf5**
And i will try to down the h5py version to math the libhdf5-dev version.
running 20 tests
test reexport_dataset_modules::util::test_find_max_abs ... ok
test tests::test_erb_inout ... ok
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140371722127104:
  #000: ../../../src/H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: ../../../src/H5Fint.c line 1087 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: ../../../src/H5Fsuper.c line 294 in H5F_super_read(): unable to load superblock

**Comment by Tim5Tang** [comment]
i **reinstall the hdf5 by the source and use the config "sudo ./configure --prefix=/usr/"** to replace the hdf5 installed by apt-get, and rebuild the deepfilter, the test passed and i can train. Thanks.
