### ISSUE TITLE
Question on dataloader in training.py

### ISSUE THREAD

**Issue by ChandanaJonna** [Rikorose/DeepFilterNet#68]
I am working on training setup. I got below error in run_epoch function in [train.py.]

ERROR:-
> File "/DeepFilterNet-main/DeepFilterNet/df/train.py", line 479, in <module>
    main()
    └ <function main at 0x7f74abd598b0>

  File "/DeepFilterNet-main/DeepFilterNet/df/train.py", line 173, in main
    train_loss = run_epoch(
                 └ <function run_epoch at 0x7f74abd665e0>

  File "/DeepFilterNet-main/DeepFilterNet/df/train.py", line 265, in run_epoch
    assert batch.feat_spec is not None
           │     └ None
           └ Batch of size 1:
                 length: 240000
                 snr: -5
                 gain: 0
            
**AssertionError: assert batch.feat_spec is not None**

# usage: train.py [-h] [--debug] data_config_file data_dir base_dir
python df/train.py ../assets/dataset.cfg ../assets/ df/new_config
Config file used
{
    "test": [
        [
            "clean.hdf5",
            100
        ],
        [
            "noise.hdf5",
            10
        ]
    ],
    "train": [
        [
            "clean.hdf5",
            10000
        ],
        [
            "noise.hdf5",
            10
        ]
    ],
    "valid": [
        [
            "clean.hdf5",
            100
        ],
        [
            "noise.hdf5",
            10
        ]
    ]
}

I used above configuration file(dataset.cfg file available in Deepfilternet-main/assets/ directory).

It is saying that batch.feat_spec doesn't contain any information. Do we need to write batch.feat_spec and batch.feat_erb while writing to hdf5 file itself or dataloader function will extract these features?? . 

Is train.py using predefined dataloader from torch.utils.data or it is taking from "C:\DFnet\DeepFilterNet-main\pyDF-data\libdfdata\torch_dataloader".

 Can u help me out to resolve this error (**AssertionError: assert batch.feat_spec is not None**). Hope to hear from you soon.

Thanks in advance.

![error_train](https://user-images.githubusercontent.com/101628409/158346703-505d119e-297f-4928-8ffc-99d81c4b29a0.PNG)
![Uploading error_train.PNG…]()

**Comment by Rikorose** [comment]
Hi,

which version (or git commit) are you using? Did you change anything from the default configuration?

**Comment by ChandanaJonna** [comment]
Hi @Rikorose 

I downloaded the source code from this path https://github.com/Rikorose/DeepFilterNet.  The issue mentioned above "AssertionError: assert batch.feat_spec" is got fixed.  
ERB features(feat_erb), Spectral features (feat_spec) are calculating from  _FdDataLoader() function using libdfdata library.  I would like to know how these features are extracted.. Is there any code available to understand for _FdDataLoader() function.

Thank you

**Comment by Rikorose** [comment]
You could take a look at the [paper](https://arxiv.org/abs/2110.05588).
In the code, the erb filter bank is initialized [here](https://github.com/Rikorose/DeepFilterNet/blob/main/libDF/src/lib.rs#L52), the erb featrues are exponentially normalized [here](https://github.com/Rikorose/DeepFilterNet/blob/main/libDF/src/lib.rs#L174) and the complex features [here](https://github.com/Rikorose/DeepFilterNet/blob/main/libDF/src/lib.rs#L183).
