### ISSUE TITLE
What is up with the canned deepFilter?

### ISSUE THREAD

**Issue by Joeweav** [Rikorose/DeepFilterNet#75]
(DeepFilterNet) C:\Users\sdr\Downloads\Playground\DeepFilterNet>deepFilter test.wav
Traceback (most recent call last):
  File "C:\Users\sdr\anaconda3\envs\DeepFilterNet\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sdr\anaconda3\envs\DeepFilterNet\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\sdr\anaconda3\envs\DeepFilterNet\Scripts\deepFilter.exe\__main__.py", line 7, in <module>
TypeError: main() missing 1 required positional argument: 'args'

(DeepFilterNet) C:\Users\sdr\Downloads\Playground\DeepFilterNet>

**Comment by Rikorose** [comment]
Hi there,

thanks for your interest in DeepFilterNet and reporting this problem. I will provide a fix.

In the meanwhile, `python DeepFilterNet/df/enhance.py test.wav` should work.

**Comment by Rikorose** [comment]
Should be fixed on master. If you installed DeepFilterNet via pip, you could update with `pip install --update git+https://github.com/Rikorose/DeepFilterNet/`

**Comment by Joeweav** [comment]
Thank you for the reply.

I tried the line you suggested but that said --update was not an option, I
looked at the help and --upgrade is so I tried that but that did not work:

(DeepFilterNet) C:\Users\sdr\Downloads\Playground\DeepFilterNet> pip
install --upgrade git+https://github.com/Rikorose/DeepFilterNet/
Collecting git+https://github.com/Rikorose/DeepFilterNet/
  Cloning https://github.com/Rikorose/DeepFilterNet/ to
c:\users\sdr\appdata\local\temp\pip-req-build-0313svgy
  Running command git clone --filter=blob:none --quiet
https://github.com/Rikorose/DeepFilterNet/
'C:\Users\sdr\AppData\Local\Temp\pip-req-build-0313svgy'
  Resolved https://github.com/Rikorose/DeepFilterNet/ to commit
afe6bfb53efae70207e18df7ed372c2cfe337fee
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      error: Multiple top-level packages discovered in a flat-layout:
['pyDF', 'libDF', 'assets', 'DeepFilterNet'].

      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.

      If you are trying to create a single distribution with multiple
packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:

      1. set up custom discovery (`find` directive with `include` or
`exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names

      To find more information, look for "package discovery" on setuptools
docs.
      [end of output]

  note: This error originates from a subprocess, and is likely not a
problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem
with pip.

As far as getting the python code to run, I have been going around the
block with it for a while now.  The last step:

poetry install -E train -E eval --no-root

Attempts to downgrade numpy:

Updating numpy (1.22.3 -> 1.21.1)

And it tries to build 1.21.1 from sources and has errors all over the place.

**Comment by Rikorose** [comment]
My bad, I forgot you only need to update the wheel in the DeepFilterNet directory.

I guess, until I cut a new release, you need to follow the development instructions in the readme or use the workaround `python DeepFilterNet/df/enhance.py test.wav` instead of `deepFilter test.wav`.

**Comment by Rikorose** [comment]
I pushed a new release. Could you test `pip install -U deepfilternet`?

**Comment by Joeweav** [comment]
Howdy, and thank you for looking into this for me.  I hit on a few things
on my own along the way.

I wiped out the old environment as nothing was working anyway, and started
fresh, I had to also install PySoundFile but after that the compiled
version of deepFilter worked.  I have not had a chance to review
the results yet, but the program came up and ran.

On the self build version, I think you have been working on it for a long
time, thank you for sharing your work, but there are a lot of pieces
missing in the recipe to get it to build.  You need to install rust, cmake,
and hdf5, I may have forgot a few other pieces.  The last issue was it
could not import something that was in the df directory, I think that was
where the peril of wisdom about setting the pythonpath came into play, but
I had not had the time to chase down how to do that.  I think I was close
with the build it yourself version.  At some point you may want to review
your build environment and figure out all the pieces that are necessary to
build it and update the recipe.

Thank you for taking the time to look into this for me.

**Comment by Rikorose** [comment]
You don't need to install from source, since I pushed a new release to pypi. Just running `pip install -U deepfilternet` should install the latest 0.1.11 DeepFilterNet which fixes this bug.

**Comment by Joeweav** [comment]
Yes, I understand that, but when the pre built one was not working I gave
the source a good go.
