### ISSUE TITLE
Implement a real-time loop for DeepFilterNet

### ISSUE THREAD

**Issue by StuartIanNaylor** [Rikorose/DeepFilterNet#76]
Hi Hendrik,
Just curious as didn't see any benchmarks but could it run chunking audio as it goes or does it need the overall file to analyse?
How does it compare to https://github.com/breizhn/DTLN?

Thanks
Stuart

**Comment by Rikorose** [comment]
Hi Stuart,

thanks for your interest in this project. As of now, no real-time loop is available. There is a WIP version in #13, but it has a bug in the 2nd stage resulting in worse audio quality.
So this is definitely planned, but I cannot give an ETA.

**Comment by StuartIanNaylor** [comment]
No probs but great to hear as been wondering how it compares to https://github.com/breizhn/DTLN so if you would if you remember add a comment so that I see it in notifications.
Also just out curiosity but is there any method that is purely to extract a single KW (Keyword) from noise as voicefilter-lite is targeted speaker extraction as an example is it possible to do targeted KW extraction? For want of a better description.

**Comment by Rikorose** [comment]
Ideally a real-time loop would be implemented in Rust, so we can ship a compiled binary without any dependencies.

**Comment by isgursoy** [comment]
> Hi Stuart,
> 
> thanks for your interest in this project. As of now, no real-time loop is available. There is a WIP version in #13, but it has a bug in the 2nd stage resulting in worse audio quality. So this is definitely planned, but I cannot give an ETA.

is it still the case right now after v0.2.3?

**Comment by Rikorose** [comment]
Still the case as long as this issue is open.

**Comment by isgursoy** [comment]
Relevant https://github.com/Rikorose/DeepFilterNet/issues/106

**Comment by andyweiqiu** [comment]
Simple implementation of a real-time, you can experience
https://github.com/andyweiqiu/denoiser-realtime-48k-ios

**Comment by Rikorose** [comment]
Thanks for the link. It would be great, if you would contribute back to the open source community and open source the denoising loop as well.

**Comment by Rikorose** [comment]
Hi folks, I released a real time loop fully written in Rust. You can download a `deep-filter` executable in the latest 0.3.0 release.
