### ISSUE TITLE
About whitenoise performance

### ISSUE THREAD

**Issue by sqummy** [Rikorose/DeepFilterNet#81]
Thanks for your awesome work!
I have installed deepfilternet through pip and test some samples.  The overall noise reduction effect is great, but in whitenoise scene, there are more residues in the speech, which leads to a poor subjective feelings. 
Have you noticed this phenomenon? I will attach the samples below.
[samples.zip](https://github.com/Rikorose/DeepFilterNet/files/8684478/samples.zip)

**Comment by Rikorose** [comment]
Hi, thanks for your interest in DeepFilterNet! The sample you provided has a very bad SNR (I guess <-10dB). Even though DeepFitlerNet2's performance is quite good, these bad SNRs are too challenging I guess. Do you have some other approaches that sound well given this SNR?

**Comment by sqummy** [comment]
The SNR of the previous zip file is indeed low, I replaced a zip file with a higher SNR. My main question is why  the residue exists in speech, and in non-speech segments the effect is relatively better. Intuitively, whitenoise should be easy to deal with.
[samples_higer_snr.zip](https://github.com/Rikorose/DeepFilterNet/files/8684834/samples_higer_snr.zip)

**Comment by Rikorose** [comment]
I get a different output than you:
[femaleSNR20dB_DeepFilterNet2.zip](https://github.com/Rikorose/DeepFilterNet/files/8684922/femaleSNR20dB_DeepFilterNet2.zip)
This sounds much better.

Could you send me some logs to see if something went wrong when you processed the samples?

**Comment by sqummy** [comment]
![Uploading 20220513152925.jpg…]()

**Comment by sqummy** [comment]
![20220513152925](https://user-images.githubusercontent.com/24407386/168233566-21574deb-d914-46b3-885a-d0e491a0e10e.jpg)

**Comment by sqummy** [comment]
Is there something wrong?

**Comment by Rikorose** [comment]
Seems like DeepFilterNet 1 is loaded. I will push a new release that includes the new DeepFilterNet2 checkpoints soon. The new model should provide a better performance.

**Comment by sqummy** [comment]
Thanks

**Comment by Rikorose** [comment]
Hi I pushed a new release. Could you update with: `pip install -U deepfilternet` and try again?
