### ISSUE TITLE
about test_erb function

### ISSUE THREAD

**Issue by ioyy900205** [Rikorose/DeepFilterNet#88]
Dear Author, I am having problems with test_erb in modules.py in the df folder.
![image](https://user-images.githubusercontent.com/76168691/169680510-476d6fac-1d2d-4c8c-aeb8-af5752ef7ca9.png)

**Comment by Rikorose** [comment]
You didn't install the deep filter rust module, see Readme.

**Comment by ioyy900205** [comment]
I re-git clone your repository
and finished the installation according to the manual installation, but I still get this error.
My system is WSL

**Comment by Rikorose** [comment]
f you did please provide some more information including:

    DeepFilterNet git commit
    rust version
    maturin version
    build logs

**Comment by Rikorose** [comment]
Indeed this test was using an old API and is currently not tested in CI as most python tests. Thanks for reporting.
