### ISSUE TITLE
errors when trying to process wav files on Windows

### ISSUE THREAD

**Issue by musicalman** [Rikorose/DeepFilterNet#89]
Hello,
I was trying to test deepfilternet on Windows. I don't know much about the technical aspects or Python in general though, and consequently I am getting errors and I don't know the cause.
I ran these commands from the readme:
pip install torch torchaudio -f https://download.pytorch.org/whl/cpu/torch_stable.html
pip install deepfilternet
(So far, no errors)
deepFilter test.wav
(Test.wav is just a placeholder to the path to a real file)

I tried both with Python 3.10 (latest) and 3.7 as suggested by the deepfilterlib page on pypi. In both cases I get errors that no audio backend is available, and that libdf couldn't be found.
Any advice would be greatly appreciated. Thanks in advance!

**Comment by Rikorose** [comment]
Hi could you provide some stack traces showing the full error messages?

No audio backend is related to torch audio. You mal have a look in their documentation.

**Comment by musicalman** [comment]
Thanks for your reply.
I needed to install PySoundFile. Now the audio backend error is gone, but libdf error still remains. The traceback is below:
Traceback (most recent call last):
  File "c:\users\raymond\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\raymond\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Raymond\AppData\Local\Programs\Python\Python37\Scripts\deepFilter.exe\__main__.py", line 4, in <module>
  File "c:\users\raymond\appdata\local\programs\python\python37\lib\site-packages\df\enhance.py", line 17, in <module>
    from df.checkpoint import load_model as load_model_cp
  File "c:\users\raymond\appdata\local\programs\python\python37\lib\site-packages\df\checkpoint.py", line 14, in <module>
    from libdf import DF
  File "c:\users\raymond\appdata\local\programs\python\python37\lib\site-packages\libdf\__init__.py", line 1, in <module>
    from .libdf import *
ImportError: DLL load failed: The specified module could not be found.

**Comment by Rikorose** [comment]
Which deep filter version are you using?
Could you try reinstalling deepfilterlib: `pip install -U deepfilterlib`.

I don't have access to a windows machine, but in CI, windows is working. You may also have a look at the CI: https://github.com/Rikorose/DeepFilterNet/blob/main/.github/workflows/test_df.yml

**Comment by musicalman** [comment]
I tried updating.
Requirement already up-to-date: deepfilterlib in c:\users\raymond\appdata\local\programs\python\python37\lib\site-packages (0.2.3)
Requirement already satisfied, skipping upgrade: numpy>=1.20 in c:\users\raymond\appdata\local\programs\python\python37\lib\site-packages (from deepfilterlib) (1.21.6)
I'm not familiar with how to test with CI and using the yml configs and stuff, but I'll look into it and see if I can figure something out.

**Comment by Rikorose** [comment]
Hi I pushed 0.2.4 release. Could you update and test again?
