### ISSUE TITLE
Question for metric evaluation file

### ISSUE THREAD

**Issue by ndisci** [Rikorose/DeepFilterNet#98]
Hi, thanks for this work !  I have some questions about calculation of STOI. How can we use evaluation_utils.py ?  Could you explain it with an example or add some explanations to README  ?
When I try to get result I always see this exception  'x and y should have the same length' . I am using your pretrained DeepFilterNet2 model and Valentini test dataset . The clean and enhanced tensor length are close but not same.

**Comment by Rikorose** [comment]
Hi, in general, most SE metrics require the same length an alignment. Thus, you need to make sure that the enhanced audio does not contain any latency and trim it to the original length. Or you need to process the clean reference via the stft/istft to introduce the same latency and padding. You can have a `evaluation_loop()` how I did this.
