### ISSUE TITLE
Question about DNSMOS

### ISSUE THREAD

**Issue by TAWHT** [Rikorose/DeepFilterNet#99]
Hi, thanks for this work. I have some questions about DNSMOS.
I tested the raw blind test set and deepfilter2 results with the DNSMOS tool (https://github.com/microsoft/DNS-Challenge dnsmos.py). Both results are different from your paper. What preprocessing did you do to the blind test set?

**Comment by Rikorose** [comment]
How did you test exactly? Please provide code and instructions to reproduce your claims. The paper results are obtained using https://github.com/Rikorose/DeepFilterNet/blob/ac9c803/DeepFilterNet/df/evaluation_utils.py#L90=

**Comment by TAWHT** [comment]
Ok i will try this file. My previous tests used this one.
python DeepFilterNet/df/enhance.py -m DeepFilterNet2 path/to/noisy_audio.wav
The results are then scored by DNSMOS tool.

**Comment by Rikorose** [comment]
You could try to to use the `-D` option to compensate for the STFT delay.
